# Generated by Django 4.1.5 on 2023-01-09 14:49

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_session_duration_manual_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="duration_manual",
            field=models.DurationField(
                blank=True, default=datetime.timedelta(0), null=True
            ),
        ),
    ]
