# Generated by Django 4.1.4 on 2022-12-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_purchase_date_purchased_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="date_refunded",
            field=models.DateField(blank=True),
        ),
    ]
