# Generated by Django 4.1.4 on 2022-12-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_alter_purchase_date_refunded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="date_refunded",
            field=models.DateField(blank=True, null=True),
        ),
    ]
