# Generated by Django 4.1.4 on 2022-12-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_alter_purchase_date_refunded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="duration_calculated",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="duration_manual",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
