---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: python:3.10
  commands:
    - VIRTUAL_ENV=/opt/venv
    - "python3 -m venv pip $VIRTUAL_ENV"
    - PATH="$VIRTUAL_ENV/bin:$PATH"
    - python -m pip install poetry
    - poetry install
    - poetry env info
    - pytest
- name: build container
  image: plugins/docker
  settings:
    repo: registry.kucharczyk.xyz/timetracker
    tags:
      - latest
trigger:
  event:
  - push
  - cron
  exclude:
    - pull_request