---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: python:3.10
  commands:
    - python -m pip install poetry
    - poetry install
    - poetry env info
    - poetry run pytest
- name: build container
  image: plugins/docker
  settings:
    repo: registry.kucharczyk.xyz/timetracker
    tags:
      - latest
trigger:
  event:
  - push
  - cron
  exclude:
    - pull_request