---
services:
  timetracker:
    image: ${REGISTRY_URL:-registry.kucharczyk.xyz}/timetracker:1.7.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timetracker
    environment:
      - TZ=${TZ:-Europe/Prague}
      - CSRF_TRUSTED_ORIGINS=https://tracker.kucharczyk.xyz
      - PUID=${PUID:-1000}
      - PGID=${PGID:-100}
      - DATA_DIR=${DATA_DIR:-/home/timetracker/app/data}
      - CREATE_DEFAULT_SUPERUSER=${CREATE_DEFAULT_SUPERUSER:-false}
    ports:
      - "${TIMETRACKER_EXTERNAL_PORT:-8000}:8000"
    volumes:
      - "./data:/home/timetracker/app/data"
      - "${DOCKER_STORAGE_PATH:-/tmp}/timetracker/backups:/home/timetracker/app/games/fixtures/backups"
    restart: unless-stopped

