[tool.poetry]
name = "timetracker"
version = "0.0.0"
description = "A simple time tracker."
authors = ["Lukáš Kucharczyk <lukas@kucharczyk.xyz>"]
license = "GPL"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.1.4"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
mypy = "^0.991"
pyyaml = "^6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
