[tool.poetry]
name = "timetracker"
version = "1.5.2"
description = "A simple time tracker."
authors = ["Lukáš Kucharczyk <lukas@kucharczyk.xyz>"]
license = "GPL"
readme = "README.md"
packages = [{include = "timetracker"}]

[tool.poetry.group.main.dependencies]
python = "^3.11"
django = "^4.2.0"
gunicorn = "^21.2.0"
uvicorn = "^0.20.0"
graphene-django = "^3.1.5"
django-htmx = "^1.17.2"
django-template-partials = "^23.4"
markdown = "^3.5.2"

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"
mypy = "^1.9.0"
pyyaml = "^6.0"
pytest = "^8.1.1"
django-extensions = "^3.2.1"
djhtml = "^3.0.6"
djlint = "^1.19.11"
isort = "^5.11.4"
pre-commit = "^3.5.0"
django-debug-toolbar = "^4.2.0"


[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
timetracker-import = "common.import_data:import_from_file"
