# Generated by Django 4.1.4 on 2023-01-02 18:55

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="duration_manual",
            field=models.DurationField(
                blank=True, default=datetime.timedelta(0), null=True
            ),
        ),
    ]
