"""Unit tests for the structural TypedDict->TS emitter (issue #247 / #284)."""

import json
from enum import Enum
from typing import Literal, TypedDict, get_type_hints

import pytest

import common.criteria
from common.components.ts_codegen import (
    TsConstant,
    render_choice_vocabulary,
    render_filter_metadata_module,
)
from common.criteria import (
    SPACE_GROUPS,
    ComparableColumn,
    FieldMeta,
    Modifier,
    ModifierToken,
)


# Module-level so get_type_hints can resolve the "Tree" forward reference.
class Tree(TypedDict):
    label: str
    children: list["Tree"]  # self-referential -> exercises the recursion guard


class Shared(TypedDict):
    x: str


class RootA(TypedDict):
    shared: Shared


class RootB(TypedDict):
    shared: Shared


def test_emits_field_meta_and_comparable_column_interfaces() -> None:
    output = render_filter_metadata_module([FieldMeta, ComparableColumn])
    assert "export interface FieldMeta {" in output
    assert "export interface ComparableColumn {" in output


def test_includes_previously_drifted_fields() -> None:
    # The hand-mirror had dropped these; codegen restores them (the whole point).
    output = render_filter_metadata_module([FieldMeta])
    assert "search_url: string;" in output
    assert "is_m2m: boolean;" in output


def test_nested_typeddicts_are_emitted_and_referenced_as_arrays() -> None:
    output = render_filter_metadata_module([FieldMeta])
    assert "export interface ChoiceMeta {" in output
    assert "export interface RelationTarget {" in output
    assert "choices: ChoiceMeta[];" in output
    assert "relations: RelationTarget[];" in output


def test_literal_alias_becomes_a_string_union() -> None:
    output = render_filter_metadata_module([ComparableColumn])
    assert (
        'export type ComparisonGroup = "date" | "datetime" | "duration" | '
        '"number" | "string" | "bool";' in output
    )


def test_union_alias_of_alias_and_literal_renders_both() -> None:
    # FieldMetaKind = LeafWidgetKind | Literal["relation"] — the only branch where
    # a `X | Y` union combines a nested alias arm with an inline Literal arm.
    output = render_filter_metadata_module([FieldMeta])
    assert 'export type FieldMetaKind = LeafWidgetKind | "relation";' in output
    assert (
        'export type LeafWidgetKind = "string" | "number" | "date" | "bool" | '
        '"set" | "field-comparison";' in output
    )


def test_alias_referenced_twice_is_emitted_once() -> None:
    # AttrName backs both FieldMeta.name and RelationTarget.field; the dedup guard
    # must emit its `export type` exactly once (a second would be a tsc error).
    output = render_filter_metadata_module([FieldMeta])
    assert output.count("export type AttrName = ") == 1


def test_shared_nested_interface_emitted_once_across_roots() -> None:
    output = render_filter_metadata_module([RootA, RootB])
    assert output.count("export interface Shared {") == 1


def test_self_referential_typeddict_terminates_and_emits_once() -> None:
    # The reserve-slot recursion guard must break the cycle rather than recurse
    # forever; Tree is emitted once and its field references itself as Tree[].
    output = render_filter_metadata_module([Tree])
    assert output.count("export interface Tree {") == 1
    assert "children: Tree[];" in output


def test_str_alias_becomes_named_string_type() -> None:
    output = render_filter_metadata_module([FieldMeta])
    assert "export type ModifierToken = string;" in output
    assert "modifiers: ModifierToken[];" in output


def test_header_and_primitive_mapping() -> None:
    output = render_filter_metadata_module([ComparableColumn])
    assert output.startswith("// GENERATED by `manage.py gen_element_types`")
    # value is typed ComparisonOperand (a transparent str alias) — codegen emits
    # the alias name so the TS interface is self-documenting, not "string" bare.
    assert "value: ComparisonOperand;" in output


def test_inline_literal_field_maps_to_union() -> None:
    # A Literal used directly (not via a named alias) inlines as a quoted union.
    class Widget(TypedDict):
        kind: Literal["a", "b"]

    output = render_filter_metadata_module([Widget])
    assert 'kind: "a" | "b";' in output


def test_unsupported_type_raises() -> None:
    class Bad(TypedDict):
        value: complex  # not in the primitive map, not a supported construct

    with pytest.raises(TypeError, match="unsupported type"):
        render_filter_metadata_module([Bad])


def test_non_typeddict_root_raises() -> None:
    class NotATypedDict:
        pass

    with pytest.raises(TypeError, match="not a TypedDict"):
        render_filter_metadata_module([NotATypedDict])


# ── Constants (issue #284) ───────────────────────────────────────────────────


def _space_constants() -> list[TsConstant]:
    """The real constants gen_element_types emits, built the same way."""
    return [
        TsConstant(
            "SPACE_GROUPS",
            get_type_hints(common.criteria)["SPACE_GROUPS"],
            SPACE_GROUPS,
        ),
        TsConstant(
            "SPACE_ORDERED_MODIFIERS",
            list[ModifierToken],
            Modifier.for_ordered_field_comparisons(),
        ),
    ]


def test_space_groups_constant_is_a_typed_record() -> None:
    output = render_filter_metadata_module([], constants=_space_constants())
    assert (
        "export const SPACE_GROUPS: Record<ComparisonSpace, ComparisonGroup[]> ="
        in output
    )


def test_constant_annotations_pull_in_their_aliases_without_roots() -> None:
    # ComparisonSpace/ComparisonGroup are referenced only by the constant's type;
    # they must still be emitted or the const's annotation is a tsc error.
    output = render_filter_metadata_module([], constants=_space_constants())
    assert 'export type ComparisonSpace = "date" | "year";' in output
    assert "export type ComparisonGroup =" in output


def test_frozenset_values_serialize_as_sorted_arrays() -> None:
    # frozenset iteration order varies with hash randomization; the emitter must
    # sort so regeneration is byte-stable across runs.
    output = render_filter_metadata_module([], constants=_space_constants())
    assert '"date",\n    "datetime"\n  ]' in output
    assert '"date",\n    "datetime",\n    "number"\n  ]' in output


def test_enum_members_flatten_to_their_values_in_order() -> None:
    # List order is meaningful (dropdown order) and must survive; enum members
    # must serialize as their string values, not "Modifier.EQUALS" reprs.
    output = render_filter_metadata_module([], constants=_space_constants())
    expected_values = json.dumps(
        [modifier.value for modifier in Modifier.for_ordered_field_comparisons()],
        indent=2,
    )
    assert (
        f"export const SPACE_ORDERED_MODIFIERS: ModifierToken[] = {expected_values};"
        in output
    )


def test_unsupported_constant_type_raises_naming_the_constant() -> None:
    # The per-constant wrapper must name which constant failed — with several
    # registered, a bare "unsupported type" points nowhere.
    with pytest.raises(TypeError, match="constant 'BAD'.*unsupported type"):
        render_filter_metadata_module(
            [], constants=[TsConstant("BAD", complex, 1 + 2j)]
        )


def test_mixed_type_set_serializes_without_raising_and_deterministically() -> None:
    # sorted(key=repr) must be total: a heterogeneous set may not support `<`
    # between members, and its order must still be stable across runs. (The
    # declared TS type is a lie here; only the value path is under test.)
    constant = TsConstant("MIXED", frozenset[str], frozenset({1, "a", "b"}))
    first = render_filter_metadata_module([], constants=[constant])
    second = render_filter_metadata_module([], constants=[constant])
    assert first == second
    assert "export const MIXED" in first


def test_non_string_dict_key_raises() -> None:
    with pytest.raises(TypeError, match="non-string dict key"):
        render_filter_metadata_module(
            [], constants=[TsConstant("BAD", dict[int, str], {1: "a"})]
        )


def test_colliding_dict_keys_raise() -> None:
    # Two distinct dict keys flattening to the same JSON string (a plain-Enum
    # member and its value are unequal keys, unlike str-mixin enums) must not
    # silently collapse last-wins.
    class Shade(Enum):
        DARK = "x"

    with pytest.raises(TypeError, match="dict keys collide"):
        render_filter_metadata_module(
            [],
            constants=[TsConstant("BAD", dict[str, str], {Shade.DARK: "a", "x": "b"})],
        )


def test_nan_value_raises_instead_of_emitting_non_json() -> None:
    # NaN/Infinity are valid TS `number` expressions but not JSON; without
    # allow_nan=False they'd slip through every guard.
    with pytest.raises(TypeError, match="constant 'BAD'"):
        render_filter_metadata_module(
            [], constants=[TsConstant("BAD", float, float("nan"))]
        )


def test_choice_vocabulary_emits_const_union_and_labels() -> None:
    output = render_choice_vocabulary(
        type_name="ThemePreference",
        values_name="THEME_PREFERENCES",
        labels_name="THEME_LABELS",
        choices=(("system", "System"), ("light", "Light"), ("dark", "Dark")),
    )

    assert output.startswith("// GENERATED by `manage.py gen_element_types`")
    assert (
        'export const THEME_PREFERENCES = ["system", "light", "dark"] as const;'
        in output
    )
    assert "export type ThemePreference = typeof THEME_PREFERENCES[number];" in output
    assert 'system: "System"' in output
    assert 'light: "Light"' in output
    assert 'dark: "Dark"' in output
    assert "satisfies Record<ThemePreference, string>;" in output


@pytest.mark.parametrize(
    ("choices", "message"),
    [
        ((("", "Empty"),), "non-empty"),
        ((("dark", "Dark"), ("dark", "Again")), "duplicate"),
    ],
)
def test_choice_vocabulary_rejects_invalid_values(choices, message) -> None:
    with pytest.raises(ValueError, match=message):
        render_choice_vocabulary(
            type_name="ThemePreference",
            values_name="THEME_PREFERENCES",
            labels_name="THEME_LABELS",
            choices=choices,
        )


def test_choice_vocabulary_escapes_labels() -> None:
    output = render_choice_vocabulary(
        type_name="Preference",
        values_name="PREFERENCES",
        labels_name="LABELS",
        choices=(("quoted", 'Say "hello"'),),
    )

    assert 'quoted: "Say \\"hello\\""' in output
