"""Unit tests for the structural TypedDict->TS emitter (issue #247)."""

from typing import Literal, TypedDict

from common.components.ts_codegen import render_filter_metadata_module
from common.criteria import ComparableColumn, FieldMeta


def test_emits_field_meta_and_comparable_column_interfaces() -> None:
    output = render_filter_metadata_module([FieldMeta, ComparableColumn])
    assert "export interface FieldMeta {" in output
    assert "export interface ComparableColumn {" in output


def test_includes_previously_drifted_fields() -> None:
    # The hand-mirror had dropped these; codegen restores them (the whole point).
    output = render_filter_metadata_module([FieldMeta])
    assert "search_url: string;" in output
    assert "is_m2m: boolean;" in output


def test_nested_typeddicts_are_emitted_and_referenced_as_arrays() -> None:
    output = render_filter_metadata_module([FieldMeta])
    assert "export interface ChoiceMeta {" in output
    assert "export interface RelationTarget {" in output
    assert "choices: ChoiceMeta[];" in output
    assert "relations: RelationTarget[];" in output


def test_literal_alias_becomes_a_string_union() -> None:
    output = render_filter_metadata_module([ComparableColumn])
    assert (
        'export type ComparisonGroup = "date" | "datetime" | "duration" | '
        '"number" | "string" | "bool";' in output
    )


def test_str_alias_becomes_named_string_type() -> None:
    output = render_filter_metadata_module([FieldMeta])
    assert "export type ModifierToken = string;" in output
    assert "modifiers: ModifierToken[];" in output


def test_header_and_primitive_mapping() -> None:
    output = render_filter_metadata_module([ComparableColumn])
    assert output.startswith("// GENERATED by `manage.py gen_element_types`")
    assert "value: string;" in output  # str -> string


def test_inline_literal_field_maps_to_union() -> None:
    # A Literal used directly (not via a named alias) inlines as a quoted union.
    class Widget(TypedDict):
        kind: Literal["a", "b"]

    output = render_filter_metadata_module([Widget])
    assert 'kind: "a" | "b";' in output


def test_unsupported_type_raises() -> None:
    class Bad(TypedDict):
        value: complex  # not in the primitive map, not a supported construct

    try:
        render_filter_metadata_module([Bad])
    except TypeError as error:
        assert "unsupported type" in str(error)
    else:  # pragma: no cover - the call must raise
        raise AssertionError("expected TypeError for an unsupported field type")
