"""Server-side HTML component library.

Split into core / primitives / domain / filters submodules; this package
re-exports the public API so ``from common.components import X`` keeps working.
"""

from common.components.core import (
    Component,
    HTMLAttribute,
    HTMLTag,
    _render_element,
    randomid,
)
from common.components.date_range_picker import (
    DateRangeCalendar,
    DateRangeField,
    DateRangePicker,
)
from common.components.domain import (
    GameLink,
    GameStatus,
    GameStatusSelector,
    LinkedPurchase,
    NameWithIcon,
    PriceConverted,
    PurchasePrice,
    SessionDeviceSelector,
    _resolve_name_with_icon,
)
from common.components.filters import (
    DeviceFilterBar,
    FilterBar,
    PlatformFilterBar,
    PlayEventFilterBar,
    PurchaseFilterBar,
    SessionFilterBar,
    StringFilter,
)
from common.components.primitives import (
    H1,
    A,
    AddForm,
    Button,
    ButtonGroup,
    Checkbox,
    CsrfInput,
    Div,
    ExternalScript,
    Icon,
    Input,
    Label,
    Li,
    Modal,
    ModuleScript,
    Pill,
    Popover,
    PopoverTruncated,
    Radio,
    SearchField,
    SimpleTable,
    Span,
    TableHeader,
    TableRow,
    TableTd,
    Td,
    Template,
    Tr,
    Ul,
    YearPicker,
    paginated_table_content,
)
from common.components.search_select import (
    DEFAULT_PREFETCH,
    FilterSelect,
    LabeledOption,
    SearchSelect,
    SearchSelectOption,
    searchselect_selected,
)
from common.utils import truncate

__all__ = [
    "truncate",
    "Component",
    "HTMLAttribute",
    "HTMLTag",
    "_render_element",
    "randomid",
    "A",
    "AddForm",
    "Button",
    "ButtonGroup",
    "Checkbox",
    "CsrfInput",
    "Div",
    "ExternalScript",
    "H1",
    "Icon",
    "Input",
    "Modal",
    "ModuleScript",
    "Pill",
    "Popover",
    "PopoverTruncated",
    "Radio",
    "SearchField",
    "DEFAULT_PREFETCH",
    "FilterSelect",
    "LabeledOption",
    "SearchSelect",
    "SearchSelectOption",
    "searchselect_selected",
    "SimpleTable",
    "Span",
    "Label",
    "TableHeader",
    "TableRow",
    "TableTd",
    "Template",
    "YearPicker",
    "paginated_table_content",
    "GameLink",
    "GameStatus",
    "GameStatusSelector",
    "LinkedPurchase",
    "NameWithIcon",
    "PriceConverted",
    "PurchasePrice",
    "SessionDeviceSelector",
    "_resolve_name_with_icon",
    "DateRangeCalendar",
    "DateRangeField",
    "DateRangePicker",
    "FilterBar",
    "PurchaseFilterBar",
    "SessionFilterBar",
    "DeviceFilterBar",
    "PlatformFilterBar",
    "PlayEventFilterBar",
    "StringFilter",
]
