"""Custom-element builder, registry, and TypeScript codegen.

A custom element is a light-DOM Web Component: the Python builder emits a
semantic tag whose typed props become kebab-case attributes and whose behavior
lives in a compiled TS module (loaded via Media). One ``TypedDict`` per element
is the single source of truth for the server<->client contract;
``gen_element_types`` turns each registered spec into a TS interface + attribute
reader so drift fails ``tsc``.
"""

import warnings
from dataclasses import dataclass
from typing import TypedDict, get_type_hints

from common.components.core import Child, Element, Fragment, Node
from common.components.primitives import (
    A,
    Button,
    Div,
    Icon,
    Input,
    Label,
    Li,
    Span,
    StyledButton,
    Template,
    Ul,
    custom_element_builder,
)


@dataclass(frozen=True)
class ElementSpec:
    tag: str  # e.g. "drop-down"
    ts_name: str  # e.g. "Dropdown"
    props: type  # a TypedDict subclass


ELEMENT_REGISTRY: list[ElementSpec] = []


def register_element(tag: str, ts_name: str, props: type) -> None:
    """Register an element so codegen can emit its TS contract."""
    ELEMENT_REGISTRY.append(ElementSpec(tag, ts_name, props))


def _kebab(name: str) -> str:
    return name.replace("_", "-")


# ── Codegen ──────────────────────────────────────────────────────────────────

_TYPE_MAP = {int: "number", float: "number", str: "string", bool: "boolean"}


def _camel(name: str) -> str:
    head, *tail = name.split("_")
    return head + "".join(part.title() for part in tail)


def _reader_expr(name: str, python_type: type) -> str:
    attr = _kebab(name)
    if python_type in (int, float):
        return f'Number(el.getAttribute("{attr}"))'
    if python_type is bool:
        return f'el.getAttribute("{attr}") === "true"'
    return f'el.getAttribute("{attr}") ?? ""'


def _ts_for_spec(spec: ElementSpec) -> str:
    hints = get_type_hints(spec.props)
    interface_lines = "\n".join(
        f"  {_camel(name)}: {_TYPE_MAP[python_type]};"
        for name, python_type in hints.items()
    )
    reader_lines = "\n".join(
        f"    {_camel(name)}: {_reader_expr(name, python_type)},"
        for name, python_type in hints.items()
    )
    return (
        f"export interface {spec.ts_name}Props {{\n{interface_lines}\n}}\n\n"
        f"export function read{spec.ts_name}Props(el: HTMLElement): "
        f"{spec.ts_name}Props {{\n  return {{\n{reader_lines}\n  }};\n}}"
    )


def render_props_module() -> str:
    """The full ``ts/generated/props.ts`` content for every registered element."""
    header = "// GENERATED by `manage.py gen_element_types` — do not edit.\n"
    blocks = [_ts_for_spec(spec) for spec in ELEMENT_REGISTRY]
    return header + "\n" + "\n\n".join(blocks) + "\n"


# ── Element prop schemas (registered at import time) ─────────────────────────


class PlayEventRowProps(TypedDict):
    game_id: int
    csrf: str
    api_create_url: str


register_element("play-event-row", "PlayEventRow", PlayEventRowProps)


class SessionTimestampButtonsProps(TypedDict):
    pass


register_element(
    "session-timestamp-buttons", "SessionTimestampButtons", SessionTimestampButtonsProps
)


# ── Named tag builders (consistent htpy-style with Div/Span) ─────────────────
# Underscore-prefixed: used internally by domain wrappers.
# Public ones (no domain wrapper): exported directly.

_PlayEventRow = custom_element_builder("play-event-row")
SessionTimestampButtons = custom_element_builder("session-timestamp-buttons")


class SelectionFieldsProps(TypedDict):
    source: str  # data-name of the source SearchSelect to mirror
    name_prefix: str  # each rendered input is named f"{name_prefix}{item_id}"
    field_type: str  # input type, e.g. "number"
    min_items: int  # render nothing until at least this many items are selected
    active: bool  # when false, render nothing (but preserve typed values)


register_element("selection-fields", "SelectionFields", SelectionFieldsProps)

_SelectionFields = custom_element_builder("selection-fields")


class DateRangePickerProps(TypedDict):
    pass


register_element("date-range-picker", "DateRangePicker", DateRangePickerProps)
_DateRangePicker = custom_element_builder("date-range-picker")


class SearchSelectProps(TypedDict):
    name: str
    search_url: str
    multi: bool
    filter_mode: bool
    free_text: bool
    always_visible: bool
    prefetch: int
    sync_url: bool


register_element("search-select", "SearchSelect", SearchSelectProps)
_SearchSelect = custom_element_builder("search-select")


class FilterBarProps(TypedDict):
    preset_list_url: str
    preset_save_url: str


register_element("filter-bar", "FilterBar", FilterBarProps)
_FilterBarElement = custom_element_builder("filter-bar")


class YearPickerProps(TypedDict):
    selected_year: str  # "" for the all-time/empty state
    available_years: str  # csv, e.g. "2019,2020"
    url_template: str  # contains the literal __year__ placeholder


# The <year-picker> builder lives in primitives.py (next to YearPicker, which
# uses it) because custom_elements imports from primitives — registering here
# would be a circular import. Registration is codegen-only, so it belongs here.
register_element("year-picker", "YearPicker", YearPickerProps)


def SelectionFields(
    *,
    source: str,
    name_prefix: str,
    field_type: str = "text",
    min_items: int = 1,
    active: bool = False,
    input_attributes: list[tuple[str, str]] | None = None,
) -> Node:
    """Render one synced form field per selected item of a source SearchSelect.

    General-purpose: it mirrors the SearchSelect named ``source`` and emits an
    input named ``f"{name_prefix}{item_id}"`` per selected item. Behavior lives
    in ``ts/elements/selection-fields.ts``; this is just the server-rendered
    light DOM (an empty rows container + a row ``<template>``). Inputs inherit
    the global ``#add-form`` styling, so the markup stays minimal.
    """
    row_template = Template(attributes=[("data-selection-fields-row", "")])[
        Div(attributes=[("data-selection-fields-row-item", "")])[
            Label(attributes=[("data-selection-fields-label", "")]),
            Input(type=field_type, attributes=list(input_attributes or [])),
        ]
    ]
    return _SelectionFields(
        source=source,
        name_prefix=name_prefix,
        field_type=field_type,
        min_items=min_items,
        active="true" if active else "false",
    )[
        Div(attributes=[("data-selection-fields-rows", "")]),
        row_template,
    ]


# ── Dropdown ─────────────────────────────────────────────────────────────────
# A generic, accessible dropdown element. Behavior lives in
# ts/elements/drop-down.ts (open/close, keyboard nav, behavior dispatch); the
# shared positioning/keyboard core is ts/elements/menu-behavior.ts. Opening is
# instant (no animation, by design).


class DropdownProps(TypedDict):
    placement: str  # "bottom-start" | "bottom-center" | "bottom-end" | "right-start"
    submenu: bool  # enables hover-open + arrow-key submenu behavior
    behavior: str  # registered client behavior: "menu" | "select" | …


register_element("drop-down", "Dropdown", DropdownProps)
_Dropdown = custom_element_builder("drop-down")


# Unified dropdown styling — ONE look for every dropdown: white in light mode,
# frosted (translucent + backdrop blur) in dark mode. The only option is
# `outline`: a border on the toggle AND panel for button-like (non-menu)
# dropdowns (the value selectors, the played-row split button); menu-like
# dropdowns (the navbar) stay borderless (shadow only). Behavior is shared via
# attachMenu; these constants are the single source of truth for the look and
# are reused by the selectors (domain.py) and the played row (game.py).

# Outlined (button-like) toggle: bordered button, no base rounding — Dropdown
# adds rounded-lg / rounded-e-lg by shape; standalone consumers add their own.
DROPDOWN_TOGGLE_OUTLINE = (
    "px-4 py-2 text-sm font-medium bg-white border border-gray-200 "
    "hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:text-white "
    "dark:hover:bg-gray-700 hover:cursor-pointer"
)

# Plain (menu-like) toggle: the borderless navbar nav-link look.
_DROPDOWN_TOGGLE_PLAIN = (
    "flex items-center justify-between w-full py-2 px-3 text-gray-900 rounded-sm "
    "hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 "
    "md:p-0 md:w-auto dark:text-white md:dark:hover:text-blue-500 "
    "dark:focus:text-white dark:border-gray-700 dark:hover:bg-gray-700 "
    "md:dark:hover:bg-transparent hover:cursor-pointer"
)

# Panel: white (light) / frosted (dark). Keeps the #46 overflow-hidden. Outline
# adds a border; otherwise a shadow.
# NB: the dark-mode backdrop blur lives on a `::before` layer, NOT the panel.
# A non-`none` backdrop-filter makes its element the containing block for `fixed`
# descendants — so blurring the panel itself would (a) re-anchor the `fixed`
# submenu flyouts relative to the panel and (b) make them count toward the
# panel's overflow, growing a transient scrollbar that mis-anchored low submenus.
# Putting the filter on a childless `::before` keeps the frosted look while
# leaving the panel filter-free, so submenus still resolve against the viewport.
_DROPDOWN_PANEL_BASE = (
    "absolute z-20 w-44 overflow-hidden rounded-lg p-2 "
    "bg-white dark:bg-gray-800/40 text-sm "
    "before:content-[''] before:absolute before:inset-0 before:-z-10 "
    "before:rounded-[inherit] dark:before:backdrop-blur-xl"
)
DROPDOWN_PANEL_OUTLINE_CLASS = (
    f"{_DROPDOWN_PANEL_BASE} border border-gray-200 dark:border-gray-700"
)
_DROPDOWN_PANEL_PLAIN_CLASS = (
    f"{_DROPDOWN_PANEL_BASE} shadow-sm border border-gray-200 dark:border-gray-700"
)

# One item look: dark text on white (light), light text on frosted (dark).
DROPDOWN_ITEM_CLASS = (
    "block w-full text-left px-4 py-2 cursor-pointer no-underline rounded-base "
    "hover:bg-gray-100 dark:hover:bg-gray-700 text-body hover:text-heading "
    "focus:bg-gray-100 dark:focus:bg-gray-700 dark:focus:text-white "
    "focus:outline-hidden aria-disabled:opacity-50 aria-disabled:cursor-not-allowed"
)


# The single panel look for menu-style dropdowns (shadow + border). The old
# OUTLINE/PLAIN split collapsed into one; DROPDOWN_PANEL_OUTLINE_CLASS survives
# only for the value selectors (domain.py), which keep their own path until PR 2.
_DROPDOWN_MENU_PANEL_CLASS = _DROPDOWN_PANEL_PLAIN_CLASS


# ── Trigger/target contract stamping ─────────────────────────────────────────
# `Dropdown` is a generic "attach a popup to a trigger" primitive: the caller
# owns each element's *look*, the core stamps the behavioral/ARIA *contract* onto
# them. The contract is the single source of truth for what the TS + ARIA need;
# a caller setting a reserved key is a misuse, surfaced as a warning (the contract
# value still wins). Menu *semantics* (role/aria-haspopup) are NOT stamped here —
# they live in the menu preset/wrappers, so non-menu targets stay clean.


class DropdownContractWarning(UserWarning):
    """A trigger/target supplied a reserved contract attribute; the core's value
    wins. Its own category so tests can ``pytest.warns(DropdownContractWarning)``
    precisely and callers can filter/escalate it independently."""


def _stamp(element: Element, contract: list[tuple[str, str]], id: str) -> Element:
    """Return a clone of `element` carrying `contract`, preserving its other attrs
    (class, hx-*, …) and media. Warns on each reserved-key collision."""
    reserved = {key for key, _ in contract}
    for key, _ in element.attributes:
        if key in reserved:
            warnings.warn(
                f"dropdown {id!r}: supplied element sets reserved attr {key!r}; "
                "the contract value wins",
                DropdownContractWarning,
                stacklevel=3,
            )
    kept = [(key, value) for key, value in element.attributes if key not in reserved]
    clone = Element(element.tag_name, kept + contract, element.children)
    clone.media = element.media
    return clone


def _stamp_trigger_contract(trigger: Element, id: str) -> Element:
    """The toggle's behavioral contract: the [data-toggle] hook the TS finds plus
    the ARIA wiring to its panel. `type` is button-ness, set by trigger builders."""
    return _stamp(
        trigger,
        [
            ("data-toggle", ""),
            ("id", f"{id}Link"),
            ("aria-controls", id),
            ("aria-expanded", "false"),
        ],
        id,
    )


def _stamp_target_contract(target: Element, id: str) -> Element:
    """The panel's behavioral contract: the [data-menu] hook + initial hidden
    state + id. `aria-labelledby` auto-wires to the toggle UNLESS the target
    carries an explicit `aria-label` (which would otherwise be overridden by it —
    the icon-only-trigger case)."""
    contract = [("data-menu", ""), ("id", id), ("hidden", "")]
    if not any(key == "aria-label" for key, _ in target.attributes):
        contract.append(("aria-labelledby", f"{id}Link"))
    return _stamp(target, contract, id)


def _as_menu_trigger(trigger: Element) -> Element:
    """Add the menu semantic (`aria-haspopup="menu"`) to a trigger. The single
    home for "this trigger opens a menu", shared by the menu wrappers."""
    if any(key == "aria-haspopup" for key, _ in trigger.attributes):
        return trigger
    return _stamp(trigger, [("aria-haspopup", "menu")], "menu")


def DropdownLinkItem(url: str, label: str, *, current: bool = False) -> Node:
    """A navigation menu item (an ``<a>`` link)."""
    attributes: list[tuple[str, str]] = [
        ("href", url),
        ("role", "menuitem"),
        ("tabindex", "-1"),
        ("class", DROPDOWN_ITEM_CLASS),
    ]
    if current:
        attributes.append(("aria-current", "page"))
    return Li()[A(attributes)[label]]


def DropdownActionItem(
    label: str,
    *,
    attributes: list[tuple[str, str]] | None = None,
    disabled: bool = False,
) -> Node:
    """An action menu item (a ``<button>``). ``attributes`` carries the caller's
    data hooks (e.g. ``[("data-add-play", "")]``) wiring its own JS behavior."""
    item_attributes: list[tuple[str, str]] = [
        ("type", "button"),
        ("role", "menuitem"),
        ("tabindex", "-1"),
        ("class", DROPDOWN_ITEM_CLASS),
    ]
    if disabled:
        item_attributes += [("disabled", ""), ("aria-disabled", "true")]
    item_attributes += list(attributes or [])
    return Li()[Element("button", item_attributes, [label])]


def DropdownCheckItem(
    label: str,
    *,
    checked: bool,
    attributes: list[tuple[str, str]] | None = None,
) -> Node:
    """A multi-select menu item (``role="menuitemcheckbox"``). Toggling it keeps
    the menu open; the checked state is reflected via ``aria-checked``."""
    item_attributes: list[tuple[str, str]] = [
        ("type", "button"),
        ("role", "menuitemcheckbox"),
        ("aria-checked", "true" if checked else "false"),
        ("tabindex", "-1"),
        ("class", DROPDOWN_ITEM_CLASS + " group flex items-center gap-2"),
    ]
    item_attributes += list(attributes or [])
    return Li()[
        Element(
            "button",
            item_attributes,
            [
                Span(class_="opacity-0 group-aria-[checked=true]:opacity-100")["✓"],
                Span()[label],
            ],
        )
    ]


def DropdownDivider() -> Node:
    """A separator between groups of items."""
    return Li(role="separator", class_="my-1 h-px bg-gray-100 dark:bg-gray-600")


def _assemble(
    trigger: Element,
    target: Element,
    *,
    id: str,
    placement: str,
    submenu: bool,
    wrapper_class: str,
    behavior: str = "menu",
    config: dict[str, str] | None = None,
) -> Node:
    """Stamp both contracts and wire the <drop-down> element. The single assembly
    point shared by the public Dropdown and DropdownSubmenu. `config` becomes
    extra data-* attributes the chosen behavior reads (e.g. select's PATCH url)."""
    # config keys use underscores (e.g. data_patch_url); convert to data-* names
    # and pass as an explicit attribute list so the dict never spreads onto the
    # builder's typed attributes/children params.
    config_attributes = [
        (key.replace("_", "-"), value) for key, value in (config or {}).items()
    ]
    return _Dropdown(
        config_attributes,
        class_=wrapper_class,
        placement=placement,
        submenu="true" if submenu else "false",
        behavior=behavior,
    )[
        Fragment(
            _stamp_trigger_contract(trigger, id),
            _stamp_target_contract(target, id),
        )
    ]


def Dropdown(
    *,
    trigger_element: Element,
    target_element: Element,
    id: str,
    placement: str = "bottom-start",
    behavior: str = "menu",
    config: dict[str, str] | None = None,
) -> Node:
    """Attach a popup (target_element) to a trigger_element. Generic primitive:
    stamps the JS/ARIA contract, wires the <drop-down> element, and tags it with a
    client `behavior` (menu by default). Menu semantics live in the menu preset/
    wrappers, not here."""
    return _assemble(
        trigger_element,
        target_element,
        id=id,
        placement=placement,
        submenu=False,
        # inline-flex (not inline-block) so the trigger stretches to fill the
        # wrapper — needed when the wrapper is itself a stretched flex child (the
        # SplitButtonDropdown group). Visually identical for a standalone dropdown.
        # FRICTION POINT: imposes flex on every wrapper; `display: contents` is the
        # cleaner-but-broader fallback if it ever fights a layout.
        wrapper_class="relative inline-flex",
        behavior=behavior,
        config=config,
    )


def DropdownMenuPanel(*, items: list[Node], aria_label: str = "") -> Element:
    """The canonical menu target: a ``role="menu"`` panel wrapping ``items`` in a
    list. Pass ``aria_label`` to name the menu when its trigger has no text (an
    icon-only trigger); otherwise the core auto-labels it from the trigger."""
    attributes: list[tuple[str, str]] = [
        ("role", "menu"),
        ("class", _DROPDOWN_MENU_PANEL_CLASS),
    ]
    if aria_label:
        attributes.append(("aria-label", aria_label))
    return Element("div", attributes, [Ul()[*items]])


def MenuDropdown(
    *,
    label: Child,
    items: list[Node],
    id: str,
    placement: str = "bottom-start",
    aria_label: str = "",
) -> Node:
    """A borderless, navbar-style menu dropdown (the old non-outline look)."""
    trigger = _as_menu_trigger(
        Button(attributes=[("type", "button"), ("class", _DROPDOWN_TOGGLE_PLAIN)])[
            Span(class_="flex items-center gap-1")[label, Icon("arrowdown")]
        ]
    )
    return Dropdown(
        trigger_element=trigger,
        target_element=DropdownMenuPanel(items=items, aria_label=aria_label),
        id=id,
        placement=placement,
    )


def ButtonDropdown(
    *,
    label: Child,
    items: list[Node],
    id: str,
    color: str = "gray",
    size: str = "base",
    placement: str = "bottom-start",
    aria_label: str = "",
) -> Node:
    """A button-styled menu dropdown; the trigger is a ``StyledButton``."""
    trigger = _as_menu_trigger(
        StyledButton(color=color, size=size, icon=True)[label, Icon("arrowdown")]
    )
    return Dropdown(
        trigger_element=trigger,
        target_element=DropdownMenuPanel(items=items, aria_label=aria_label),
        id=id,
        placement=placement,
    )


def SplitButtonDropdown(
    *,
    primary: Node,
    items: list[Node],
    id: str,
    placement: str = "bottom-start",
    aria_label: str = "",
) -> Node:
    """A split button: a leading ``primary`` action grouped with an outlined caret
    that opens the menu. The Dropdown attaches to the caret only — ``primary`` is
    a plain sibling, so the core never needs to know it exists."""
    caret = _as_menu_trigger(
        Button(
            attributes=[
                ("type", "button"),
                ("class", DROPDOWN_TOGGLE_OUTLINE + " rounded-e-lg"),
            ]
        )[Icon("arrowdown")]
    )
    dropdown = Dropdown(
        trigger_element=caret,
        target_element=DropdownMenuPanel(items=items, aria_label=aria_label),
        id=id,
        placement=placement,
    )
    return Div(class_="inline-flex items-stretch rounded-md shadow-2xs")[
        primary, dropdown
    ]


def DropdownSubmenu(
    label: Child, items: list[Node], *, id: str, placement: str = "right-start"
) -> Node:
    """A menu item that opens a nested submenu (a flyout, right by default).

    Renders an ``<li>`` whose trigger is itself a ``role="menuitem"`` (so the
    parent menu's keyboard nav includes it) carrying ``aria-haspopup`` so the
    parent stays open when it activates. ``submenu=True`` is intrinsic (hover-open
    + ArrowRight/Left); only ``placement`` is tunable."""
    trigger = _as_menu_trigger(
        Button(
            attributes=[
                ("type", "button"),
                ("role", "menuitem"),
                ("tabindex", "-1"),
                (
                    "class",
                    DROPDOWN_ITEM_CLASS + " flex items-center justify-between gap-2",
                ),
            ]
        )[Span()[label], Icon("arrowright")]
    )
    return Li()[
        _assemble(
            trigger,
            DropdownMenuPanel(items=items),
            id=id,
            placement=placement,
            submenu=True,
            wrapper_class="relative",
        )
    ]


type SelectOption = tuple[
    str, Child, bool
]  # (value, label, is_selected); e.g. ("f", "Finished", True)


def ListboxPanel(*, options: list[SelectOption], aria_label: str = "") -> Element:
    """A single-select listbox target: role="listbox" over role="option" items
    carrying [data-option][data-value][aria-selected]. The select behavior wires
    clicks; the core stamps data-menu/hidden/id when it's used as target_element."""
    attributes: list[tuple[str, str]] = [
        ("role", "listbox"),
        ("class", DROPDOWN_PANEL_OUTLINE_CLASS),
    ]
    if aria_label:
        attributes.append(("aria-label", aria_label))
    option_nodes = [
        Li()[
            Element(
                "button",
                [
                    ("type", "button"),
                    ("role", "option"),
                    ("data-option", ""),
                    ("data-value", value),
                    ("aria-selected", "true" if selected else "false"),
                    ("tabindex", "-1"),
                    ("class", DROPDOWN_ITEM_CLASS),
                ],
                [label],
            )
        ]
        for value, label, selected in options
    ]
    return Element("div", attributes, [Ul()[*option_nodes]])


def SelectDropdown(
    *,
    current_label: Child,
    options: list[SelectOption],
    id: str,
    patch_url: str,
    body_key: str,
    event: str,
    csrf: str,
    numeric: bool = False,
    placement: str = "bottom-start",
) -> Node:
    """A value-selector dropdown: a current-value trigger + a listbox whose picks
    PATCH the server (via the client `select` behavior). The per-entity specifics
    (endpoint, body key, numeric) are the caller's; this owns the shared shape."""
    trigger = Button(
        attributes=[
            ("type", "button"),
            ("class", DROPDOWN_TOGGLE_OUTLINE + " rounded-lg"),
            ("aria-haspopup", "listbox"),
        ]
    )[
        Span(class_="flex flex-row gap-4 justify-between items-center")[
            Span(data_label="")[current_label], Icon("arrowdown")
        ]
    ]
    config: dict[str, str] = {
        "data_patch_url": patch_url,
        "data_body_key": body_key,
        "data_event": event,
        "data_csrf": csrf,
    }
    if numeric:
        config["data_numeric"] = "true"
    return Dropdown(
        trigger_element=trigger,
        target_element=ListboxPanel(options=options),
        id=id,
        placement=placement,
        behavior="select",
        config=config,
    )
