"""Custom-element builder, registry, and TypeScript codegen.

A custom element is a light-DOM Web Component: the Python builder emits a
semantic tag whose typed props become kebab-case attributes and whose behavior
lives in a compiled TS module (loaded via Media). One ``TypedDict`` per element
is the single source of truth for the server<->client contract;
``gen_element_types`` turns each registered spec into a TS interface + attribute
reader so drift fails ``tsc``.
"""

from dataclasses import dataclass
from typing import TypedDict, get_type_hints

from common.components.core import Child, Element, Fragment, Node
from common.components.primitives import (
    A,
    Div,
    Icon,
    Input,
    Label,
    Li,
    Span,
    Template,
    Ul,
    custom_element_builder,
)


@dataclass(frozen=True)
class ElementSpec:
    tag: str  # e.g. "game-status-selector"
    ts_name: str  # e.g. "GameStatusSelector"
    props: type  # a TypedDict subclass


ELEMENT_REGISTRY: list[ElementSpec] = []


def register_element(tag: str, ts_name: str, props: type) -> None:
    """Register an element so codegen can emit its TS contract."""
    ELEMENT_REGISTRY.append(ElementSpec(tag, ts_name, props))


def _kebab(name: str) -> str:
    return name.replace("_", "-")


# ── Codegen ──────────────────────────────────────────────────────────────────

_TYPE_MAP = {int: "number", float: "number", str: "string", bool: "boolean"}


def _camel(name: str) -> str:
    head, *tail = name.split("_")
    return head + "".join(part.title() for part in tail)


def _reader_expr(name: str, python_type: type) -> str:
    attr = _kebab(name)
    if python_type in (int, float):
        return f'Number(el.getAttribute("{attr}"))'
    if python_type is bool:
        return f'el.getAttribute("{attr}") === "true"'
    return f'el.getAttribute("{attr}") ?? ""'


def _ts_for_spec(spec: ElementSpec) -> str:
    hints = get_type_hints(spec.props)
    interface_lines = "\n".join(
        f"  {_camel(name)}: {_TYPE_MAP[python_type]};"
        for name, python_type in hints.items()
    )
    reader_lines = "\n".join(
        f"    {_camel(name)}: {_reader_expr(name, python_type)},"
        for name, python_type in hints.items()
    )
    return (
        f"export interface {spec.ts_name}Props {{\n{interface_lines}\n}}\n\n"
        f"export function read{spec.ts_name}Props(el: HTMLElement): "
        f"{spec.ts_name}Props {{\n  return {{\n{reader_lines}\n  }};\n}}"
    )


def render_props_module() -> str:
    """The full ``ts/generated/props.ts`` content for every registered element."""
    header = "// GENERATED by `manage.py gen_element_types` — do not edit.\n"
    blocks = [_ts_for_spec(spec) for spec in ELEMENT_REGISTRY]
    return header + "\n" + "\n\n".join(blocks) + "\n"


# ── Element prop schemas (registered at import time) ─────────────────────────


class GameStatusSelectorProps(TypedDict):
    game_id: int
    status: str
    csrf: str


register_element("game-status-selector", "GameStatusSelector", GameStatusSelectorProps)


class SessionDeviceSelectorProps(TypedDict):
    session_id: int
    csrf: str


register_element(
    "session-device-selector", "SessionDeviceSelector", SessionDeviceSelectorProps
)


class PlayEventRowProps(TypedDict):
    game_id: int
    csrf: str
    api_create_url: str


register_element("play-event-row", "PlayEventRow", PlayEventRowProps)


class SessionTimestampButtonsProps(TypedDict):
    pass


register_element(
    "session-timestamp-buttons", "SessionTimestampButtons", SessionTimestampButtonsProps
)


# ── Named tag builders (consistent htpy-style with Div/Span) ─────────────────
# Underscore-prefixed: used internally by domain wrappers.
# Public ones (no domain wrapper): exported directly.

_GameStatusSelector = custom_element_builder("game-status-selector")
_SessionDeviceSelector = custom_element_builder("session-device-selector")
_PlayEventRow = custom_element_builder("play-event-row")
SessionTimestampButtons = custom_element_builder("session-timestamp-buttons")


class SelectionFieldsProps(TypedDict):
    source: str  # data-name of the source SearchSelect to mirror
    name_prefix: str  # each rendered input is named f"{name_prefix}{item_id}"
    field_type: str  # input type, e.g. "number"
    min_items: int  # render nothing until at least this many items are selected
    active: bool  # when false, render nothing (but preserve typed values)


register_element("selection-fields", "SelectionFields", SelectionFieldsProps)

_SelectionFields = custom_element_builder("selection-fields")


class DateRangePickerProps(TypedDict):
    pass


register_element("date-range-picker", "DateRangePicker", DateRangePickerProps)
_DateRangePicker = custom_element_builder("date-range-picker")


class SearchSelectProps(TypedDict):
    name: str
    search_url: str
    multi: bool
    filter_mode: bool
    free_text: bool
    always_visible: bool
    prefetch: int
    sync_url: bool


register_element("search-select", "SearchSelect", SearchSelectProps)
_SearchSelect = custom_element_builder("search-select")


class FilterBarProps(TypedDict):
    preset_list_url: str
    preset_save_url: str


register_element("filter-bar", "FilterBar", FilterBarProps)
_FilterBarElement = custom_element_builder("filter-bar")


class YearPickerProps(TypedDict):
    selected_year: str  # "" for the all-time/empty state
    available_years: str  # csv, e.g. "2019,2020"
    url_template: str  # contains the literal __year__ placeholder


# The <year-picker> builder lives in primitives.py (next to YearPicker, which
# uses it) because custom_elements imports from primitives — registering here
# would be a circular import. Registration is codegen-only, so it belongs here.
register_element("year-picker", "YearPicker", YearPickerProps)


def SelectionFields(
    *,
    source: str,
    name_prefix: str,
    field_type: str = "text",
    min_items: int = 1,
    active: bool = False,
    input_attributes: list[tuple[str, str]] | None = None,
) -> Node:
    """Render one synced form field per selected item of a source SearchSelect.

    General-purpose: it mirrors the SearchSelect named ``source`` and emits an
    input named ``f"{name_prefix}{item_id}"`` per selected item. Behavior lives
    in ``ts/elements/selection-fields.ts``; this is just the server-rendered
    light DOM (an empty rows container + a row ``<template>``). Inputs inherit
    the global ``#add-form`` styling, so the markup stays minimal.
    """
    row_template = Template(attributes=[("data-selection-fields-row", "")])[
        Div(attributes=[("data-selection-fields-row-item", "")])[
            Label(attributes=[("data-selection-fields-label", "")]),
            Input(type=field_type, attributes=list(input_attributes or [])),
        ]
    ]
    return _SelectionFields(
        source=source,
        name_prefix=name_prefix,
        field_type=field_type,
        min_items=min_items,
        active="true" if active else "false",
    )[
        Div(attributes=[("data-selection-fields-rows", "")]),
        row_template,
    ]


# ── Dropdown ─────────────────────────────────────────────────────────────────
# A generic, accessible dropdown menu. Behavior lives in
# ts/elements/dropdown-menu.ts (open/close, keyboard nav, submenus); the shared
# positioning/keyboard core is ts/elements/menu-behavior.ts. Opening is instant
# (no animation, by design).


class DropdownMenuProps(TypedDict):
    placement: str  # "bottom-start" | "bottom-end" | "right-start"
    submenu: bool  # enables hover-open + arrow-key submenu behavior


register_element("dropdown-menu", "DropdownMenu", DropdownMenuProps)
_DropdownMenu = custom_element_builder("dropdown-menu")


type DropdownLink = tuple[str, str]  # (url, label), e.g. ("/games/add/", "Game")


# Outline-less navbar look ("plain") vs. a bordered button ("button"). The
# variant only changes the toggle's classes, not its behavior.
_DROPDOWN_TOGGLE_VARIANTS: dict[str, str] = {
    "plain": (
        "flex items-center justify-between w-full py-2 px-3 text-gray-900 "
        "rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:border-0 "
        "md:hover:text-blue-700 md:p-0 md:w-auto dark:text-white "
        "md:dark:hover:text-blue-500 dark:focus:text-white dark:border-gray-700 "
        "dark:hover:bg-gray-700 md:dark:hover:bg-transparent hover:cursor-pointer"
    ),
    "button": (
        "inline-flex items-center gap-1 px-4 py-2 text-sm font-medium bg-white "
        "border border-gray-200 rounded-lg hover:bg-gray-100 dark:bg-gray-800 "
        "dark:border-gray-700 dark:hover:text-white dark:hover:bg-gray-700 "
        "hover:cursor-pointer"
    ),
}

_DROPDOWN_PANEL_CLASS = (
    "absolute z-20 w-44 overflow-hidden rounded-lg bg-white shadow-sm text-sm "
    "font-normal text-gray-700 dark:bg-gray-700 dark:text-gray-400"
)
_DROPDOWN_ITEM_CLASS = (
    "block w-full cursor-pointer px-4 py-2 text-left no-underline "
    "hover:bg-gray-100 focus:bg-gray-100 focus:outline-hidden "
    "dark:hover:bg-gray-600 dark:hover:text-white dark:focus:bg-gray-600 "
    "aria-disabled:opacity-50 aria-disabled:cursor-not-allowed"
)
_DROPDOWN_CHECK_ITEM_CLASS = _DROPDOWN_ITEM_CLASS + " group flex items-center gap-2"


def DropdownLinkItem(url: str, label: str, *, current: bool = False) -> Node:
    """A navigation menu item (an ``<a>`` link)."""
    attributes: list[tuple[str, str]] = [
        ("href", url),
        ("role", "menuitem"),
        ("tabindex", "-1"),
        ("class", _DROPDOWN_ITEM_CLASS),
    ]
    if current:
        attributes.append(("aria-current", "page"))
    return Li()[A(attributes)[label]]


def DropdownActionItem(
    label: str,
    *,
    attributes: list[tuple[str, str]] | None = None,
    disabled: bool = False,
) -> Node:
    """An action menu item (a ``<button>``). ``attributes`` carries the caller's
    data hooks (e.g. ``[("data-add-play", "")]``) wiring its own JS behavior."""
    item_attributes: list[tuple[str, str]] = [
        ("type", "button"),
        ("role", "menuitem"),
        ("tabindex", "-1"),
        ("class", _DROPDOWN_ITEM_CLASS),
    ]
    if disabled:
        item_attributes += [("disabled", ""), ("aria-disabled", "true")]
    item_attributes += list(attributes or [])
    return Li()[Element("button", item_attributes, [label])]


def DropdownCheckItem(
    label: str,
    *,
    checked: bool,
    attributes: list[tuple[str, str]] | None = None,
) -> Node:
    """A multi-select menu item (``role="menuitemcheckbox"``). Toggling it keeps
    the menu open; the checked state is reflected via ``aria-checked``."""
    item_attributes: list[tuple[str, str]] = [
        ("type", "button"),
        ("role", "menuitemcheckbox"),
        ("aria-checked", "true" if checked else "false"),
        ("tabindex", "-1"),
        ("class", _DROPDOWN_CHECK_ITEM_CLASS),
    ]
    item_attributes += list(attributes or [])
    return Li()[
        Element(
            "button",
            item_attributes,
            [
                Span(class_="opacity-0 group-aria-[checked=true]:opacity-100")["✓"],
                Span()[label],
            ],
        )
    ]


def DropdownDivider() -> Node:
    """A separator between groups of items."""
    return Li(role="separator", class_="my-1 h-px bg-gray-100 dark:bg-gray-600")


def Dropdown(
    *,
    label: Child,
    items: list[Node],
    id: str,
    variant: str = "plain",
    primary: Node | None = None,
    placement: str = "bottom-start",
    submenu: bool = False,
) -> Node:
    """A generic dropdown: a toggle button + a menu panel.

    ``items`` are nodes (use ``DropdownLinkItem`` / ``DropdownActionItem`` /
    ``DropdownCheckItem`` / ``DropdownDivider``), so a menu can mix links,
    actions, checkboxes and even nested ``Dropdown``s (submenus). ``primary``
    renders a split button (a leading action grouped with the caret toggle).
    """
    toggle_class = _DROPDOWN_TOGGLE_VARIANTS.get(
        variant, _DROPDOWN_TOGGLE_VARIANTS["plain"]
    )
    if primary is not None:
        toggle_class += " rounded-e-lg"
    toggle = Element(
        "button",
        [
            ("type", "button"),
            ("data-toggle", ""),
            ("id", f"{id}Link"),
            ("aria-haspopup", "menu"),
            ("aria-controls", id),
            ("aria-expanded", "false"),
            ("class", toggle_class),
        ],
        Span(class_="flex items-center gap-1")[label, Icon("arrowdown")],
    )
    panel = Div(
        data_menu="",
        role="menu",
        id=id,
        aria_labelledby=f"{id}Link",
        hidden=True,
        class_=_DROPDOWN_PANEL_CLASS,
    )[Ul()[*items]]
    if primary is not None:
        inner: Node = Div(
            class_="relative inline-flex items-stretch rounded-md shadow-2xs"
        )[primary, toggle, panel]
    else:
        inner = Fragment(toggle, panel)
    return _DropdownMenu(
        class_="relative inline-block",
        placement=placement,
        submenu="true" if submenu else "false",
    )[inner]
