"""Core-adjacent home for the generic element-builder factory and every named
plain HTML / SVG builder generated from it.

Split out from ``primitives.py`` (which still consumes and re-exports these
names) so :mod:`icons_generated` — generated by ``manage.py gen_icons`` from
SVG icon snippets — can import the SVG builders (``Svg``, ``Path``, …)
without creating a ``primitives.py -> icons_generated.py -> primitives.py``
import cycle: this module only imports from ``common.components.core``.
"""

from collections.abc import Mapping

from common.components.core import AttrsArg, Element, HTMLAttribute, Media

# Builder param names that must never arrive as htpy attribute kwargs. After the
# legacy ``attributes=`` / ``children=`` params are removed, a stray one would be
# silently swallowed by ``**kwargs`` and rendered as a bogus ``attributes="…"``
# HTML attribute — so we reject them with a pointer to the htpy form instead.
_RESERVED_ATTR_KWARGS = frozenset({"attributes", "children"})


def _attrs_from_kwargs(attrs: dict[str, object]) -> list[HTMLAttribute]:
    """Translate htpy-style attribute kwargs to (name, value) pairs.

    ``class_`` -> ``class`` (trailing underscore stripped); ``hx_get`` ->
    ``hx-get`` (inner underscores to hyphens); ``True`` -> ``name="name"``
    (boolean-attribute form); ``False`` / ``None`` -> omitted."""
    for reserved in _RESERVED_ATTR_KWARGS:
        if reserved in attrs:
            raise TypeError(
                f"{reserved!r} is not an htpy attribute kwarg. Pass dynamic "
                "attributes positionally — Builder(attrs) — and children via "
                "Builder(...)[...]."
            )
    result: list[HTMLAttribute] = []
    for key, value in attrs.items():
        if value is None or value is False:
            continue
        name = key.rstrip("_").replace("_", "-")
        result.append((name, name if value is True else value))  # type: ignore[arg-type]
    return result


def _coerce_attrs(attrs: AttrsArg | None) -> list[HTMLAttribute]:
    """Normalise a dynamic-attributes argument to ``list[HTMLAttribute]``.

    Accepts an ``Attributes`` sequence of ``(name, value)`` pairs **or** a
    ``Mapping`` (``{"data-x": "y"}``), so callers can build dynamic attributes
    as whichever is convenient and pass them through the single positional
    ``attrs`` slot. ``None`` -> empty list.
    """
    if attrs is None:
        return []
    if isinstance(attrs, Mapping):
        return list(attrs.items())
    return list(attrs)


def element_builder(tag_name: str, media: Media | None = None, default_class: str = ""):
    """Build a generic element builder for ``tag_name`` (the whitelist factory).

    If ``media`` is provided, every node created by the builder will carry it
    (used for custom elements whose compiled JS must be loaded automatically).

    ``default_class`` bakes a base class list onto every node; caller ``class_``
    accumulates onto it (node-layer class merge). Note accumulation is not
    override — a caller cannot down-scale a baked size utility (Tailwind sorts
    ``text-*`` alphabetically), so components wanting a different scale build on
    a plain, unstyled builder (e.g. ``PlainH1``) instead.
    """

    def element(
        attrs: AttrsArg | None = None,
        **kwargs: object,
    ) -> Element:
        # Merge order is priority order — first contributor wins per the node
        # algebra: baked ``default_class`` first, then positional ``attrs``
        # (dynamic), then htpy ``kwargs`` (static); ``class`` accumulates across
        # all three. Children come via ``[]``.
        merged = _coerce_attrs(attrs) + _attrs_from_kwargs(kwargs)
        if default_class:
            merged = [("class", default_class), *merged]
        node = Element(tag_name, merged)
        return node.with_media(media) if media else node

    element.__name__ = element.__qualname__ = tag_name[:1].upper() + tag_name[1:]
    element.__doc__ = f"Builder for the <{tag_name}> element."
    return element


# ── Plain HTML elements ──────────────────────────────────────────────────────
# A whitelist of plain tags, each turned into a builder over `Element`. The
# tag name is data, not a separate class/function body. Add a tag = one line.

A = element_builder("a")
Button = element_builder("button")
Div = element_builder("div")
P = element_builder("p")
Ul = element_builder("ul")
Li = element_builder("li")
Br = element_builder("br")
Strong = element_builder("strong")
Span = element_builder("span")
Label = element_builder("label")
Template = element_builder("template")
Td = element_builder("td")
Tr = element_builder("tr")
Th = element_builder("th")
Table = element_builder("table")
Thead = element_builder("thead")
Tbody = element_builder("tbody")
Caption = element_builder("caption")
Nav = element_builder("nav")
Img = element_builder("img")
Html = element_builder("html")
Form = element_builder("form")
Head = element_builder("head")
Body = element_builder("body")
Meta = element_builder("meta")
Title = element_builder("title")
Script = element_builder("script")
Link = element_builder("link")
Select = element_builder("select")
Option = element_builder("option")
Optgroup = element_builder("optgroup")
Noscript = element_builder("noscript")
Dl = element_builder("dl")
Dt = element_builder("dt")
Dd = element_builder("dd")
Fieldset = element_builder("fieldset")
Legend = element_builder("legend")
Dialog = element_builder("dialog")
Section = element_builder("section")
# Size token only, no margin: parents own spacing via `gap` (see
# docs/visual-conventions.md §3), enforced by tests/test_heading_margins.py.
H1 = element_builder("h1", default_class="text-type-title")
H2 = element_builder("h2", default_class="text-type-heading")
H3 = element_builder("h3", default_class="text-type-subheading")
# Unstyled heading builders for the few components whose heading needs a scale
# other than H1/H2/H3's baked default — class accumulation can't down-scale a
# baked size utility, so these carry no default_class and the caller supplies
# the full class list (e.g. DialogTitle, BottomSheet's title, stats cards).
PlainH1 = element_builder("h1")
PlainH2 = element_builder("h2")
PlainH4 = element_builder("h4")

# ── SVG elements ──────────────────────────────────────────────────────────
# Used by hand-written SVG (theme.py) and by the icon codegen (gen_icons.py),
# which imports these directly to avoid a cycle through primitives.py.

Svg = element_builder("svg")
Circle = element_builder("circle")
Path = element_builder("path")
Rect = element_builder("rect")
G = element_builder("g")
