"""General structural ``TypedDict`` -> TypeScript codegen.

Emits TS ``interface`` + named ``type`` declarations for a set of root
``TypedDict``s and the transitive closure of the aliases / nested TypedDicts they
reference. Unlike the element-props codegen in ``custom_elements.py`` (camelCase
fields + a DOM attribute reader), this emitter keeps field names **verbatim** —
the values are ``json.dumps``-serialized dicts whose keys are the snake_case
Python field names — and emits **no** reader: consumers ``JSON.parse`` the wire
blob and cast it to the generated interface. ``ts/generated/`` is gitignored and
regenerated on every ``make ts`` / ``ts-check``, so a Python schema change re-emits
these interfaces and a stale cast fails ``tsc`` — that build step is the drift guard.

Handles: primitives, PEP695 ``type X = ...`` aliases (``TypeAliasType``), nested
``TypedDict``s, ``list[T]``, ``dict[K, V]`` (→ ``Record``), ``frozenset[T]``/
``set[T]`` (→ arrays), ``X | Y`` unions, and ``Literal[...]`` string unions.

Besides types, the module can emit *values*: each ``TsConstant`` becomes a typed
``export const`` whose value is JSON-serialized deterministically (enum members
flatten to their ``.value``; sets sort — their iteration order varies with hash
randomization; dict insertion order is meaningful and kept). This is how shared
vocabulary tables (``SPACE_GROUPS``, the ordered-modifier list, issue #284) reach
TS without a hand-kept mirror.
"""

import json
import re
import types
from collections.abc import Mapping, Sequence
from enum import Enum
from typing import (
    Literal,
    NamedTuple,
    TypeAliasType,
    Union,
    cast,
    get_args,
    get_origin,
    get_type_hints,
    is_typeddict,
)

from common.components.custom_elements import _TYPE_MAP, TypedDictClass

type TsName = str  # a TS interface/alias identifier, e.g. "FieldMeta"
type TsTypeExpr = str  # a rendered TS type expression, e.g. "ChoiceMeta[]"
# A runtime type-annotation object, e.g. list[ModifierToken]. `object` because
# annotation objects (TypeAliasType, types.GenericAlias, plain classes) share no
# useful static supertype; ts_type() rejects unsupported ones loudly.
type PyTypeAnnotation = object

_TS_IDENTIFIER = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def render_choice_vocabulary(
    *,
    type_name: str,
    values_name: str,
    labels_name: str,
    choices: Sequence[tuple[str, str]],
) -> str:
    """Render Django-style value/label choices as a closed TS vocabulary."""
    for name in (type_name, values_name, labels_name):
        if not _TS_IDENTIFIER.fullmatch(name):
            raise ValueError(f"ts_codegen: invalid TypeScript identifier {name!r}")
    if not choices:
        raise ValueError("ts_codegen: choice vocabulary must not be empty")

    values: list[str] = []
    labels: list[str] = []
    seen: set[str] = set()
    for value, label in choices:
        if not isinstance(value, str) or not value:
            raise ValueError("ts_codegen: choice values must be non-empty strings")
        if value in seen:
            raise ValueError(f"ts_codegen: duplicate choice value {value!r}")
        if not isinstance(label, str):
            raise ValueError("ts_codegen: choice labels must be strings")
        seen.add(value)
        values.append(value)
        labels.append(label)

    rendered_values = json.dumps(values, ensure_ascii=False)
    label_lines = []
    for value, label in zip(values, labels, strict=True):
        key = value if _TS_IDENTIFIER.fullmatch(value) else json.dumps(value)
        label_lines.append(f"  {key}: {json.dumps(label, ensure_ascii=False)},")
    return (
        "// GENERATED by `manage.py gen_element_types` — do not edit.\n\n"
        f"export const {values_name} = {rendered_values} as const;\n"
        f"export type {type_name} = typeof {values_name}[number];\n"
        f"export const {labels_name} = {{\n"
        + "\n".join(label_lines)
        + f"\n}} satisfies Record<{type_name}, string>;\n"
    )


class TsField(NamedTuple):
    name: str  # verbatim Python field name, e.g. "search_url"
    ts_type: TsTypeExpr  # its rendered TS type, e.g. "string"


class TsConstant(NamedTuple):
    """One Python value to publish as a typed ``export const``."""

    name: TsName  # the exported const identifier, e.g. "SPACE_GROUPS"
    python_type: PyTypeAnnotation  # rendered to the const's TS type via ts_type()
    value: object  # the runtime value, serialized via _jsonable()


def _jsonable(value: object) -> object:
    """A constant's runtime value as deterministic JSON-serializable data."""
    if isinstance(value, Enum):
        return _jsonable(value.value)
    if isinstance(value, (frozenset, set)):
        # key=repr: lexicographic for the string members these tables hold, and
        # total (never a TypeError) should a future set mix member types.
        return sorted((_jsonable(item) for item in value), key=repr)
    if isinstance(value, Mapping):
        # JSON object keys must be strings: json.dumps would silently coerce a
        # non-string key (True -> "true"), and two keys flattening to the same
        # string (e.g. an Enum member and its value) would silently collapse
        # last-wins. Both are table-authoring bugs — fail at codegen.
        result: dict[str, object] = {}
        for key, item in value.items():
            json_key = _jsonable(key)
            if not isinstance(json_key, str):
                raise TypeError(f"ts_codegen: non-string dict key {key!r}")
            if json_key in result:
                raise TypeError(f"ts_codegen: dict keys collide on {json_key!r}")
            result[json_key] = _jsonable(item)
        return result
    if isinstance(value, (list, tuple)):
        return [_jsonable(item) for item in value]
    return value


def render_filter_metadata_module(
    roots: list[TypedDictClass], constants: Sequence[TsConstant] = ()
) -> str:
    """The full ``ts/generated/filter-metadata.ts`` content for ``roots``.

    Each root is a ``TypedDict``; the closure of aliases + nested TypedDicts they
    reference is emitted too — including anything only a ``constants`` type
    annotation references. Aliases come first, then interfaces (both in
    discovery order), then constants in caller order — irrelevant to ``tsc``,
    but stable output.
    """
    aliases: dict[TsName, TsTypeExpr] = {}
    interfaces: dict[TsName, list[TsField]] = {}

    def register_interface(typed_dict: TypedDictClass) -> None:
        if not is_typeddict(typed_dict):
            raise TypeError(f"ts_codegen: {typed_dict!r} is not a TypedDict")
        name = typed_dict.__name__
        if name in interfaces:
            return
        interfaces[name] = []  # reserve slot (recursion guard) before descending
        interfaces[name] = [
            TsField(field_name, ts_type(field_type))
            for field_name, field_type in get_type_hints(typed_dict).items()
        ]

    def ts_type(python_type: PyTypeAnnotation) -> TsTypeExpr:
        if python_type in _TYPE_MAP:
            return _TYPE_MAP[python_type]
        if isinstance(python_type, TypeAliasType):
            name = python_type.__name__
            if name not in aliases:
                aliases[name] = ""  # reserve slot before resolving the value
                aliases[name] = ts_type(python_type.__value__)
            return name
        if is_typeddict(python_type):
            typed_dict = cast(type, python_type)
            register_interface(typed_dict)
            return typed_dict.__name__
        origin = get_origin(python_type)
        if origin is Union or origin is types.UnionType:
            return " | ".join(ts_type(arg) for arg in get_args(python_type))
        if origin is Literal:
            return " | ".join(json.dumps(arg) for arg in get_args(python_type))
        if origin is list:
            (item_type,) = get_args(python_type)
            return f"{ts_type(item_type)}[]"
        if origin is frozenset or origin is set:
            # Sets serialize as (sorted) JSON arrays, so their TS face is an array.
            (item_type,) = get_args(python_type)
            return f"{ts_type(item_type)}[]"
        if origin is dict:
            key_type, value_type = get_args(python_type)
            return f"Record<{ts_type(key_type)}, {ts_type(value_type)}>"
        raise TypeError(f"ts_codegen: unsupported type {python_type!r}")

    for root in roots:
        register_interface(root)

    def render_constant(constant: TsConstant) -> str:
        # Contextualize failures: json.dumps/_jsonable errors name only the
        # offending value, useless once several constants are registered.
        # allow_nan=False: NaN/Infinity are valid TS `number` expressions but
        # not JSON — reject rather than emit a not-actually-JSON constant.
        try:
            return "export const {name}: {ts_type} = {value};".format(
                name=constant.name,
                ts_type=ts_type(constant.python_type),
                value=json.dumps(_jsonable(constant.value), indent=2, allow_nan=False),
            )
        except (TypeError, ValueError) as error:
            raise TypeError(
                f"ts_codegen: constant {constant.name!r}: {error}"
            ) from error

    # Render constants before assembling blocks: a constant's type annotation
    # may pull in aliases nothing in `roots` references.
    constant_blocks = [render_constant(constant) for constant in constants]

    # No reserve-slot placeholder should survive: every reserved alias/interface is
    # overwritten before the loop returns. Assert it so a future early-return leak
    # fails here, not as invalid TS (`export type X = ;`) downstream in tsc.
    assert "" not in aliases.values(), "unresolved alias placeholder"

    header = "// GENERATED by `manage.py gen_element_types` — do not edit.\n"
    alias_blocks = [f"export type {name} = {expr};" for name, expr in aliases.items()]
    interface_blocks = [
        "export interface {name} {{\n{body}\n}}".format(
            name=name,
            body="\n".join(f"  {field.name}: {field.ts_type};" for field in fields),
        )
        for name, fields in interfaces.items()
    ]
    return (
        header
        + "\n"
        + "\n\n".join(alias_blocks + interface_blocks + constant_blocks)
        + "\n"
    )
