"""General structural ``TypedDict`` -> TypeScript codegen.

Emits TS ``interface`` + named ``type`` declarations for a set of root
``TypedDict``s and the transitive closure of the aliases / nested TypedDicts they
reference. Unlike the element-props codegen in ``custom_elements.py`` (camelCase
fields + a DOM attribute reader), this emitter keeps field names **verbatim** —
the values are ``json.dumps``-serialized dicts whose keys are the snake_case
Python field names — and emits **no** reader: consumers ``JSON.parse`` the wire
blob and cast it to the generated interface, so ``tsc`` is the drift guard.

Handles: primitives, PEP695 ``type X = ...`` aliases (``TypeAliasType``), nested
``TypedDict``s, ``list[T]``, ``X | Y`` unions, and ``Literal[...]`` string unions.
"""

import json
import types
from typing import (
    Literal,
    TypeAliasType,
    Union,
    cast,
    get_args,
    get_origin,
    get_type_hints,
    is_typeddict,
)

from common.components.custom_elements import _TYPE_MAP

# A field name and its rendered TS type, e.g. ("search_url", "string").
type TsField = tuple[str, str]


def render_filter_metadata_module(roots: list[type]) -> str:
    """The full ``ts/generated/filter-metadata.ts`` content for ``roots``.

    Each root is a ``TypedDict``; the closure of aliases + nested TypedDicts they
    reference is emitted too. Aliases come first, then interfaces, in discovery
    order (irrelevant to ``tsc``, but stable output).
    """
    aliases: dict[str, str] = {}  # name -> TS type expression
    interfaces: dict[str, list[TsField]] = {}  # name -> ordered fields

    def register_interface(typed_dict: type) -> None:
        name = typed_dict.__name__
        if name in interfaces:
            return
        interfaces[name] = []  # reserve slot (recursion guard) before descending
        interfaces[name] = [
            (field_name, ts_type(field_type))
            for field_name, field_type in get_type_hints(typed_dict).items()
        ]

    def ts_type(python_type: object) -> str:
        if python_type in _TYPE_MAP:
            return _TYPE_MAP[python_type]
        if isinstance(python_type, TypeAliasType):
            name = python_type.__name__
            if name not in aliases:
                aliases[name] = ""  # reserve slot before resolving the value
                aliases[name] = ts_type(python_type.__value__)
            return name
        if is_typeddict(python_type):
            typed_dict = cast(type, python_type)
            register_interface(typed_dict)
            return typed_dict.__name__
        origin = get_origin(python_type)
        if origin is Union or origin is types.UnionType:
            return " | ".join(ts_type(arg) for arg in get_args(python_type))
        if origin is Literal:
            return " | ".join(json.dumps(arg) for arg in get_args(python_type))
        if origin is list:
            (item_type,) = get_args(python_type)
            return f"{ts_type(item_type)}[]"
        raise TypeError(f"ts_codegen: unsupported type {python_type!r}")

    for root in roots:
        register_interface(root)

    header = "// GENERATED by `manage.py gen_element_types` — do not edit.\n"
    alias_blocks = [f"export type {name} = {expr};" for name, expr in aliases.items()]
    interface_blocks = [
        "export interface {name} {{\n{body}\n}}".format(
            name=name,
            body="\n".join(f"  {field}: {ts};" for field, ts in fields),
        )
        for name, fields in interfaces.items()
    ]
    return header + "\n" + "\n\n".join(alias_blocks + interface_blocks) + "\n"
