name: Django CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Install Poetry
      run: |
        python -m pip install poetry
        echo "$HOME/.local/bin" >> $GITHUB_PATH        
    - name: Install Dependencies
      run: |
        poetry install        
    - name: Apply migrations
      run: |
        poetry run python manage.py migrate        
    - name: Run Tests
      run: |
        poetry run python manage.py test        

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          registry.kucharczyk.xyz/timetracker:latest
          registry.kucharczyk.xyz/timetracker:${{ env.VERSION_NUMBER }}          
    env:
      VERSION_NUMBER: 1.5.1
