"""Write common/components/icons_generated.py from games/templates/icons/*.html.

Icons are authored as raw SVG snippets but consumed as first-class node trees.
This command parses each snippet once (build time) and emits a committed Python
module of ``Element`` trees, so the runtime never parses XML. Run it after
adding or editing an icon: ``make gen-icons`` (CI guards drift via ``--check``).
"""

from pathlib import Path
from xml.etree import ElementTree

from django.conf import settings
from django.core.management.base import BaseCommand

from common.icons import iter_icon_sources

SVG_NAMESPACE = "http://www.w3.org/2000/svg"
_TARGET = Path("common") / "components" / "icons_generated.py"

# Every SVG tag actually used by an icon snippet must have a named builder in
# elements.py (imported below, not from primitives.py — that would cycle back
# through icons_generated.py). An icon introducing a new tag should get a
# builder added there; this map is intentionally exhaustive, not a fallback.
_TAG_BUILDERS = {
    "svg": "Svg",
    "path": "Path",
    "circle": "Circle",
    "rect": "Rect",
    "g": "G",
    "title": "Title",
}

_HEADER = """\
# Generated by `manage.py gen_icons` from games/templates/icons/*.html.
# Do not edit by hand — run `make gen-icons` after changing an icon.
from common.components.core import Element
from common.components.elements import Circle, G, Path, Rect, Svg, Title

ICON_NODES: dict[str, Element] = {
"""


def _local_name(tag: str) -> str:
    """Strip an ElementTree namespace: ``{http://…/svg}path`` -> ``path``."""
    return tag.rsplit("}", 1)[-1]


def _emit_node(source: ElementTree.Element, indent: int) -> str:
    """Render one SVG element as a Python named-builder source expression."""
    pad = "    " * indent
    inner_pad = "    " * (indent + 1)

    tag = _local_name(source.tag)
    builder = _TAG_BUILDERS[tag]
    attributes = [(_local_name(key), value) for key, value in source.attrib.items()]
    if tag == "svg":
        # ElementTree consumes the source xmlns into namespace machinery, so
        # re-declare it explicitly to keep the rendered <svg> self-contained.
        attributes.append(("xmlns", SVG_NAMESPACE))

    children: list[str] = []
    if source.text and source.text.strip():
        children.append(f"{inner_pad}{source.text!r}")
    for child in source:
        children.append(_emit_node(child, indent + 1))
        if child.tail and child.tail.strip():
            children.append(f"{inner_pad}{child.tail!r}")

    attributes_source = repr(attributes)
    if not children:
        return f"{pad}{builder}({attributes_source})"
    children_block = ",\n".join(children)
    return (
        f"{pad}{builder}(\n"
        f"{inner_pad}{attributes_source},\n"
        f"{pad})[\n"
        f"{children_block},\n"
        f"{pad}]"
    )


def render_icons_module() -> str:
    """Build the full source of the generated icons module (deterministic)."""
    entries = []
    for name, raw_html in iter_icon_sources():
        root = ElementTree.fromstring(raw_html)
        entries.append(f"    {name!r}: {_emit_node(root, 1).lstrip()},")
    return _HEADER + "\n".join(entries) + "\n}\n"


class Command(BaseCommand):
    help = "Generate common/components/icons_generated.py from icon SVG snippets."

    def add_arguments(self, parser) -> None:
        parser.add_argument(
            "--check",
            action="store_true",
            help="Exit non-zero if the generated module is stale; do not write.",
        )

    def handle(self, *args, **options) -> None:
        target = Path(settings.BASE_DIR) / _TARGET
        rendered = render_icons_module()

        if options["check"]:
            current = target.read_text(encoding="utf-8") if target.exists() else ""
            if current != rendered:
                self.stderr.write(
                    self.style.ERROR(f"{_TARGET} is out of date. Run `make gen-icons`.")
                )
                raise SystemExit(1)
            self.stdout.write(self.style.SUCCESS(f"{_TARGET} is up to date."))
            return

        target.write_text(rendered, encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(f"Wrote {target}"))
