"""Commands about the sessions a library records."""

import uuid
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from functools import lru_cache
from typing import ClassVar, NamedTuple

from django.db import connection

from common.date_time_presentation import zone_or_none
from games.commands.playthrough import _live_run
from games.commands.scope import Refusal, library_row
from games.events.dispatch import Command, CommandContext, CommandName, CommandRejected
from games.events.playersession import (
    TimingPayload,
    day_text,
    instant_text,
    playersession_created,
)
from games.events.references import capture_reference
from games.events.vocabulary import NewEvent, Unchanged
from games.models import Device

#: The finest duration a statement may carry. The payload states whole
#: seconds while the fingerprint states microseconds, so anything
#: finer would fingerprint differently from the event it recorded and
#: answer an honest retry with a conflict.
DURATION_RESOLUTION = timedelta(seconds=1)


class TimedTiming(NamedTuple):
    """An exact start, an end once there is one, no override.

    A NamedTuple, so the idempotency fingerprint encodes it as an
    array: a dataclass reaches the encoder's fallback and raises.
    """

    started_at: datetime
    #: The zone this library counts the session's day in.
    day_zone: str
    #: Where the clock stood. None is a zone nobody stated.
    started_at_zone: str | None = None
    ended_at: datetime | None = None
    ended_at_zone: str | None = None


class DurationOnlyTiming(NamedTuple):
    """A written calendar day and a duration. No instants."""

    day: date
    duration: timedelta


class CorrectedTiming(NamedTuple):
    """Both instants, and a duration that replaces the elapsed time."""

    started_at: datetime
    ended_at: datetime
    duration: timedelta
    day_zone: str
    started_at_zone: str | None = None
    ended_at_zone: str | None = None


type TimingStatement = TimedTiming | DurationOnlyTiming | CorrectedTiming


@lru_cache(maxsize=1)
def _database_zones() -> frozenset[str]:
    """The zones PostgreSQL can evaluate.

    Python's tzdata and the database's are separate data sets -- in a
    container they arrive in different images -- and `effective_day`
    is generated by the database. A name only Python knows would pass
    this command and raise a DataError inside the append, which
    nothing maps to an answer, and again mid-rebuild, where no repair
    is possible without editing recorded events.
    """
    with connection.cursor() as cursor:
        cursor.execute("SELECT name FROM pg_timezone_names")
        return frozenset(name for (name,) in cursor.fetchall())


def known_zone(name: str) -> bool:
    """Whether both tzdata sets read this name."""
    return zone_or_none(name) is not None and name in _database_zones()


@dataclass(frozen=True, slots=True)
class CreateSession(Command):
    """Record one session against a run the caller names.

    The run is stated, never inferred from the game, the day or
    another session, which is the rule the charter applies to a
    release. The zone the day is read in is stated with it, for the
    same reason: a command that resolves a preference records a fact
    nobody stated.
    """

    command_name: ClassVar[CommandName] = CommandName.PLAYERSESSION_CREATE
    #: A UUID, because Command fingerprints its fields.
    playthrough_id: uuid.UUID
    timing: TimingStatement
    device_id: uuid.UUID | None = None
    note: str = ""
    emulated: bool = False

    def __post_init__(self) -> None:
        #: One spelling of a blank note, so a restatement fingerprints alike.
        object.__setattr__(self, "note", self.note.strip())
        #: Before the fingerprint rather than inside build(): dispatch
        #: fingerprints the input first, and a naive datetime has no
        #: canonical form there, so a build-time refusal would never
        #: run and the person would see a TypeError instead.
        for instant in (
            getattr(self.timing, "started_at", None),
            getattr(self.timing, "ended_at", None),
        ):
            if instant is None:
                continue
            if instant.tzinfo is None or instant.utcoffset() is None:
                raise CommandRejected(
                    f"{instant!r} states no offset, so it names no instant and "
                    "would read differently on another host.",
                    sentence="That time is missing its time zone.",
                )

    def build(self, context: CommandContext) -> Sequence[NewEvent] | Unchanged:
        run = _live_run(context, self.playthrough_id)
        device = self._device(context)
        return [
            playersession_created(
                run.pk,
                timing=self._timing_payload(),
                device=None if device is None else capture_reference(device),
                release=None,
                note=self.note,
                emulated=self.emulated,
            )
        ]

    def _device(self, context: CommandContext) -> Device | None:
        """This library's device, or a refusal."""
        if self.device_id is None:
            return None
        device = library_row(
            context,
            Device.objects.all(),
            Refusal(
                message=(
                    f"This library holds no device {self.device_id}. A session "
                    "names a device the library records."
                ),
                sentence="That device is not available.",
            ),
            pk=self.device_id,
        )
        #: Under dispatch's lock: the mark cannot move.
        if device.removed_at is not None:
            raise CommandRejected(
                f"This library removed device {self.device_id}, so it records "
                "no further sessions on it.",
                sentence=(
                    "That device was removed from your library. Restore it "
                    "before recording a session on it."
                ),
            )
        return device

    def _timing_payload(self) -> TimingPayload:
        """What the statement records, refusing what it cannot."""
        match self.timing:
            case DurationOnlyTiming(day=day, duration=duration):
                self._check_duration(duration)
                if duration == timedelta(0):
                    raise CommandRejected(
                        "A duration-only session of no duration states nothing: "
                        "the census reads a legacy row with no end and no "
                        "duration as a running session, which no mode holds.",
                        sentence="Say how long this session lasted.",
                    )
                return {
                    "mode": "duration_only",
                    "stated_day": day_text(day),
                    "duration_seconds": int(duration.total_seconds()),
                }
            case TimedTiming(
                started_at=started_at,
                day_zone=day_zone,
                started_at_zone=started_at_zone,
                ended_at=ended_at,
                ended_at_zone=ended_at_zone,
            ):
                self._check_instants(started_at, ended_at)
                self._check_zones(day_zone, started_at_zone, ended_at_zone)
                self._check_endpoint_zone(ended_at, ended_at_zone, endpoint="end")
                return {
                    "mode": "timed",
                    "started_at": instant_text(started_at),
                    "started_at_zone": started_at_zone,
                    "ended_at": None if ended_at is None else instant_text(ended_at),
                    "ended_at_zone": ended_at_zone,
                    "day_zone": day_zone,
                }
            case CorrectedTiming(
                started_at=started_at,
                ended_at=ended_at,
                duration=duration,
                day_zone=day_zone,
                started_at_zone=started_at_zone,
                ended_at_zone=ended_at_zone,
            ):
                self._check_instants(started_at, ended_at)
                self._check_zones(day_zone, started_at_zone, ended_at_zone)
                self._check_duration(duration)
                return {
                    "mode": "corrected",
                    "started_at": instant_text(started_at),
                    "started_at_zone": started_at_zone,
                    "ended_at": instant_text(ended_at),
                    "ended_at_zone": ended_at_zone,
                    "day_zone": day_zone,
                    "duration_seconds": int(duration.total_seconds()),
                }

    @staticmethod
    def _check_instants(started_at: datetime, ended_at: datetime | None) -> None:
        """Instants in the order they happened."""
        if ended_at is not None and ended_at < started_at:
            raise CommandRejected(
                "The session being recorded would end before it began, and no "
                "session does.",
                sentence="This session ended before it started. Check the times.",
            )

    @staticmethod
    def _check_duration(duration: timedelta) -> None:
        """A whole number of seconds, and not a negative one."""
        if duration < timedelta(0):
            raise CommandRejected(
                f"A session cannot last {duration}, and no negative duration is "
                "a length of time.",
                sentence="A session cannot last a negative amount of time.",
            )
        if duration % DURATION_RESOLUTION:
            raise CommandRejected(
                f"{duration} is finer than a second, which a recorded payload "
                "cannot carry. Truncating it here would fingerprint the retry "
                "of this very statement as a different one.",
                sentence="State this session's length in whole seconds.",
            )

    @staticmethod
    def _check_zones(day_zone: str, *endpoint_zones: str | None) -> None:
        """Names both tzdata sets read."""
        for name in (day_zone, *endpoint_zones):
            if name is None:
                continue
            if not known_zone(name):
                raise CommandRejected(
                    f"{name!r} is not a time zone this installation can read, "
                    "and the day this session lands on is computed from one.",
                    sentence=f"{name or 'That'} is not a time zone we know.",
                )

    @staticmethod
    def _check_endpoint_zone(
        instant: datetime | None, zone: str | None, *, endpoint: str
    ) -> None:
        """A zone says where a clock stood, so it needs the clock."""
        if instant is None and zone is not None:
            raise CommandRejected(
                f"This session states the zone of an {endpoint} it does not "
                "state, and a zone with no instant says nothing.",
                sentence=(
                    f"This session has no {endpoint} time, so it cannot have "
                    f"an {endpoint} time zone."
                ),
            )
