"""Commands about the sessions a library records."""

import uuid
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from functools import lru_cache
from typing import ClassVar, NamedTuple, assert_never
from zoneinfo import ZoneInfo

from django.db import connection

from common.date_time_presentation import zone_or_none
from games.commands.playthrough import _live_run
from games.commands.scope import Refusal, library_row
from games.events.dispatch import Command, CommandContext, CommandName, CommandRejected
from games.events.playersession import (
    TimingPayload,
    ZoneName,
    day_text,
    instant_text,
    playersession_created,
    playersession_ended,
)
from games.events.references import capture_reference
from games.events.vocabulary import NewEvent, Unchanged
from games.models import Device, PlayerSession, PlayerSessionTimingMode

#: The finest duration a statement may carry. The payload states whole
#: seconds while the fingerprint states microseconds, so anything
#: finer would fingerprint differently from the event it recorded and
#: answer an honest retry with a conflict.
DURATION_RESOLUTION = timedelta(seconds=1)


class TimedTiming(NamedTuple):
    """An exact start, an end once there is one, no override.

    A NamedTuple, so the idempotency fingerprint encodes it as an
    array: a dataclass reaches the encoder's fallback and raises.
    The array carries no tag, so the three statements are told
    apart by their length alone -- a fourth one with five fields
    would fingerprint as this one and replay as it.
    """

    started_at: datetime
    #: The zone this library counts the session's day in.
    day_zone: str
    #: Where the clock stood. None is a zone nobody stated.
    started_at_zone: str | None = None
    ended_at: datetime | None = None
    ended_at_zone: str | None = None


class DurationOnlyTiming(NamedTuple):
    """A written calendar day and a duration. No instants."""

    day: date
    duration: timedelta


class CorrectedTiming(NamedTuple):
    """Both instants, and a duration that replaces the elapsed time."""

    started_at: datetime
    ended_at: datetime
    duration: timedelta
    day_zone: str
    started_at_zone: str | None = None
    ended_at_zone: str | None = None


type TimingStatement = TimedTiming | DurationOnlyTiming | CorrectedTiming


@lru_cache(maxsize=1)
def _database_zones() -> frozenset[str]:
    """The zones PostgreSQL can evaluate.

    Python's tzdata and the database's are separate data sets -- in a
    container they arrive in different images -- and `effective_day`
    is generated by the database. A name only Python knows would pass
    this command and raise a DataError inside the append, which
    nothing maps to an answer, and again mid-rebuild, where no repair
    is possible without editing recorded events.
    """
    with connection.cursor() as cursor:
        cursor.execute("SELECT name FROM pg_timezone_names")
        return frozenset(name for (name,) in cursor.fetchall())


def known_zone(name: str) -> bool:
    """Whether both tzdata sets read this name.

    A miss re-reads the database before refusing. The cache holds
    for the life of the process while the database is a separate
    image that may be replaced under it, so a zone added there
    would otherwise be refused until something restarted this one.
    A zone the database *loses* stays admitted until then, which is
    the rarer direction and the one the generated day reports.
    """
    if zone_or_none(name) is None:
        return False
    if name in _database_zones():
        return True
    _database_zones.cache_clear()
    return name in _database_zones()


def _stated_zone(name: str | None) -> ZoneName | None:
    """One spelling of a zone, and one of an unstated one.

    A browser reporting no zone posts an empty string, and a form
    round-trip pads a name. Both are normalized before the
    fingerprint, so one statement keeps one digest however it was
    spelled, and every command in this module reads a zone alike.
    """
    stated = (name or "").strip()
    return stated or None


def _check_aware(*instants: datetime | None) -> None:
    """Instants that name a moment anywhere."""
    for instant in instants:
        if instant is None:
            continue
        if instant.tzinfo is None or instant.utcoffset() is None:
            raise CommandRejected(
                f"{instant!r} states no offset, so it names no instant and "
                "would read differently on another host.",
                sentence="That time is missing its time zone.",
            )


def _live_session(context: CommandContext, session_id: uuid.UUID) -> PlayerSession:
    """The session, refused if nothing may be stated about it."""
    session = library_row(
        context,
        #: The plain manager: a removed row is refused by name below,
        #: not hidden into "no such session".
        PlayerSession.objects.all(),
        Refusal(
            message=(
                f"This library holds no session {session_id}. A stated fact "
                "belongs to a session the library records."
            ),
            sentence="That session is not available.",
        ),
        pk=session_id,
    )
    #: For its scope as much as its marks: it proves the
    #: session's run is this library's, which is the
    #: registered reference the ownership audit walks.
    _live_run(context, session.playthrough_id)
    #: Under dispatch's lock: the mark cannot move. Nothing states one
    #: yet, so this branch waits for the removal command rather than
    #: being unreachable.
    if session.removed_at is not None:
        raise CommandRejected(
            f"This library removed session {session_id}, so it states no "
            "further facts about it.",
            sentence=(
                "That session was removed from your library. Restore it "
                "before recording this."
            ),
        )
    return session


class TimedStart(NamedTuple):
    """A Timed row's start, and the zone its library counts days in.

    The zone is resolved, not named: it comes off a row an earlier
    statement wrote, so reading it is where a name this installation
    lost is still a sentence rather than a `KeyError` in the builder.
    """

    started_at: datetime
    day_zone: ZoneInfo


def _timed_start(session: PlayerSession) -> TimedStart:
    """A Timed row's start and its day zone.

    The mode is refused before either value is read, so a Corrected
    row is told what it is rather than told it already has an end:
    the remedy differs.
    """
    if session.timing_mode == PlayerSessionTimingMode.DURATION_ONLY:
        raise CommandRejected(
            f"Session {session.pk} states a written day and a duration, so it "
            "holds no instants and has no end to give.",
            sentence=(
                "This session records how long it lasted on a day, so it has "
                "no end to state."
            ),
        )
    if session.timing_mode == PlayerSessionTimingMode.CORRECTED:
        raise CommandRejected(
            f"Session {session.pk} already states both instants and an "
            "override, so its end is a correction rather than a first "
            "statement.",
            sentence=(
                "This session's time was already corrected, so it already has "
                "an end. Correct it again to change it."
            ),
        )
    started_at, day_zone = session.started_at, session.day_zone
    if started_at is None or day_zone is None:
        #: `playersession_timed_columns` forbids this. Refused rather
        #: than cast away, so a relaxed constraint lands here as a
        #: sentence instead of a TypeError inside the builder.
        raise CommandRejected(
            f"Timed session {session.pk} states no start or no day zone, which "
            "the timed-columns constraint forbids. The row is wrong, not the "
            "statement.",
            sentence="We cannot read that session's start time.",
        )
    zone = zone_or_none(day_zone)
    if zone is None:
        #: No constraint can reach this: the name passed `known_zone`
        #: when some earlier statement wrote it, and tzdata retires a
        #: zone between one image and the next. Unresolved, it reaches
        #: the builder as a `KeyError` the boundary does not answer.
        raise CommandRejected(
            f"Session {session.pk} counts its day in {day_zone!r}, which this "
            "installation's tzdata can no longer read, so the end it is given "
            "lands on no day.",
            sentence=("We cannot read the time zone this session's day is counted in."),
        )
    return TimedStart(started_at, zone)


@dataclass(frozen=True, slots=True)
class CreateSession(Command):
    """Record one session against a run the caller names.

    The run is stated, never inferred from the game, the day or
    another session, which is the rule the charter applies to a
    release. The zone the day is read in is stated with it, for the
    same reason: a command that resolves a preference records a fact
    nobody stated.
    """

    command_name: ClassVar[CommandName] = CommandName.PLAYERSESSION_CREATE
    #: A UUID, because Command fingerprints its fields.
    playthrough_id: uuid.UUID
    timing: TimingStatement
    device_id: uuid.UUID | None = None
    note: str = ""
    emulated: bool = False

    def __post_init__(self) -> None:
        #: One spelling of a blank note, so a restatement fingerprints alike.
        object.__setattr__(self, "note", self.note.strip())
        self._check_note(self.note)
        #: Before the fingerprint rather than inside build(): dispatch
        #: fingerprints the input first, and a naive datetime has no
        #: canonical form there, so a build-time refusal would never
        #: run and the person would meet a TypeError instead.
        #:
        #: Through the pattern rather than by attribute name: getattr
        #: with a default turns a renamed field into a guard that
        #: silently never runs, and the fingerprint encodes a
        #: NamedTuple positionally, so nothing else would object.
        match self.timing:
            case TimedTiming(started_at=started_at, ended_at=ended_at):
                _check_aware(started_at, ended_at)
                object.__setattr__(self, "timing", self._stated_zones(self.timing))
            case CorrectedTiming(started_at=started_at, ended_at=ended_at):
                _check_aware(started_at, ended_at)
                object.__setattr__(self, "timing", self._stated_zones(self.timing))
            case DurationOnlyTiming():
                #: A written day states no instant to be naive.
                pass
            case _:
                assert_never(self.timing)

    def build(self, context: CommandContext) -> Sequence[NewEvent] | Unchanged:
        run = _live_run(context, self.playthrough_id)
        device = self._device(context)
        return [
            playersession_created(
                run.pk,
                timing=self._timing_payload(),
                device=None if device is None else capture_reference(device),
                release=None,
                note=self.note,
                emulated=self.emulated,
            )
        ]

    def _device(self, context: CommandContext) -> Device | None:
        """This library's device, or a refusal."""
        if self.device_id is None:
            return None
        device = library_row(
            context,
            Device.objects.all(),
            Refusal(
                message=(
                    f"This library holds no device {self.device_id}. A session "
                    "names a device the library records."
                ),
                sentence="That device is not available.",
            ),
            pk=self.device_id,
        )
        #: Under dispatch's lock: the mark cannot move.
        if device.removed_at is not None:
            raise CommandRejected(
                f"This library removed device {self.device_id}, so it records "
                "no further sessions on it.",
                sentence=(
                    "That device was removed from your library. Restore it "
                    "before recording a session on it."
                ),
            )
        return device

    def _timing_payload(self) -> TimingPayload:
        """What the statement records, refusing what it cannot."""
        match self.timing:
            case DurationOnlyTiming(day=day, duration=duration):
                self._check_duration(duration)
                if duration == timedelta(0):
                    raise CommandRejected(
                        "A duration-only session of no duration states nothing. "
                        "A session still running is a timed one with no end "
                        "yet, not a duration of zero.",
                        sentence="Say how long this session lasted.",
                    )
                return {
                    "mode": "duration_only",
                    "stated_day": day_text(day),
                    "duration_seconds": int(duration.total_seconds()),
                }
            case TimedTiming(
                started_at=started_at,
                day_zone=day_zone,
                started_at_zone=started_at_zone,
                ended_at=ended_at,
                ended_at_zone=ended_at_zone,
            ):
                self._check_instants(started_at, ended_at)
                self._check_zones(day_zone, started_at_zone, ended_at_zone)
                self._check_endpoint_zone(ended_at, ended_at_zone, endpoint="end")
                return {
                    "mode": "timed",
                    "started_at": instant_text(started_at),
                    "started_at_zone": started_at_zone,
                    "ended_at": None if ended_at is None else instant_text(ended_at),
                    "ended_at_zone": ended_at_zone,
                    "day_zone": day_zone,
                }
            case CorrectedTiming(
                started_at=started_at,
                ended_at=ended_at,
                duration=duration,
                day_zone=day_zone,
                started_at_zone=started_at_zone,
                ended_at_zone=ended_at_zone,
            ):
                self._check_instants(started_at, ended_at)
                self._check_zones(day_zone, started_at_zone, ended_at_zone)
                self._check_duration(duration)
                return {
                    "mode": "corrected",
                    "started_at": instant_text(started_at),
                    "started_at_zone": started_at_zone,
                    "ended_at": instant_text(ended_at),
                    "ended_at_zone": ended_at_zone,
                    "day_zone": day_zone,
                    "duration_seconds": int(duration.total_seconds()),
                }
            case _:
                #: A fourth statement type reaches mypy here, rather
                #: than returning None into a payload nobody can read.
                assert_never(self.timing)

    @staticmethod
    def _stated_zones(
        timing: TimedTiming | CorrectedTiming,
    ) -> TimedTiming | CorrectedTiming:
        """The three zones a statement with instants carries.

        The day's zone keeps its blank spelling rather than becoming
        None: `_check_zones` refuses it with a sentence naming the
        fact it wants, while None there would read as a zone nobody
        has to state.
        """
        return timing._replace(
            day_zone=(timing.day_zone or "").strip(),
            started_at_zone=_stated_zone(timing.started_at_zone),
            ended_at_zone=_stated_zone(timing.ended_at_zone),
        )

    @staticmethod
    def _check_note(note: str) -> None:
        """Text PostgreSQL can store as JSON.

        `strip()` leaves a NUL byte in place, JSON carries it as
        `\u0000`, and JSONB refuses it -- a DataError raised while
        the event is appended, which nothing maps to an answer.
        """
        if "\x00" in note:
            raise CommandRejected(
                "This note holds a NUL byte, which JSONB cannot store, so the "
                "event would be refused as it was written.",
                sentence="That note contains a character we cannot store.",
            )

    @staticmethod
    def _check_instants(started_at: datetime, ended_at: datetime | None) -> None:
        """Instants in the order they happened."""
        if ended_at is not None and ended_at < started_at:
            raise CommandRejected(
                "The session being recorded would end before it began, and no "
                "session does.",
                sentence="This session ended before it started. Check the times.",
            )

    @staticmethod
    def _check_duration(duration: timedelta) -> None:
        """A whole number of seconds, and not a negative one."""
        if duration < timedelta(0):
            raise CommandRejected(
                f"A session cannot last {duration}, and no negative duration is "
                "a length of time.",
                sentence="A session cannot last a negative amount of time.",
            )
        if duration % DURATION_RESOLUTION:
            raise CommandRejected(
                f"{duration} is finer than a second, which a recorded payload "
                "cannot carry. Truncating it here would fingerprint the retry "
                "of this very statement as a different one.",
                sentence="State this session's length in whole seconds.",
            )

    @staticmethod
    def _check_zones(day_zone: str, *endpoint_zones: str | None) -> None:
        """Names both tzdata sets read.

        The day's zone is checked apart from the endpoints' because
        it is the one that must be there: checking it in the same
        loop would let `None` take the optional branch and reach the
        database, where the generated day is a DataError.
        """
        if day_zone is None:
            raise CommandRejected(
                "This session states no zone to read its day in, and every "
                "session with an instant lands on a day.",
                sentence="Say which time zone this session's day is read in.",
            )
        for name in (day_zone, *endpoint_zones):
            if name is None:
                continue
            if not known_zone(name):
                raise CommandRejected(
                    f"{name!r} is not a time zone this installation can read, "
                    "and the day this session lands on is computed from one.",
                    sentence=f"{name or 'That'} is not a time zone we know.",
                )

    @staticmethod
    def _check_endpoint_zone(
        instant: datetime | None, zone: str | None, *, endpoint: str
    ) -> None:
        """A zone says where a clock stood, so it needs the clock."""
        if instant is None and zone is not None:
            raise CommandRejected(
                f"This session states the zone of an {endpoint} it does not "
                "state, and a zone with no instant says nothing.",
                sentence=(
                    f"This session has no {endpoint} time, so it cannot have "
                    f"an {endpoint} time zone."
                ),
            )


@dataclass(frozen=True, slots=True)
class EndSession(Command):
    """State when a running Timed session ended."""

    command_name: ClassVar[CommandName] = CommandName.PLAYERSESSION_END
    #: A UUID, because Command fingerprints its fields.
    session_id: uuid.UUID
    ended_at: datetime
    #: No default: a forgotten argument is a TypeError at the call
    #: site, never a session recorded as stating no zone.
    ended_at_zone: ZoneName | None

    def __post_init__(self) -> None:
        #: One spelling, so a restatement fingerprints alike. A
        #: browser reporting no zone posts an empty string, which
        #: `known_zone` would refuse rather than record as unset.
        object.__setattr__(self, "ended_at_zone", _stated_zone(self.ended_at_zone))
        #: Before the fingerprint: dispatch hashes the input first,
        #: and a naive datetime has no canonical form there, so a
        #: build-time refusal would never run.
        _check_aware(self.ended_at)

    def build(self, context: CommandContext) -> Sequence[NewEvent] | Unchanged:
        session = _live_session(context, self.session_id)
        started_at, day_zone = _timed_start(session)
        if session.ended_at is not None:
            if (session.ended_at, session.ended_at_zone) == (
                self.ended_at,
                self.ended_at_zone,
            ):
                return Unchanged("This session already ends then.")
            raise CommandRejected(
                f"Session {self.session_id} already ends at {session.ended_at}, "
                "and a second end would say it stopped twice.",
                sentence=(
                    "This session already has an end. Correct the one it has "
                    "instead of stating another."
                ),
            )
        if self.ended_at < started_at:
            raise CommandRejected(
                f"Session {self.session_id} would end at {self.ended_at}, before "
                f"it started at {started_at}, and no session does.",
                sentence="This session would end before it started. Check the time.",
            )
        #: The only guard there is: the zone feeds no generated
        #: column, and no constraint refuses a name that is merely
        #: wrong, so an unknown one is recorded permanently.
        if self.ended_at_zone is not None and not known_zone(self.ended_at_zone):
            raise CommandRejected(
                f"{self.ended_at_zone!r} is not a time zone this installation "
                "can read, and the column would take it silently.",
                sentence=f"{self.ended_at_zone} is not a time zone we know.",
            )
        return [
            playersession_ended(
                session.pk,
                ended_at=self.ended_at,
                ended_at_zone=self.ended_at_zone,
                day_zone=day_zone,
            )
        ]
