# Generated by Django 6.0.6 on 2026-08-10 07:28

import datetime

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PC", "PC"),
                            ("Console", "Console"),
                            ("Handheld", "Handheld"),
                            ("Mobile", "Mobile"),
                            ("Single-board computer", "Single-board computer"),
                            ("Unknown", "Unknown"),
                        ],
                        default="Unknown",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sort_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "year_released",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "original_year_released",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("wikidata", models.CharField(blank=True, default="", max_length=50)),
                (
                    "playtime",
                    models.DurationField(
                        blank=True, default=datetime.timedelta(0), editable=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("u", "Unplayed"),
                            ("p", "Played"),
                            ("f", "Finished"),
                            ("r", "Retired"),
                            ("a", "Abandoned"),
                        ],
                        default="u",
                        max_length=1,
                    ),
                ),
                ("mastered", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("group", models.CharField(blank=True, default="", max_length=255)),
                ("icon", models.SlugField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency_from", models.CharField(max_length=255)),
                ("currency_to", models.CharField(max_length=255)),
                ("year", models.PositiveIntegerField()),
                ("rate", models.FloatField()),
            ],
            options={
                "unique_together": {("currency_from", "currency_to", "year")},
            },
        ),
        migrations.CreateModel(
            name="GameStatusChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("u", "Unplayed"),
                            ("p", "Played"),
                            ("f", "Finished"),
                            ("r", "Retired"),
                            ("a", "Abandoned"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("u", "Unplayed"),
                            ("p", "Played"),
                            ("f", "Finished"),
                            ("r", "Retired"),
                            ("a", "Abandoned"),
                        ],
                        max_length=1,
                    ),
                ),
                ("timestamp", models.DateTimeField(null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_changes",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="game",
            name="platform",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="games.platform",
            ),
        ),
        migrations.CreateModel(
            name="PlayEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started", models.DateField(blank=True, null=True)),
                ("ended", models.DateField(blank=True, null=True)),
                (
                    "days_to_finish",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            models.Case(
                                models.When(
                                    ended=models.F("started"), then=models.Value(1)
                                ),
                                default=models.Func(
                                    models.F("ended"),
                                    models.F("started"),
                                    arg_joiner=" - ",
                                    function="",
                                    output_field=models.IntegerField(),
                                    template="(%(expressions)s)",
                                ),
                                output_field=models.IntegerField(),
                            ),
                            models.Value(0),
                        ),
                        output_field=models.IntegerField(),
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playevents",
                        to="games.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_purchased", models.DateField(verbose_name="Purchased")),
                (
                    "date_refunded",
                    models.DateField(blank=True, null=True, verbose_name="Refunded"),
                ),
                ("infinite", models.BooleanField(default=False)),
                ("price", models.FloatField(default=0)),
                (
                    "price_currency",
                    models.CharField(blank=True, default="", max_length=3),
                ),
                ("converted_price", models.FloatField(null=True)),
                (
                    "converted_currency",
                    models.CharField(blank=True, default="", max_length=3),
                ),
                (
                    "needs_price_update",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "price_per_game",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            django.db.models.functions.comparison.Coalesce(
                                models.F("converted_price"), models.F("price"), 0
                            ),
                            "/",
                            django.db.models.functions.comparison.NullIf(
                                models.F("num_purchases"), 0
                            ),
                        ),
                        output_field=models.FloatField(),
                    ),
                ),
                ("num_purchases", models.IntegerField(default=0)),
                (
                    "ownership_type",
                    models.CharField(
                        choices=[
                            ("ph", "Physical"),
                            ("di", "Digital"),
                            ("du", "Digital Upgrade"),
                            ("re", "Rented"),
                            ("bo", "Borrowed"),
                            ("tr", "Trial"),
                            ("de", "Demo"),
                            ("pi", "Pirated"),
                        ],
                        default="di",
                        max_length=2,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("game", "Game"),
                            ("dlc", "DLC"),
                            ("season_pass", "Season Pass"),
                            ("battle_pass", "Battle Pass"),
                        ],
                        default="game",
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "games",
                    models.ManyToManyField(related_name="purchases", to="games.game"),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="games.platform",
                    ),
                ),
                (
                    "related_game",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="addon_purchases",
                        to="games.game",
                        verbose_name="Base game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp_start",
                    models.DateTimeField(db_index=True, verbose_name="Session start"),
                ),
                (
                    "timestamp_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Session end"
                    ),
                ),
                (
                    "timestamp_start_timezone",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "timestamp_end_timezone",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "duration_manual",
                    models.DurationField(
                        blank=True,
                        default=datetime.timedelta(0),
                        null=True,
                        verbose_name="Manual duration",
                    ),
                ),
                (
                    "duration_calculated",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            django.db.models.expressions.CombinedExpression(
                                models.F("timestamp_end"),
                                "-",
                                models.F("timestamp_start"),
                            ),
                            datetime.timedelta(0),
                        ),
                        output_field=models.DurationField(),
                    ),
                ),
                (
                    "duration_total",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.ExpressionWrapper(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.functions.comparison.Coalesce(
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("timestamp_end"),
                                        "-",
                                        models.F("timestamp_start"),
                                    ),
                                    datetime.timedelta(0),
                                ),
                                "+",
                                models.F("duration_manual"),
                            ),
                            output_field=models.DurationField(),
                        ),
                        output_field=models.DurationField(),
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("emulated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="games.device",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "get_latest_by": "timestamp_start",
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_currency",
                    models.CharField(blank=True, default=None, max_length=3, null=True),
                ),
                (
                    "default_landing_page",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("system", "System"),
                            ("light", "Light"),
                            ("dark", "Dark"),
                        ],
                        default=None,
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "display_time_zone",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "date_format_locale",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "datetime_format",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                ("extra_preferences", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="games.device",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user preferences",
                "verbose_name_plural": "user preferences",
            },
        ),
        migrations.CreateModel(
            name="FilterPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("games", "Games"),
                            ("sessions", "Sessions"),
                            ("purchases", "Purchases"),
                            ("playevents", "Play Events"),
                            ("devices", "Devices"),
                            ("platforms", "Platforms"),
                        ],
                        default="games",
                        max_length=50,
                    ),
                ),
                ("find_filter", models.JSONField(blank=True, default=dict)),
                ("object_filter", models.JSONField(blank=True, default=dict)),
                ("ui_options", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filter_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "mode", "name"),
                        name="unique_user_mode_name_preset",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(
                condition=models.Q(("platform__isnull", True)),
                fields=("name", "year_released"),
                name="unique_platformless_game_name_year",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="game",
            unique_together={("name", "platform", "year_released")},
        ),
    ]
