# Generated by Django 6.0.7 on 2026-09-13 14:38

import datetime

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.fields
import django.db.models.functions.comparison
from django.db import migrations, models

import games.models
import timetracker.uuidv7


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerSession",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=django.db.models.fields.NOT_PROVIDED,
                        default=django.db.models.fields.NOT_PROVIDED,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timing_mode",
                    models.CharField(
                        choices=[
                            ("timed", "Timed"),
                            ("duration_only", "Duration only"),
                            ("corrected", "Corrected"),
                        ],
                        max_length=13,
                    ),
                ),
                ("started_at", models.DateTimeField(null=True)),
                ("started_at_zone", models.CharField(max_length=64, null=True)),
                ("ended_at", models.DateTimeField(null=True)),
                ("ended_at_zone", models.CharField(max_length=64, null=True)),
                ("stated_day", models.DateField(null=True)),
                ("stated_duration", models.DurationField(null=True)),
                ("day_zone", models.CharField(max_length=64, null=True)),
                (
                    "effective_day",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            models.F("stated_day"),
                            django.db.models.functions.comparison.Cast(
                                models.Func(
                                    models.F("day_zone"),
                                    models.F("started_at"),
                                    function="timezone",
                                ),
                                models.DateField(),
                            ),
                        ),
                        output_field=models.DateField(),
                    ),
                ),
                (
                    "effective_duration",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            models.F("stated_duration"),
                            django.db.models.expressions.CombinedExpression(
                                models.F("ended_at"), "-", models.F("started_at")
                            ),
                            models.Value(datetime.timedelta(0)),
                        ),
                        output_field=models.DurationField(),
                    ),
                ),
                (
                    "sort_instant",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            models.F("started_at"),
                            models.Func(
                                models.Value("UTC"),
                                games.models.NaiveTimestamp(models.F("stated_day")),
                                function="timezone",
                            ),
                        ),
                        output_field=models.DateTimeField(),
                    ),
                ),
                ("note", models.TextField()),
                ("emulated", models.BooleanField()),
                ("created_at", models.DateTimeField(editable=False)),
                (
                    "removed_at",
                    models.DateTimeField(default=None, editable=False, null=True),
                ),
                (
                    "device",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="player_sessions",
                        to="games.device",
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="games.userlibrary",
                    ),
                ),
                (
                    "playthrough",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sessions",
                        to="games.playthrough",
                    ),
                ),
            ],
            options={
                "get_latest_by": "sort_instant",
                "indexes": [
                    models.Index(
                        fields=["library", "effective_day", "id"],
                        name="playersession_day_order",
                    ),
                    models.Index(
                        fields=["library", "sort_instant", "id"],
                        name="playersession_sort_order",
                    ),
                    models.Index(
                        fields=["playthrough", "effective_day"],
                        name="playersession_run_day",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("timing_mode__in", ("timed", "duration_only", "corrected"))
                        ),
                        name="playersession_timing_mode_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("timing_mode", "timed"), _negated=True),
                            models.Q(
                                ("day_zone__isnull", False),
                                ("started_at__isnull", False),
                                ("stated_day__isnull", True),
                                ("stated_duration__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="playersession_timed_columns",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("timing_mode", "duration_only"), _negated=True),
                            models.Q(
                                ("day_zone__isnull", True),
                                ("ended_at__isnull", True),
                                ("ended_at_zone__isnull", True),
                                ("started_at__isnull", True),
                                ("started_at_zone__isnull", True),
                                ("stated_day__isnull", False),
                                ("stated_duration__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="playersession_duration_only_columns",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("timing_mode", "corrected"), _negated=True),
                            models.Q(
                                ("day_zone__isnull", False),
                                ("ended_at__isnull", False),
                                ("started_at__isnull", False),
                                ("stated_day__isnull", True),
                                ("stated_duration__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="playersession_corrected_columns",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ended_at__isnull", True),
                            ("ended_at__gte", models.F("started_at")),
                            _connector="OR",
                        ),
                        name="playersession_end_after_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("stated_duration__isnull", True),
                            ("stated_duration__gte", datetime.timedelta(0)),
                            _connector="OR",
                        ),
                        name="playersession_duration_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("started_at_zone__isnull", True),
                                ("started_at__isnull", False),
                                _connector="OR",
                            ),
                            models.Q(
                                ("ended_at_zone__isnull", True),
                                ("ended_at__isnull", False),
                                _connector="OR",
                            ),
                        ),
                        name="playersession_zone_needs_its_instant",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("started_at_zone", ""), _negated=True),
                            models.Q(("ended_at_zone", ""), _negated=True),
                        ),
                        name="playersession_zone_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("effective_day__isnull", False)),
                        name="playersession_effective_day_stated",
                    ),
                ],
            },
        ),
    ]
