# Generated by Django 5.1.5 on 2025-01-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='price_per_game',
            field=models.FloatField(null=True),
        ),
    ]
