# Generated by Django 6.0.7 on 2026-09-14 16:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_playersession"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="playtime",
        ),
    ]
