# Generated by Django 4.1.4 on 2023-01-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_alter_session_duration_manual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="duration_manual",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="timestamp_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
