# Generated by Django 6.0.7 on 2026-09-15 07:52

import django.db.models.deletion
import django.db.models.fields
from django.db import migrations, models

import timetracker.uuidv7


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0004_playersession_conversion"),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryCalendar",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=django.db.models.fields.NOT_PROVIDED,
                        default=django.db.models.fields.NOT_PROVIDED,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("day_zone", models.CharField(max_length=64)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="games.userlibrary",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("library",),
                        name="games_librarycalendar_one_per_library",
                    )
                ],
            },
        ),
    ]
