# Generated by Django 4.1.5 on 2023-01-19 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_auto_20230109_1904"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="games.game"
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="platform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="games.platform"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="games.purchase"
            ),
        ),
    ]
