# Generated by Django 6.0.7 on 2026-09-16 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_squashed_0006_remove_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="mastered",
        ),
        migrations.RemoveField(
            model_name="game",
            name="status",
        ),
    ]
