# Generated by Django 6.0.7 on 2026-09-28 15:33

import datetime
import uuid

import django.db.models.deletion
import django.db.models.fields
from django.conf import settings
from django.db import migrations, models

import timetracker.temporal
import timetracker.uuidv7


class Migration(migrations.Migration):
    replaces = [
        ("games", "0007_remove_game_status_and_mastered"),
        ("games", "0008_projection_library_identity"),
        ("games", "0009_historical_playtime"),
        ("games", "0010_alter_filterpreset_mode"),
        ("games", "0011_historicalplaytime_reclassified_from"),
        ("games", "0012_library_event_batch_indexes"),
        ("games", "0013_list_column_choice"),
        ("games", "0014_device_projection"),
        ("games", "0015_device_conversion"),
        ("games", "0016_default_device_key"),
        ("games", "0017_batch_change"),
        ("games", "0018_platform_icon_glyphs"),
    ]

    dependencies = [
        ("games", "0001_squashed_0006_remove_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="mastered",
        ),
        migrations.RemoveField(
            model_name="game",
            name="status",
        ),
        migrations.AddConstraint(
            model_name="librarycalendar",
            constraint=models.UniqueConstraint(
                fields=("id", "library"),
                name="unique_games_librarycalendar_library_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="playergame",
            constraint=models.UniqueConstraint(
                fields=("id", "library"),
                name="unique_games_playergame_library_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="playersession",
            constraint=models.UniqueConstraint(
                fields=("id", "library"),
                name="unique_games_playersession_library_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="playthrough",
            constraint=models.UniqueConstraint(
                fields=("id", "library"),
                name="unique_games_playthrough_library_identity",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalPlaytime",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=django.db.models.fields.NOT_PROVIDED,
                        default=django.db.models.fields.NOT_PROVIDED,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("duration", models.DurationField()),
                (
                    "when",
                    timetracker.temporal.TemporalValueField(
                        blank=False,
                        default=django.db.models.fields.NOT_PROVIDED,
                        editable=False,
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "when_lower",
                    models.GeneratedField(
                        db_persist=True,
                        expression=timetracker.temporal.TemporalLowerBound("when"),
                        null=True,
                        output_field=models.DateField(null=True),
                        serialize=False,
                    ),
                ),
                (
                    "when_upper",
                    models.GeneratedField(
                        db_persist=True,
                        expression=timetracker.temporal.TemporalUpperBound("when"),
                        null=True,
                        output_field=models.DateField(null=True),
                        serialize=False,
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("estimated", "Estimated"),
                            ("manually_entered", "Manually entered"),
                            ("externally_measured", "Externally measured"),
                        ],
                        max_length=19,
                    ),
                ),
                ("emulated", models.BooleanField()),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(editable=False)),
                (
                    "removed_at",
                    models.DateTimeField(default=None, editable=False, null=True),
                ),
                (
                    "device",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="historical_playtime",
                        to="games.device",
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="games.userlibrary",
                    ),
                ),
                (
                    "player_game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="historical_playtime",
                        to="games.playergame",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalPlaytimeRun",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=django.db.models.fields.NOT_PROVIDED,
                        default=django.db.models.fields.NOT_PROVIDED,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="games.userlibrary",
                    ),
                ),
                (
                    "playthrough",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="historical_playtime_runs",
                        to="games.playthrough",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="runs",
                        to="games.historicalplaytime",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="historicalplaytime",
            index=models.Index(
                fields=["library", "when_lower", "id"],
                name="historicalplaytime_when_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalplaytime",
            constraint=models.UniqueConstraint(
                fields=("id", "library"),
                name="unique_games_historicalplaytime_library_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalplaytime",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration__gt", datetime.timedelta(0))),
                name="historicalplaytime_duration_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalplaytime",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "provenance__in",
                        ["estimated", "manually_entered", "externally_measured"],
                    )
                ),
                name="historicalplaytime_provenance_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalplaytimerun",
            constraint=models.UniqueConstraint(
                fields=("id", "library"),
                name="unique_games_historicalplaytimerun_library_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalplaytimerun",
            constraint=models.UniqueConstraint(
                fields=("record", "playthrough"),
                name="historicalplaytimerun_once_per_record",
            ),
        ),
        migrations.AlterField(
            model_name="filterpreset",
            name="mode",
            field=models.CharField(
                choices=[
                    ("games", "Games"),
                    ("sessions", "Sessions"),
                    ("purchases", "Purchases"),
                    ("playthroughs", "Playthroughs"),
                    ("historical_playtime", "Historical playtime"),
                    ("devices", "Devices"),
                    ("platforms", "Platforms"),
                ],
                default="games",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="historicalplaytime",
            name="restated_at",
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="historicalplaytime",
            name="reclassified_from",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="reclassified_records",
                to="games.playersession",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalplaytime",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("reclassified_from__isnull", False), ("removed_at__isnull", True)
                ),
                fields=("reclassified_from",),
                name="historicalplaytime_one_live_per_session",
            ),
        ),
        migrations.AddIndex(
            model_name="libraryevent",
            index=models.Index(
                fields=["library", "correlation_id"], name="library_event_batch"
            ),
        ),
        migrations.AddIndex(
            model_name="libraryevent",
            index=models.Index(
                fields=["library", "aggregate_id"], name="library_event_aggregate"
            ),
        ),
        migrations.CreateModel(
            name="ListColumnChoice",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=timetracker.uuidv7.PostgreSQLUUIDv7(),
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("games", "Games"),
                            ("sessions", "Sessions"),
                            ("purchases", "Purchases"),
                            ("playthroughs", "Playthroughs"),
                            ("historical_playtime", "Historical playtime"),
                            ("devices", "Devices"),
                            ("platforms", "Platforms"),
                        ],
                        max_length=50,
                    ),
                ),
                ("shown", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_column_choices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "mode"),
                        name="unique_list_column_choice_per_mode",
                    )
                ],
            },
        ),
        migrations.AlterField(
            model_name="device",
            name="created_at",
            field=models.DateTimeField(editable=False),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE games_device ALTER COLUMN id DROP DEFAULT",
                    reverse_sql="ALTER TABLE games_device ALTER COLUMN id SET DEFAULT uuidv7()",
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="device",
                    name="id",
                    field=timetracker.uuidv7.UUIDv7Field(
                        db_default=django.db.models.fields.NOT_PROVIDED,
                        default=django.db.models.fields.NOT_PROVIDED,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="device",
            name="library",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="games.userlibrary",
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                fields=("id", "library"), name="unique_games_device_library_identity"
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="\nDO $$\nDECLARE found record;\nBEGIN\n    FOR found IN\n        SELECT con.conname\n        FROM pg_constraint con\n        JOIN pg_attribute att\n          ON att.attrelid = con.conrelid AND att.attnum = ANY (con.conkey)\n        WHERE con.conrelid = 'games_userlibrarypreferences'::regclass\n          AND con.contype = 'f'\n          AND att.attname = 'default_device_id'\n    LOOP\n        EXECUTE format(\n            'ALTER TABLE games_userlibrarypreferences DROP CONSTRAINT %I',\n            found.conname\n        );\n    END LOOP;\n    FOR found IN\n        SELECT index_class.relname\n        FROM pg_index idx\n        JOIN pg_class index_class ON index_class.oid = idx.indexrelid\n        JOIN pg_attribute att\n          ON att.attrelid = idx.indrelid AND att.attnum = ANY (idx.indkey)\n        WHERE idx.indrelid = 'games_userlibrarypreferences'::regclass\n          AND NOT idx.indisprimary\n          AND att.attname = 'default_device_id'\n    LOOP\n        EXECUTE format('DROP INDEX %I', found.relname);\n    END LOOP;\nEND $$;\n",
                    reverse_sql="\nCREATE INDEX games_userlibrarypreferences_default_device_id\n    ON games_userlibrarypreferences (default_device_id);\nALTER TABLE games_userlibrarypreferences\n    ADD CONSTRAINT games_userlibrarypreferences_default_device_id_fk\n    FOREIGN KEY (default_device_id) REFERENCES games_device (id)\n    DEFERRABLE INITIALLY DEFERRED;\n",
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="userlibrarypreferences",
                    name="default_device",
                ),
                migrations.AddField(
                    model_name="userlibrarypreferences",
                    name="default_device_id",
                    field=models.UUIDField(blank=True, default=None, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="platform",
            name="icon",
            field=models.SlugField(default="unspecified"),
        ),
        migrations.CreateModel(
            name="BatchChange",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=timetracker.uuidv7.PostgreSQLUUIDv7(),
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("batch", models.UUIDField()),
                ("act", models.CharField(max_length=100)),
                ("model_label", models.CharField(max_length=100)),
                ("row_id", models.UUIDField()),
                ("field", models.CharField(max_length=100)),
                ("earlier", models.JSONField(null=True)),
                ("stated", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="games.userlibrary",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["library", "batch"],
                        name="games_batch_library_30649e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("library", "batch", "model_label", "row_id", "field"),
                        name="unique_batch_change_per_field",
                    )
                ],
            },
        ),
    ]
