# Generated by Django 6.0.7 on 2026-09-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_game_status_and_mastered'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='librarycalendar',
            constraint=models.UniqueConstraint(fields=('id', 'library'), name='unique_games_librarycalendar_library_identity'),
        ),
        migrations.AddConstraint(
            model_name='playergame',
            constraint=models.UniqueConstraint(fields=('id', 'library'), name='unique_games_playergame_library_identity'),
        ),
        migrations.AddConstraint(
            model_name='playersession',
            constraint=models.UniqueConstraint(fields=('id', 'library'), name='unique_games_playersession_library_identity'),
        ),
        migrations.AddConstraint(
            model_name='playthrough',
            constraint=models.UniqueConstraint(fields=('id', 'library'), name='unique_games_playthrough_library_identity'),
        ),
    ]
