# Generated by Django 6.0.7 on 2026-09-17 09:31

import datetime

import django.db.models.deletion
import django.db.models.fields
from django.db import migrations, models

import timetracker.temporal
import timetracker.uuidv7


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0008_projection_library_identity"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPlaytime",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=django.db.models.fields.NOT_PROVIDED,
                        default=django.db.models.fields.NOT_PROVIDED,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("duration", models.DurationField()),
                (
                    "when",
                    timetracker.temporal.TemporalValueField(
                        blank=False,
                        default=django.db.models.fields.NOT_PROVIDED,
                        editable=False,
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "when_lower",
                    models.GeneratedField(
                        db_persist=True,
                        expression=timetracker.temporal.TemporalLowerBound("when"),
                        null=True,
                        output_field=models.DateField(null=True),
                        serialize=False,
                    ),
                ),
                (
                    "when_upper",
                    models.GeneratedField(
                        db_persist=True,
                        expression=timetracker.temporal.TemporalUpperBound("when"),
                        null=True,
                        output_field=models.DateField(null=True),
                        serialize=False,
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("estimated", "Estimated"),
                            ("manually_entered", "Manually entered"),
                            ("externally_measured", "Externally measured"),
                        ],
                        max_length=19,
                    ),
                ),
                ("emulated", models.BooleanField()),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(editable=False)),
                (
                    "removed_at",
                    models.DateTimeField(default=None, editable=False, null=True),
                ),
                (
                    "device",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="historical_playtime",
                        to="games.device",
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="games.userlibrary",
                    ),
                ),
                (
                    "player_game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="historical_playtime",
                        to="games.playergame",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalPlaytimeRun",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=django.db.models.fields.NOT_PROVIDED,
                        default=django.db.models.fields.NOT_PROVIDED,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="games.userlibrary",
                    ),
                ),
                (
                    "playthrough",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="historical_playtime_runs",
                        to="games.playthrough",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="runs",
                        to="games.historicalplaytime",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="historicalplaytime",
            index=models.Index(
                fields=["library", "when_lower", "id"],
                name="historicalplaytime_when_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalplaytime",
            constraint=models.UniqueConstraint(
                fields=("id", "library"),
                name="unique_games_historicalplaytime_library_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalplaytime",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration__gt", datetime.timedelta(0))),
                name="historicalplaytime_duration_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalplaytime",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "provenance__in",
                        ["estimated", "manually_entered", "externally_measured"],
                    )
                ),
                name="historicalplaytime_provenance_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalplaytimerun",
            constraint=models.UniqueConstraint(
                fields=("id", "library"),
                name="unique_games_historicalplaytimerun_library_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalplaytimerun",
            constraint=models.UniqueConstraint(
                fields=("record", "playthrough"),
                name="historicalplaytimerun_once_per_record",
            ),
        ),
    ]
