# Generated by Django 5.1.7 on 2025-03-20 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0008_game_original_year_released_gamestatuschange_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="date_dropped",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="date_finished",
        ),
    ]
