# Generated by Django 6.0.7 on 2026-09-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0009_historical_playtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filterpreset",
            name="mode",
            field=models.CharField(
                choices=[
                    ("games", "Games"),
                    ("sessions", "Sessions"),
                    ("purchases", "Purchases"),
                    ("playthroughs", "Playthroughs"),
                    ("historical_playtime", "Historical playtime"),
                    ("devices", "Devices"),
                    ("platforms", "Platforms"),
                ],
                default="games",
                max_length=50,
            ),
        ),
    ]
