# Generated by Django 5.1.7 on 2025-03-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_remove_purchase_date_dropped_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='price_per_game',
        ),
    ]
