# Generated by Django 4.1.5 on 2023-02-18 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0010_alter_purchase_game"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchase",
            old_name="game",
            new_name="edition",
        ),
    ]
