# Generated by Django 6.0.7 on 2026-09-18 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0010_alter_filterpreset_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="playersession",
            name="reclassified_into",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="reclassified_sessions",
                to="games.historicalplaytime",
            ),
        ),
    ]
