# Generated by Django 6.0.7 on 2026-09-20 05:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0011_historicalplaytime_reclassified_from"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="libraryevent",
            index=models.Index(
                fields=["library", "correlation_id"], name="library_event_batch"
            ),
        ),
        migrations.AddIndex(
            model_name="libraryevent",
            index=models.Index(
                fields=["library", "aggregate_id"], name="library_event_aggregate"
            ),
        ),
    ]
