# Generated by Django 4.1.5 on 2023-02-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0011_rename_game_purchase_edition"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="purchase",
            name="price_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
    ]
