# Generated by Django 4.1.5 on 2023-02-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0012_purchase_price_purchase_price_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="ownership_type",
            field=models.CharField(
                choices=[
                    ("ph", "Physical"),
                    ("di", "Digital"),
                    ("du", "Digital Upgrade"),
                    ("re", "Rented"),
                    ("bo", "Borrowed"),
                    ("tr", "Trial"),
                    ("de", "Demo"),
                    ("pi", "Pirated"),
                ],
                default="di",
                max_length=2,
            ),
        ),
    ]
