# Generated by Django 6.0.7 on 2026-09-22 15:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import timetracker.uuidv7


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0012_library_event_batch_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListColumnChoice",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=timetracker.uuidv7.PostgreSQLUUIDv7(),
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("games", "Games"),
                            ("sessions", "Sessions"),
                            ("purchases", "Purchases"),
                            ("playthroughs", "Playthroughs"),
                            ("historical_playtime", "Historical playtime"),
                            ("devices", "Devices"),
                            ("platforms", "Platforms"),
                        ],
                        max_length=50,
                    ),
                ),
                ("hidden", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_column_choices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "mode"),
                        name="unique_list_column_choice_per_mode",
                    )
                ],
            },
        ),
    ]
