# Generated by Django 5.1.7 on 2025-03-25 20:46

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_game_playtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='duration_total',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('duration_calculated'), '+', models.F('duration_manual')), output_field=models.DurationField()),
        ),
    ]
