from django.db import migrations

from timetracker.uuidv7 import UUIDv7Field

PROMOTED_TABLES = (
    ("session", "games_session"),
    ("playevent", "games_playevent"),
    ("gamestatuschange", "games_gamestatuschange"),
)


def promote_state(model_name):
    return [
        migrations.RemoveField(model_name=model_name, name="id"),
        migrations.RemoveField(model_name=model_name, name="uuid"),
        migrations.AddField(
            model_name=model_name,
            name="id",
            field=UUIDv7Field(
                primary_key=True,
                editable=False,
                serialize=False,
            ),
        ),
    ]


def _drop_redundant_unique_constraint(cursor, table_name):
    cursor.execute(
        """
        SELECT conname FROM pg_constraint
        WHERE conrelid = %s::regclass AND contype = 'u'
          AND pg_get_constraintdef(oid) = 'UNIQUE (id)'
        """,
        [table_name],
    )
    for (constraint_name,) in cursor.fetchall():
        cursor.execute(
            f'ALTER TABLE "{table_name}" DROP CONSTRAINT "{constraint_name}"'
        )


def promote_playhistory_identities(apps, schema_editor):
    del apps
    row_counts = {}
    with schema_editor.connection.cursor() as cursor:
        for _model_name, table_name in PROMOTED_TABLES:
            cursor.execute(f'SELECT count(*) FROM "{table_name}"')
            (row_counts[table_name],) = cursor.fetchone()

            cursor.execute(f'ALTER TABLE "{table_name}" DROP COLUMN id')
            cursor.execute(f'ALTER TABLE "{table_name}" RENAME COLUMN uuid TO id')
            cursor.execute(f'ALTER TABLE "{table_name}" ADD PRIMARY KEY (id)')
            _drop_redundant_unique_constraint(cursor, table_name)

            cursor.execute(f'SELECT count(*) FROM "{table_name}"')
            (rows_after,) = cursor.fetchone()
            if rows_after != row_counts[table_name]:
                raise RuntimeError(
                    f"{table_name} row count changed during identity promotion: "
                    f"{row_counts[table_name]} != {rows_after}"
                )

    print(
        "SES identity promoted "
        f"session_rows={row_counts['games_session']} "
        f"playevent_rows={row_counts['games_playevent']} "
        f"gamestatuschange_rows={row_counts['games_gamestatuschange']}"
    )


def lock_promoted_tables(cursor):
    tables = ", ".join(f'"{table_name}"' for _model_name, table_name in PROMOTED_TABLES)
    cursor.execute(f"LOCK TABLE {tables} IN ACCESS EXCLUSIVE MODE")


def restore_empty_playhistory(apps, schema_editor):
    del apps
    with schema_editor.connection.cursor() as cursor:
        lock_promoted_tables(cursor)
        cursor.execute(
            "SELECT (SELECT count(*) FROM games_session), "
            "(SELECT count(*) FROM games_playevent), "
            "(SELECT count(*) FROM games_gamestatuschange)"
        )
        sessions, playevents, status_changes = cursor.fetchone()
        if sessions or playevents or status_changes:
            raise RuntimeError(
                "Cannot reverse the Session/play-history identity promotion: "
                "the original integer identities are gone and "
                f"{sessions} session(s), {playevents} play event(s), and "
                f"{status_changes} game status change(s) would need invented "
                "replacements. Restore from a backup taken before this "
                "migration instead."
            )

        for _model_name, table_name in PROMOTED_TABLES:
            cursor.execute(f'ALTER TABLE "{table_name}" RENAME COLUMN id TO uuid')
            cursor.execute(
                f'ALTER TABLE "{table_name}" DROP CONSTRAINT "{table_name}_pkey"'
            )
            cursor.execute(f'ALTER TABLE "{table_name}" ADD UNIQUE (uuid)')
            cursor.execute(
                f'ALTER TABLE "{table_name}" ADD COLUMN id bigint '
                "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            )


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0013_catalog_uuid_primary_key"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                operation
                for model_name, _table_name in PROMOTED_TABLES
                for operation in promote_state(model_name)
            ],
            database_operations=[],
        ),
        migrations.RunPython(
            promote_playhistory_identities,
            restore_empty_playhistory,
        ),
    ]
