# Generated by Django 4.1.5 on 2023-02-18 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0013_purchase_ownership_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("pc", "PC"),
                            ("co", "Console"),
                            ("ha", "Handheld"),
                            ("mo", "Mobile"),
                            ("sbc", "Single-board computer"),
                        ],
                        default="pc",
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="session",
            name="device",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="games.device",
            ),
        ),
    ]
