# Generated by Django 4.1.5 on 2023-02-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0014_device_session_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="wikidata",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="edition",
            name="year_released",
            field=models.IntegerField(default=2023),
        ),
    ]
