# Generated by Django 4.1.5 on 2023-11-06 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0015_edition_wikidata_edition_year_released"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edition",
            name="platform",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="games.platform",
            ),
        ),
        migrations.AlterField(
            model_name="edition",
            name="year_released",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="wikidata",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="platform",
            name="group",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="device",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="games.device",
            ),
        ),
    ]
