# Generated by Django 6.0.1 on 2026-05-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_alter_purchase_date_purchased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='needs_price_update',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.RunSQL(
            "UPDATE games_purchase SET needs_price_update = FALSE WHERE converted_price IS NOT NULL AND converted_currency != ''",
            reverse_sql="UPDATE games_purchase SET needs_price_update = TRUE WHERE converted_price IS NOT NULL AND converted_currency != ''",
        ),
    ]
