# Generated by Django 6.0.7 on 2026-09-28 09:20

import uuid

import django.db.models.deletion
from django.db import migrations, models

import timetracker.uuidv7


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0016_default_device_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchChange",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=timetracker.uuidv7.PostgreSQLUUIDv7(),
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("batch", models.UUIDField()),
                ("act", models.CharField(max_length=100)),
                ("model_label", models.CharField(max_length=100)),
                ("row_id", models.UUIDField()),
                ("field", models.CharField(max_length=100)),
                ("earlier", models.JSONField(null=True)),
                ("stated", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_changes",
                        to="games.userlibrary",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["library", "batch"],
                        name="games_batch_library_30649e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "model_label", "row_id", "field"),
                        name="unique_batch_change_per_field",
                    )
                ],
            },
        ),
    ]
