# Generated by Django 6.0.7 on 2026-09-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0016_default_device_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="removed_in_batch",
            field=models.UUIDField(blank=True, default=None, editable=False, null=True),
        ),
    ]
