# Generated by Django 6.0.1 on 2026-06-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0017_add_filter_preset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="timestamp_start",
            field=models.DateTimeField(db_index=True, verbose_name="Start"),
        ),
    ]
