# Generated by Django 6.0.7 on 2026-10-03 08:03

import uuid

import django.db.models.deletion
import django.db.models.fields
from django.db import migrations, models

import timetracker.temporal
import timetracker.uuidv7

REMEDY = (
    "A deployment migrates with the image before the squash first; "
    "a development database is dropped and rebuilt."
)

#: Rows each elided pass converted, at 0018.
UNCONVERTED = (
    ("games_purchase", "legacy purchases", "SELECT 1 FROM games_purchase"),
    (
        "games_exchangerate",
        "float rates; they are a cache, so deleting them also works",
        "SELECT 1 FROM games_exchangerate",
    ),
    (
        "games_filterpreset",
        "presets in the legacy purchase words",
        (
            "SELECT 1 FROM games_filterpreset WHERE mode = 'purchases' "
            "OR object_filter::text LIKE '%purchase%'"
        ),
    ),
)

RETIRED_TASK = "games.tasks.calculate_price_per_game"


def refuse_unconverted_data(apps, schema_editor):
    """Refuse rows the elided passes converted."""
    with schema_editor.connection.cursor() as cursor:
        for table, rows, query in UNCONVERTED:
            cursor.execute(f"SELECT EXISTS ({query})")
            if cursor.fetchone()[0]:
                raise RuntimeError(
                    f"{table} holds {rows}, which this squash cannot convert. {REMEDY}"
                )


def remove_retired_schedule(apps, schema_editor):
    """The retired task's lingering schedule row."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DELETE FROM django_q_schedule WHERE func = %s", [RETIRED_TASK])


class Migration(migrations.Migration):
    replaces = [
        ("games", "0019_device_access_end"),
        ("games", "0020_libraryentry"),
        ("games", "0021_libraryentry_access_end"),
        ("games", "0022_entry_way_unstated"),
        ("games", "0023_entries_mode"),
        ("games", "0024_game_kind_parent_edition_kind"),
        ("games", "0025_playergame_excluded_from_dropped"),
        ("games", "0026_rename_purchase_legacypurchase"),
        ("games", "0027_purchase"),
        ("games", "0028_purchase_refund"),
        ("games", "0029_exchangerate_decimal_rate"),
        ("games", "0030_purchasevaluation"),
        ("games", "0031_purchase_conversion"),
        ("games", "0032_purchase_presets"),
        ("games", "0033_legacy_purchase_reverse"),
        ("games", "0034_conversion_review_hidden"),
        ("games", "0035_delete_legacypurchase"),
        ("games", "0036_defer_library_event_stream_matches_library"),
    ]

    dependencies = [
        ("django_q", "0019_alter_task_options_alter_ormq_key_alter_ormq_lock_and_more"),
        (
            "games",
            "0007_remove_game_status_and_mastered_squashed_0018_platform_icon_glyphs",
        ),
    ]

    operations = [
        migrations.RunPython(
            refuse_unconverted_data, migrations.RunPython.noop, elidable=True
        ),
        migrations.RunPython(
            remove_retired_schedule, migrations.RunPython.noop, elidable=True
        ),
        migrations.AddField(
            model_name="device",
            name="access_end_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="device",
            name="access_end_recorded_at",
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="access_end_way",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sold", "Sold"),
                    ("lost", "Lost"),
                    ("given_away", "Given away"),
                    ("broken", "Broken"),
                    ("stolen", "Stolen"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="access_ended",
            field=timetracker.temporal.TemporalValueField(
                blank=False, default=None, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "access_end_way__in",
                        ["sold", "lost", "given_away", "broken", "stolen", ""],
                    )
                ),
                name="games_device_access_end_way_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("access_end_recorded_at__isnull", True), ("access_end_way", "")
                    ),
                    models.Q(
                        models.Q(("access_end_way", ""), _negated=True),
                        ("access_end_recorded_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="games_device_access_end_way_with_marker",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="access_ended_lower",
            field=models.GeneratedField(
                db_persist=True,
                expression=timetracker.temporal.TemporalLowerBound("access_ended"),
                null=True,
                output_field=models.DateField(null=True),
                serialize=False,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="access_ended_upper",
            field=models.GeneratedField(
                db_persist=True,
                expression=timetracker.temporal.TemporalUpperBound("access_ended"),
                null=True,
                output_field=models.DateField(null=True),
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="LibraryEntry",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=django.db.models.fields.NOT_PROVIDED,
                        default=django.db.models.fields.NOT_PROVIDED,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("owned", "Owned"),
                            ("borrowed", "Borrowed"),
                            ("rented", "Rented"),
                            ("subscription", "Subscription"),
                            ("trial", "Trial"),
                            ("demo", "Demo"),
                            ("pirated", "Pirated"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("physical", "Physical"),
                            ("digital", "Digital"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "acquired",
                    timetracker.temporal.TemporalValueField(
                        blank=False,
                        default=None,
                        editable=False,
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "acquired_lower",
                    models.GeneratedField(
                        db_persist=True,
                        expression=timetracker.temporal.TemporalLowerBound("acquired"),
                        null=True,
                        output_field=models.DateField(null=True),
                        serialize=False,
                    ),
                ),
                (
                    "acquired_upper",
                    models.GeneratedField(
                        db_persist=True,
                        expression=timetracker.temporal.TemporalUpperBound("acquired"),
                        null=True,
                        output_field=models.DateField(null=True),
                        serialize=False,
                    ),
                ),
                ("acquisition_recorded_at", models.DateTimeField(editable=False)),
                ("acquisition_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(editable=False)),
                (
                    "removed_at",
                    models.DateTimeField(default=None, editable=False, null=True),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="games.userlibrary",
                    ),
                ),
                (
                    "player_game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="entries",
                        to="games.playergame",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="games.release",
                    ),
                ),
                ("access_end_note", models.TextField(blank=True, default="")),
                (
                    "access_end_recorded_at",
                    models.DateTimeField(default=None, editable=False, null=True),
                ),
                (
                    "access_end_way",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unstated", "Not said"),
                            ("returned", "Returned"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                            ("refunded", "Refunded"),
                            ("sold", "Sold"),
                            ("lost", "Lost"),
                            ("given_away", "Given away"),
                            ("broken", "Broken"),
                            ("stolen", "Stolen"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "access_ended",
                    timetracker.temporal.TemporalValueField(
                        blank=False,
                        default=None,
                        editable=False,
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "access_ended_lower",
                    models.GeneratedField(
                        db_persist=True,
                        expression=timetracker.temporal.TemporalLowerBound(
                            "access_ended"
                        ),
                        null=True,
                        output_field=models.DateField(null=True),
                        serialize=False,
                    ),
                ),
                (
                    "access_ended_upper",
                    models.GeneratedField(
                        db_persist=True,
                        expression=timetracker.temporal.TemporalUpperBound(
                            "access_ended"
                        ),
                        null=True,
                        output_field=models.DateField(null=True),
                        serialize=False,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        condition=models.Q(("removed_at__isnull", True)),
                        fields=["library", "release"],
                        name="live_entry_per_release_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("id", "library"),
                        name="unique_games_libraryentry_library_identity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "access__in",
                                [
                                    "owned",
                                    "borrowed",
                                    "rented",
                                    "subscription",
                                    "trial",
                                    "demo",
                                    "pirated",
                                ],
                            )
                        ),
                        name="games_libraryentry_access_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("format__in", ["physical", "digital", "unknown"])
                        ),
                        name="games_libraryentry_format_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("access_end_recorded_at__isnull", True),
                                ("access_end_way", ""),
                            ),
                            models.Q(
                                models.Q(("access_end_way", ""), _negated=True),
                                ("access_end_recorded_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="games_libraryentry_access_end_way_with_marker",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "access_end_way__in",
                                [
                                    "unstated",
                                    "returned",
                                    "expired",
                                    "revoked",
                                    "refunded",
                                    "sold",
                                    "lost",
                                    "given_away",
                                    "broken",
                                    "stolen",
                                    "",
                                ],
                            )
                        ),
                        name="games_libraryentry_access_end_way_known",
                    ),
                ],
                "verbose_name": "copy",
                "verbose_name_plural": "copies",
            },
        ),
        migrations.AlterField(
            model_name="filterpreset",
            name="mode",
            field=models.CharField(
                choices=[
                    ("games", "Games"),
                    ("sessions", "Sessions"),
                    ("purchases", "Purchases"),
                    ("playthroughs", "Playthroughs"),
                    ("historical_playtime", "Historical playtime"),
                    ("devices", "Devices"),
                    ("platforms", "Platforms"),
                    ("entries", "Library"),
                ],
                default="games",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="listcolumnchoice",
            name="mode",
            field=models.CharField(
                choices=[
                    ("games", "Games"),
                    ("sessions", "Sessions"),
                    ("purchases", "Purchases"),
                    ("playthroughs", "Playthroughs"),
                    ("historical_playtime", "Historical playtime"),
                    ("devices", "Devices"),
                    ("platforms", "Platforms"),
                    ("entries", "Library"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="edition",
            name="kind",
            field=models.CharField(
                choices=[("full", "Full"), ("prerelease", "Prerelease")],
                default="full",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="kind",
            field=models.CharField(
                choices=[
                    ("main", "Main game"),
                    ("dlc", "DLC"),
                    ("expansion", "Expansion"),
                    ("standalone_expansion", "Standalone expansion"),
                ],
                default="main",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="games.game",
            ),
        ),
        migrations.AddConstraint(
            model_name="edition",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["full", "prerelease"])),
                name="edition_kind_word",
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind__in", ["main", "dlc", "expansion", "standalone_expansion"])
                ),
                name="game_kind_word",
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "main"), ("parent__isnull", True)),
                    models.Q(
                        models.Q(("kind", "main"), _negated=True),
                        ("parent__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="game_parent_exactly_for_addons",
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("id")), _negated=True),
                name="game_not_its_own_parent",
            ),
        ),
        migrations.AddField(
            model_name="playergame",
            name="excluded_from_dropped",
            field=models.BooleanField(default=False),
        ),
        migrations.RenameModel(
            old_name="Purchase",
            new_name="LegacyPurchase",
        ),
        migrations.AlterModelOptions(
            name="legacypurchase",
            options={"verbose_name": "purchase", "verbose_name_plural": "purchases"},
        ),
        migrations.RunSQL(
            sql="\nDO $$\nDECLARE\n    found record;\n    new_name text;\nBEGIN\n    FOR found IN\n        SELECT index_class.relname AS name\n        FROM pg_index\n        JOIN pg_class index_class ON index_class.oid = pg_index.indexrelid\n        JOIN pg_class table_class ON table_class.oid = pg_index.indrelid\n        WHERE table_class.relname IN ('games_legacypurchase', 'games_legacypurchase_games')\n          AND index_class.relname LIKE 'games_purchase\\_%'\n    LOOP\n        new_name := 'games_legacypurchase' || substr(found.name, length('games_purchase') + 1);\n        IF length(new_name) > 63 THEN\n            RAISE EXCEPTION 'Index % would be truncated as %.', found.name, new_name;\n        END IF;\n        EXECUTE format('ALTER INDEX %I RENAME TO %I', found.name, new_name);\n    END LOOP;\n    FOR found IN\n        SELECT pg_constraint.conname AS name, table_class.relname AS owner\n        FROM pg_constraint\n        JOIN pg_class table_class ON table_class.oid = pg_constraint.conrelid\n        WHERE table_class.relname IN ('games_legacypurchase', 'games_legacypurchase_games')\n          AND pg_constraint.conname LIKE 'games_purchase\\_%'\n    LOOP\n        -- Cut to 63, as PostgreSQL would; refuse a clash.\n        new_name := left('games_legacypurchase' || substr(found.name, length('games_purchase') + 1), 63);\n        IF EXISTS (\n            SELECT 1 FROM pg_constraint\n            JOIN pg_class owner_class ON owner_class.oid = pg_constraint.conrelid\n            WHERE owner_class.relname = found.owner\n              AND pg_constraint.conname = new_name\n        ) THEN\n            RAISE EXCEPTION 'Constraint % would become %, which exists.',\n                found.name, new_name;\n        END IF;\n        EXECUTE format(\n            'ALTER TABLE %I RENAME CONSTRAINT %I TO %I',\n            found.owner,\n            found.name,\n            new_name\n        );\n    END LOOP;\nEND\n$$;\n",
            reverse_sql="\nDO $$\nDECLARE\n    found record;\n    new_name text;\nBEGIN\n    FOR found IN\n        SELECT index_class.relname AS name\n        FROM pg_index\n        JOIN pg_class index_class ON index_class.oid = pg_index.indexrelid\n        JOIN pg_class table_class ON table_class.oid = pg_index.indrelid\n        WHERE table_class.relname IN ('games_legacypurchase', 'games_legacypurchase_games')\n          AND index_class.relname LIKE 'games_legacypurchase\\_%'\n    LOOP\n        new_name := 'games_purchase' || substr(found.name, length('games_legacypurchase') + 1);\n        IF length(new_name) > 63 THEN\n            RAISE EXCEPTION 'Index % would be truncated as %.', found.name, new_name;\n        END IF;\n        EXECUTE format('ALTER INDEX %I RENAME TO %I', found.name, new_name);\n    END LOOP;\n    FOR found IN\n        SELECT pg_constraint.conname AS name, table_class.relname AS owner\n        FROM pg_constraint\n        JOIN pg_class table_class ON table_class.oid = pg_constraint.conrelid\n        WHERE table_class.relname IN ('games_legacypurchase', 'games_legacypurchase_games')\n          AND pg_constraint.conname LIKE 'games_legacypurchase\\_%'\n    LOOP\n        -- Cut to 63, as PostgreSQL would; refuse a clash.\n        new_name := left('games_purchase' || substr(found.name, length('games_legacypurchase') + 1), 63);\n        IF EXISTS (\n            SELECT 1 FROM pg_constraint\n            JOIN pg_class owner_class ON owner_class.oid = pg_constraint.conrelid\n            WHERE owner_class.relname = found.owner\n              AND pg_constraint.conname = new_name\n        ) THEN\n            RAISE EXCEPTION 'Constraint % would become %, which exists.',\n                found.name, new_name;\n        END IF;\n        EXECUTE format(\n            'ALTER TABLE %I RENAME CONSTRAINT %I TO %I',\n            found.owner,\n            found.name,\n            new_name\n        );\n    END LOOP;\nEND\n$$;\n",
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=django.db.models.fields.NOT_PROVIDED,
                        default=django.db.models.fields.NOT_PROVIDED,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("game", "Game"),
                            ("season_pass", "Season pass"),
                            ("battle_pass", "Battle pass"),
                            ("upgrade", "Upgrade"),
                        ],
                        max_length=11,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, default="", max_length=3)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "purchased",
                    timetracker.temporal.TemporalValueField(
                        blank=False,
                        default=None,
                        editable=False,
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "purchased_lower",
                    models.GeneratedField(
                        db_persist=True,
                        expression=timetracker.temporal.TemporalLowerBound("purchased"),
                        null=True,
                        output_field=models.DateField(null=True),
                        serialize=False,
                    ),
                ),
                (
                    "purchased_upper",
                    models.GeneratedField(
                        db_persist=True,
                        expression=timetracker.temporal.TemporalUpperBound("purchased"),
                        null=True,
                        output_field=models.DateField(null=True),
                        serialize=False,
                    ),
                ),
                ("purchase_recorded_at", models.DateTimeField(editable=False)),
                ("purchase_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(editable=False)),
                (
                    "removed_at",
                    models.DateTimeField(default=None, editable=False, null=True),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="purchases",
                        to="games.libraryentry",
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="games.userlibrary",
                    ),
                ),
                ("refund_note", models.TextField(blank=True, default="")),
                (
                    "refund_recorded_at",
                    models.DateTimeField(default=None, editable=False, null=True),
                ),
                (
                    "refunded",
                    timetracker.temporal.TemporalValueField(
                        blank=False,
                        default=None,
                        editable=False,
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "refunded_lower",
                    models.GeneratedField(
                        db_persist=True,
                        expression=timetracker.temporal.TemporalLowerBound("refunded"),
                        null=True,
                        output_field=models.DateField(null=True),
                        serialize=False,
                    ),
                ),
                (
                    "refunded_upper",
                    models.GeneratedField(
                        db_persist=True,
                        expression=timetracker.temporal.TemporalUpperBound("refunded"),
                        null=True,
                        output_field=models.DateField(null=True),
                        serialize=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "purchase",
                "verbose_name_plural": "purchases",
                "indexes": [
                    models.Index(
                        condition=models.Q(("removed_at__isnull", True)),
                        fields=["library", "entry"],
                        name="live_purchase_per_entry_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("id", "library"),
                        name="unique_games_purchase_library_identity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "kind__in",
                                ["game", "season_pass", "battle_pass", "upgrade"],
                            )
                        ),
                        name="games_purchase_kind_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("amount__isnull", True),
                            ("amount__gte", 0),
                            _connector="OR",
                        ),
                        name="games_purchase_amount_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("amount__isnull", True), ("currency", "")),
                            models.Q(
                                ("amount__isnull", False),
                                ("currency__regex", "^[A-Z]{3}$"),
                            ),
                            _connector="OR",
                        ),
                        name="games_purchase_currency_where_amount",
                    ),
                ],
            },
        ),
        migrations.RemoveField(
            model_name="exchangerate",
            name="rate",
        ),
        migrations.AddField(
            model_name="exchangerate",
            name="rate",
            field=models.DecimalField(decimal_places=12, max_digits=24),
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.CheckConstraint(
                condition=models.Q(("rate__gt", 0)),
                name="games_exchangerate_rate_positive",
            ),
        ),
        migrations.CreateModel(
            name="PurchaseValuation",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=timetracker.uuidv7.PostgreSQLUUIDv7(),
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("purchase_id", models.UUIDField()),
                ("target_currency", models.CharField(max_length=3)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=26)),
                ("source_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("source_currency", models.CharField(max_length=3)),
                ("rate_year", models.PositiveSmallIntegerField()),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=12, default=None, max_digits=24, null=True
                    ),
                ),
                ("version", models.PositiveBigIntegerField()),
                ("calculated_at", models.DateTimeField()),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="games.userlibrary",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("library", "purchase_id"),
                        name="games_purchasevaluation_one_per_purchase",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("amount__gte", 0), ("source_amount__gte", 0)
                        ),
                        name="games_purchasevaluation_amounts_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("amount", models.F("source_amount")),
                                ("rate__isnull", True),
                                models.Q(
                                    ("source_currency", models.F("target_currency")),
                                    ("source_amount", 0),
                                    _connector="OR",
                                ),
                            ),
                            models.Q(
                                ("rate__gt", 0),
                                ("rate__isnull", False),
                                models.Q(
                                    ("source_currency", models.F("target_currency")),
                                    _negated=True,
                                ),
                                models.Q(("source_amount", 0), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="games_purchasevaluation_rate_where_needed",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source_currency__regex", "^[A-Z]{3}$"),
                            ("target_currency__regex", "^[A-Z]{3}$"),
                        ),
                        name="games_purchasevaluation_currency_codes",
                    ),
                ],
            },
        ),
        migrations.AlterField(
            model_name="legacypurchase",
            name="library",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="games.userlibrary",
            ),
        ),
        migrations.AlterField(
            model_name="legacypurchase",
            name="games",
            field=models.ManyToManyField(related_name="+", to="games.game"),
        ),
        migrations.AlterField(
            model_name="legacypurchase",
            name="platform",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="games.platform",
            ),
        ),
        migrations.AlterField(
            model_name="legacypurchase",
            name="related_game",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="games.game",
                verbose_name="Base game",
            ),
        ),
        migrations.AddField(
            model_name="userlibrarypreferences",
            name="conversion_review_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="LegacyPurchase",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE games_libraryevent\n    ALTER CONSTRAINT library_event_stream_matches_library\n    DEFERRABLE INITIALLY DEFERRED;",
            reverse_sql="ALTER TABLE games_libraryevent\n    ALTER CONSTRAINT library_event_stream_matches_library\n    NOT DEFERRABLE;",
        ),
    ]
