# Generated by Django 6.0.7 on 2026-08-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0018_catalog_hierarchy"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="is_default",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="release",
            name="is_default",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddConstraint(
            model_name="edition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("game",),
                name="unique_default_edition_per_game",
            ),
        ),
        migrations.AddConstraint(
            model_name="release",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("edition",),
                name="unique_default_release_per_edition",
            ),
        ),
    ]
