# Generated by Django 6.0.5 on 2026-06-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0018_alter_session_timestamp_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filterpreset",
            name="mode",
            field=models.CharField(
                choices=[
                    ("games", "Games"),
                    ("sessions", "Sessions"),
                    ("purchases", "Purchases"),
                    ("playevents", "Play Events"),
                    ("devices", "Devices"),
                    ("platforms", "Platforms"),
                ],
                default="games",
                max_length=50,
            ),
        ),
    ]
