# Generated by Django 4.1.5 on 2023-11-06 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0018_auto_20231106_1825"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="edition",
            unique_together={("name", "platform")},
        ),
    ]
