# Generated by Django 6.0.7 on 2026-09-28 16:22

from django.db import migrations, models

import timetracker.temporal


class Migration(migrations.Migration):
    dependencies = [
        (
            "games",
            "0007_remove_game_status_and_mastered_squashed_0018_platform_icon_glyphs",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="access_end_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="device",
            name="access_end_recorded_at",
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="access_end_way",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sold", "Sold"),
                    ("lost", "Lost"),
                    ("given_away", "Given away"),
                    ("broken", "Broken"),
                    ("stolen", "Stolen"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="access_ended",
            field=timetracker.temporal.TemporalValueField(
                blank=False, default=None, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "access_end_way__in",
                        ["sold", "lost", "given_away", "broken", "stolen", ""],
                    )
                ),
                name="games_device_access_end_way_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("access_end_recorded_at__isnull", True), ("access_end_way", "")
                    ),
                    models.Q(
                        models.Q(("access_end_way", ""), _negated=True),
                        ("access_end_recorded_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="games_device_access_end_way_with_marker",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="access_ended_lower",
            field=models.GeneratedField(
                db_persist=True,
                expression=timetracker.temporal.TemporalLowerBound("access_ended"),
                null=True,
                output_field=models.DateField(null=True),
                serialize=False,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="access_ended_upper",
            field=models.GeneratedField(
                db_persist=True,
                expression=timetracker.temporal.TemporalUpperBound("access_ended"),
                null=True,
                output_field=models.DateField(null=True),
                serialize=False,
            ),
        ),
    ]
