# Generated by Django 6.0.7 on 2026-09-29 08:48

import django.db.models.deletion
import django.db.models.fields
from django.db import migrations, models

import timetracker.temporal
import timetracker.uuidv7


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0019_device_access_end"),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryEntry",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=django.db.models.fields.NOT_PROVIDED,
                        default=django.db.models.fields.NOT_PROVIDED,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("owned", "Owned"),
                            ("borrowed", "Borrowed"),
                            ("rented", "Rented"),
                            ("subscription", "Subscription"),
                            ("trial", "Trial"),
                            ("demo", "Demo"),
                            ("pirated", "Pirated"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("physical", "Physical"),
                            ("digital", "Digital"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "acquired",
                    timetracker.temporal.TemporalValueField(
                        blank=False,
                        default=None,
                        editable=False,
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "acquired_lower",
                    models.GeneratedField(
                        db_persist=True,
                        expression=timetracker.temporal.TemporalLowerBound("acquired"),
                        null=True,
                        output_field=models.DateField(null=True),
                        serialize=False,
                    ),
                ),
                (
                    "acquired_upper",
                    models.GeneratedField(
                        db_persist=True,
                        expression=timetracker.temporal.TemporalUpperBound("acquired"),
                        null=True,
                        output_field=models.DateField(null=True),
                        serialize=False,
                    ),
                ),
                ("acquisition_recorded_at", models.DateTimeField(editable=False)),
                ("acquisition_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(editable=False)),
                (
                    "removed_at",
                    models.DateTimeField(default=None, editable=False, null=True),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="games.userlibrary",
                    ),
                ),
                (
                    "player_game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="entries",
                        to="games.playergame",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="games.release",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        condition=models.Q(("removed_at__isnull", True)),
                        fields=["library", "release"],
                        name="live_entry_per_release_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("id", "library"),
                        name="unique_games_libraryentry_library_identity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "access__in",
                                [
                                    "owned",
                                    "borrowed",
                                    "rented",
                                    "subscription",
                                    "trial",
                                    "demo",
                                    "pirated",
                                ],
                            )
                        ),
                        name="games_libraryentry_access_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("format__in", ["physical", "digital", "unknown"])
                        ),
                        name="games_libraryentry_format_known",
                    ),
                ],
            },
        ),
    ]
