# Generated by Django 4.1.5 on 2023-11-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0019_alter_edition_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="year",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
