# Generated by Django 6.0.7 on 2026-09-29 10:05

import timetracker.temporal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0020_libraryentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryentry",
            name="access_end_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="libraryentry",
            name="access_end_recorded_at",
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="libraryentry",
            name="access_end_way",
            field=models.CharField(
                blank=True,
                choices=[
                    ("returned", "Returned"),
                    ("expired", "Expired"),
                    ("revoked", "Revoked"),
                    ("refunded", "Refunded"),
                    ("sold", "Sold"),
                    ("lost", "Lost"),
                    ("given_away", "Given away"),
                    ("broken", "Broken"),
                    ("stolen", "Stolen"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="libraryentry",
            name="access_ended",
            field=timetracker.temporal.TemporalValueField(
                blank=False, default=None, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="libraryentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "access_end_way__in",
                        [
                            "returned",
                            "expired",
                            "revoked",
                            "refunded",
                            "sold",
                            "lost",
                            "given_away",
                            "broken",
                            "stolen",
                            "",
                        ],
                    )
                ),
                name="games_libraryentry_access_end_way_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="libraryentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("access_end_recorded_at__isnull", True), ("access_end_way", "")
                    ),
                    models.Q(
                        models.Q(("access_end_way", ""), _negated=True),
                        ("access_end_recorded_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="games_libraryentry_access_end_way_with_marker",
            ),
        ),
        migrations.AddField(
            model_name="libraryentry",
            name="access_ended_lower",
            field=models.GeneratedField(
                db_persist=True,
                expression=timetracker.temporal.TemporalLowerBound("access_ended"),
                null=True,
                output_field=models.DateField(null=True),
                serialize=False,
            ),
        ),
        migrations.AddField(
            model_name="libraryentry",
            name="access_ended_upper",
            field=models.GeneratedField(
                db_persist=True,
                expression=timetracker.temporal.TemporalUpperBound("access_ended"),
                null=True,
                output_field=models.DateField(null=True),
                serialize=False,
            ),
        ),
    ]
