# Generated by Django 6.0.7 on 2026-08-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("games", "0020_catalog_hierarchy_backfill")]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="library",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="games.userlibrary",
            ),
        ),
    ]
