# Generated by Django 6.0.7 on 2026-08-20

import json
import re
from collections import defaultdict

import django.db.models.deletion
from django.db import migrations, models

import timetracker.uuidv7

MACHINE_PREFIX = "EXTERNAL_REFERENCE_RECONCILIATION_JSON="
HUMAN_PREFIX = "CAT external reference reconciliation:"
MISMATCH_PREFIX = "CAT external reference mismatch:"
BATCH_SIZE = 1000
WIKIDATA_PATTERN = re.compile(r"Q[1-9][0-9]*")
PRESERVED_GAME_FIELDS = (
    "library_id",
    "name",
    "sort_name",
    "original_year_released",
    "year_released",
    "original_release_date",
    "platform_id",
    "status",
    "mastered",
    "playtime",
    "created_at",
    "updated_at",
)
SUMMARY_KEYS = (
    "games",
    "legacy_nonblank",
    "legacy_blank",
    "normalized_legacy_values",
    "inserted_references",
    "wikidata_references",
    "wikidata_game_references",
    "wikidata_edition_references",
    "wikidata_release_references",
    "wikidata_platform_references",
    "mismatches",
)


def _json_value(value):
    if value is None or isinstance(value, (str, int, float, bool)):
        return value
    serialize = getattr(value, "serialize", None)
    if serialize is not None:
        return serialize()
    return str(value)


def _human_value(value):
    if value is None:
        return "null"
    if isinstance(value, (list, tuple, dict)):
        return json.dumps(value, sort_keys=True, separators=(",", ":"))
    return str(value)


def _normalize_wikidata(value):
    return value.strip().upper()


def _game_snapshot(Game):
    snapshot = {}
    rows = Game.objects.order_by("pk").values(
        "pk",
        "wikidata",
        *PRESERVED_GAME_FIELDS,
    )
    for row in rows:
        game_id = str(row.pop("pk"))
        snapshot[game_id] = {key: _json_value(value) for key, value in row.items()}
    return snapshot


def _expected_legacy(snapshot):
    return {
        game_id: _normalize_wikidata(row["wikidata"])
        for game_id, row in snapshot.items()
    }


def _preflight_mismatches(snapshot, expected_legacy):
    mismatches = []
    key_games = defaultdict(list)
    for game_id in sorted(snapshot):
        original = snapshot[game_id]["wikidata"]
        provider_key = expected_legacy[game_id]
        if not provider_key:
            continue
        if WIKIDATA_PATTERN.fullmatch(provider_key) is None:
            mismatches.append(
                {
                    "code": "malformed_wikidata",
                    "game_id": game_id,
                    "field": "wikidata",
                    "expected": "Q[1-9][0-9]* or blank",
                    "actual": original,
                }
            )
            continue
        key_games[provider_key].append(game_id)

    for provider_key, game_ids in sorted(key_games.items()):
        if len(game_ids) > 1:
            mismatches.append(
                {
                    "code": "duplicate_normalized_wikidata",
                    "provider_key": provider_key,
                    "game_ids": sorted(game_ids),
                }
            )
    return mismatches


def _canonicalize_legacy_games(Game, expected_legacy):
    changed = []
    for game in Game.objects.order_by("pk"):
        canonical = expected_legacy[str(game.pk)]
        if game.wikidata != canonical:
            game.wikidata = canonical
            changed.append(game)
    if changed:
        Game.objects.bulk_update(changed, ["wikidata"], batch_size=BATCH_SIZE)


def _ensure_wikidata_game_references(apps, expected_legacy):
    ExternalReference = apps.get_model("games", "ExternalReference")
    existing = {
        (provider, entity_kind, provider_key): game_id
        for provider, entity_kind, provider_key, game_id in ExternalReference.objects.filter(
            provider="wikidata",
            entity_kind="game",
        ).values_list("provider", "entity_kind", "provider_key", "game_id")
    }
    new_references = []
    for game_id in sorted(expected_legacy):
        provider_key = expected_legacy[game_id]
        if not provider_key:
            continue
        key = ("wikidata", "game", provider_key)
        if key in existing:
            continue
        new_references.append(
            ExternalReference(
                provider="wikidata",
                entity_kind="game",
                provider_key=provider_key,
                game_id=game_id,
            )
        )
    if new_references:
        ExternalReference.objects.bulk_create(
            new_references,
            batch_size=BATCH_SIZE,
        )
    return len(new_references)


def _reference_rows(apps):
    ExternalReference = apps.get_model("games", "ExternalReference")
    rows = ExternalReference.objects.order_by(
        "provider",
        "entity_kind",
        "provider_key",
        "pk",
    ).values_list(
        "pk",
        "provider",
        "entity_kind",
        "provider_key",
        "game_id",
        "edition_id",
        "release_id",
        "platform_id",
    )
    return tuple(tuple(_json_value(value) for value in row) for row in rows)


def _result_mismatches(
    apps,
    before_snapshot,
    expected_legacy,
    first_reference_rows,
    second_reference_rows,
    second_insert_count,
):
    Game = apps.get_model("games", "Game")
    ExternalReference = apps.get_model("games", "ExternalReference")
    mismatches = []
    current_snapshot = _game_snapshot(Game)
    before_ids = set(before_snapshot)
    current_ids = set(current_snapshot)

    for game_id in sorted(before_ids - current_ids):
        mismatches.append({"code": "missing_game", "game_id": game_id})
    for game_id in sorted(current_ids - before_ids):
        mismatches.append({"code": "extra_game", "game_id": game_id})
    for game_id in sorted(before_ids & current_ids):
        before = before_snapshot[game_id]
        current = current_snapshot[game_id]
        for field in PRESERVED_GAME_FIELDS:
            if before[field] != current[field]:
                mismatches.append(
                    {
                        "code": "preserved_game_field_changed",
                        "game_id": game_id,
                        "field": field,
                        "expected": before[field],
                        "actual": current[field],
                    }
                )
        if current["wikidata"] != expected_legacy[game_id]:
            mismatches.append(
                {
                    "code": "legacy_wikidata_mismatch",
                    "game_id": game_id,
                    "field": "wikidata",
                    "expected": expected_legacy[game_id],
                    "actual": current["wikidata"],
                }
            )

    references = list(
        ExternalReference.objects.filter(provider="wikidata")
        .order_by("entity_kind", "provider_key", "pk")
        .values(
            "pk",
            "entity_kind",
            "provider_key",
            "game_id",
            "edition_id",
            "release_id",
            "platform_id",
        )
    )
    expected_tuples = {
        (provider_key, game_id)
        for game_id, provider_key in expected_legacy.items()
        if provider_key
    }
    game_references_by_key = defaultdict(list)
    for reference in references:
        reference_id = str(reference["pk"])
        entity_kind = reference["entity_kind"]
        provider_key = reference["provider_key"]
        target_values = {
            "game": reference["game_id"],
            "edition": reference["edition_id"],
            "release": reference["release_id"],
            "platform": reference["platform_id"],
        }
        populated_targets = [
            kind for kind, target_id in target_values.items() if target_id is not None
        ]
        if populated_targets != [entity_kind]:
            mismatches.append(
                {
                    "code": "reference_target_kind_violation",
                    "provider_key": provider_key,
                    "entity_kind": entity_kind,
                    "reference_id": reference_id,
                    "expected": entity_kind,
                    "actual": populated_targets,
                }
            )
        if entity_kind == "game":
            game_id = _json_value(reference["game_id"])
            game_references_by_key[provider_key].append((reference_id, game_id))
            if game_id in expected_legacy and not expected_legacy[game_id]:
                mismatches.append(
                    {
                        "code": "blank_game_reference",
                        "provider_key": provider_key,
                        "game_id": game_id,
                        "reference_id": reference_id,
                    }
                )
            if (provider_key, game_id) not in expected_tuples:
                mismatches.append(
                    {
                        "code": "extra_game_reference",
                        "provider_key": provider_key,
                        "game_id": game_id,
                        "reference_id": reference_id,
                    }
                )

    for game_id in sorted(expected_legacy):
        provider_key = expected_legacy[game_id]
        if not provider_key:
            continue
        matches = game_references_by_key.get(provider_key, [])
        if not matches:
            mismatches.append(
                {
                    "code": "missing_game_reference",
                    "provider_key": provider_key,
                    "game_id": game_id,
                    "expected": game_id,
                    "actual": None,
                }
            )
        elif matches[0][1] != game_id:
            mismatches.append(
                {
                    "code": "wrong_game_reference_target",
                    "provider_key": provider_key,
                    "game_id": game_id,
                    "reference_id": matches[0][0],
                    "expected": game_id,
                    "actual": matches[0][1],
                }
            )

    expected_nonblank_count = sum(bool(value) for value in expected_legacy.values())
    game_reference_count = sum(
        reference["entity_kind"] == "game" for reference in references
    )
    if game_reference_count != expected_nonblank_count:
        mismatches.append(
            {
                "code": "legacy_reference_count_mismatch",
                "entity_kind": "game",
                "expected": expected_nonblank_count,
                "actual": game_reference_count,
            }
        )

    if second_insert_count != 0 or first_reference_rows != second_reference_rows:
        mismatches.append(
            {
                "code": "non_idempotent_reference_ensure",
                "expected": {
                    "inserted_references": 0,
                    "reference_rows": first_reference_rows,
                },
                "actual": {
                    "inserted_references": second_insert_count,
                    "reference_rows": second_reference_rows,
                },
            }
        )
    return mismatches


def _summary(apps, snapshot, inserted_references, mismatch_count):
    Game = apps.get_model("games", "Game")
    ExternalReference = apps.get_model("games", "ExternalReference")
    values = tuple(row["wikidata"] for row in snapshot.values())
    wikidata_references = ExternalReference.objects.filter(provider="wikidata")
    return {
        "games": Game.objects.count(),
        "legacy_nonblank": sum(bool(_normalize_wikidata(value)) for value in values),
        "legacy_blank": sum(not _normalize_wikidata(value) for value in values),
        "normalized_legacy_values": sum(
            value != _normalize_wikidata(value) for value in values
        ),
        "inserted_references": inserted_references,
        "wikidata_references": wikidata_references.count(),
        "wikidata_game_references": wikidata_references.filter(
            entity_kind="game"
        ).count(),
        "wikidata_edition_references": wikidata_references.filter(
            entity_kind="edition"
        ).count(),
        "wikidata_release_references": wikidata_references.filter(
            entity_kind="release"
        ).count(),
        "wikidata_platform_references": wikidata_references.filter(
            entity_kind="platform"
        ).count(),
        "mismatches": mismatch_count,
    }


def _mismatch_sort_key(mismatch):
    primary = tuple(
        str(mismatch.get(key) or "")
        for key in (
            "code",
            "provider_key",
            "game_id",
            "entity_kind",
            "expected",
            "actual",
        )
    )
    return primary + (json.dumps(mismatch, sort_keys=True, default=str),)


def _emit(summary, mismatches):
    mismatches = sorted(mismatches, key=_mismatch_sort_key)
    payload = {
        "schema_version": 1,
        "summary": summary,
        "mismatches": mismatches,
    }
    print(MACHINE_PREFIX + json.dumps(payload, sort_keys=True, separators=(",", ":")))
    print(
        HUMAN_PREFIX + " " + " ".join(f"{key}={summary[key]}" for key in SUMMARY_KEYS)
    )
    for mismatch in mismatches:
        details = " ".join(
            f"{key}={_human_value(value)}"
            for key, value in sorted(mismatch.items())
            if key != "code"
        )
        print(
            f"{MISMATCH_PREFIX} code={mismatch['code']}"
            + (f" {details}" if details else "")
        )


def _fail_if_mismatched(mismatches):
    if mismatches:
        raise RuntimeError(
            "CAT external reference reconciliation failed with "
            f"{len(mismatches)} mismatch(es)."
        )


def backfill_external_references(apps, schema_editor):
    del schema_editor
    Game = apps.get_model("games", "Game")
    before_snapshot = _game_snapshot(Game)
    expected_legacy = _expected_legacy(before_snapshot)
    mismatches = _preflight_mismatches(before_snapshot, expected_legacy)
    if mismatches:
        summary = _summary(apps, before_snapshot, 0, len(mismatches))
        _emit(summary, mismatches)
        _fail_if_mismatched(mismatches)

    _canonicalize_legacy_games(Game, expected_legacy)
    inserted_references = _ensure_wikidata_game_references(apps, expected_legacy)
    first_reference_rows = _reference_rows(apps)
    second_insert_count = _ensure_wikidata_game_references(apps, expected_legacy)
    second_reference_rows = _reference_rows(apps)
    mismatches = _result_mismatches(
        apps,
        before_snapshot,
        expected_legacy,
        first_reference_rows,
        second_reference_rows,
        second_insert_count,
    )
    summary = _summary(
        apps,
        before_snapshot,
        inserted_references,
        len(mismatches),
    )
    _emit(summary, mismatches)
    _fail_if_mismatched(mismatches)


def reverse_external_references(apps, schema_editor):
    del schema_editor
    ExternalReference = apps.get_model("games", "ExternalReference")
    if ExternalReference.objects.exists():
        raise RuntimeError(
            "Cannot reverse external references while reference rows exist."
        )


class Migration(migrations.Migration):
    dependencies = [("games", "0021_alter_game_library")]

    operations = [
        migrations.CreateModel(
            name="ExternalReference",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                ("entity_kind", models.CharField(max_length=20)),
                ("provider_key", models.CharField(max_length=255)),
                (
                    "edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_references",
                        to="games.edition",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_references",
                        to="games.game",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_references",
                        to="games.platform",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_references",
                        to="games.release",
                    ),
                ),
            ],
            options={
                "constraints": (
                    models.UniqueConstraint(
                        fields=("provider", "entity_kind", "provider_key"),
                        name="unique_external_reference_provider_kind_key",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ("edition__isnull", True),
                                ("entity_kind", "game"),
                                ("game__isnull", False),
                                ("platform__isnull", True),
                                ("release__isnull", True),
                            )
                            | models.Q(
                                ("edition__isnull", False),
                                ("entity_kind", "edition"),
                                ("game__isnull", True),
                                ("platform__isnull", True),
                                ("release__isnull", True),
                            )
                            | models.Q(
                                ("edition__isnull", True),
                                ("entity_kind", "release"),
                                ("game__isnull", True),
                                ("platform__isnull", True),
                                ("release__isnull", False),
                            )
                            | models.Q(
                                ("edition__isnull", True),
                                ("entity_kind", "platform"),
                                ("game__isnull", True),
                                ("platform__isnull", False),
                                ("release__isnull", True),
                            )
                        ),
                        name="external_reference_kind_matches_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("provider", "wikidata")),
                        name="external_reference_supported_provider",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("provider_key__regex", "^Q[1-9][0-9]*$")),
                        name="external_reference_canonical_provider_key",
                    ),
                ),
            },
        ),
        migrations.RunPython(
            backfill_external_references,
            reverse_external_references,
        ),
    ]
