# Generated by Django 6.0.7 on 2026-09-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0021_libraryentry_access_end"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="libraryentry",
            name="games_libraryentry_access_end_way_known",
        ),
        migrations.AlterField(
            model_name="libraryentry",
            name="access_end_way",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unstated", "Not said"),
                    ("returned", "Returned"),
                    ("expired", "Expired"),
                    ("revoked", "Revoked"),
                    ("refunded", "Refunded"),
                    ("sold", "Sold"),
                    ("lost", "Lost"),
                    ("given_away", "Given away"),
                    ("broken", "Broken"),
                    ("stolen", "Stolen"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="libraryentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "access_end_way__in",
                        [
                            "unstated",
                            "returned",
                            "expired",
                            "revoked",
                            "refunded",
                            "sold",
                            "lost",
                            "given_away",
                            "broken",
                            "stolen",
                            "",
                        ],
                    )
                ),
                name="games_libraryentry_access_end_way_known",
            ),
        ),
    ]
