# Generated by Django 6.0.7 on 2026-08-20

import django.db.models.deletion
from django.db import migrations, models

import timetracker.uuidv7


class Migration(migrations.Migration):
    dependencies = [("games", "0021_alter_game_library")]

    operations = [
        migrations.CreateModel(
            name="ExternalReference",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                ("entity_kind", models.CharField(max_length=20)),
                ("provider_key", models.CharField(max_length=255)),
                (
                    "edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_references",
                        to="games.edition",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_references",
                        to="games.game",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_references",
                        to="games.platform",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_references",
                        to="games.release",
                    ),
                ),
            ],
            options={
                "constraints": (
                    models.UniqueConstraint(
                        fields=("provider", "entity_kind", "provider_key"),
                        name="unique_external_reference_provider_kind_key",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ("edition__isnull", True),
                                ("entity_kind", "game"),
                                ("game__isnull", False),
                                ("platform__isnull", True),
                                ("release__isnull", True),
                            )
                            | models.Q(
                                ("edition__isnull", False),
                                ("entity_kind", "edition"),
                                ("game__isnull", True),
                                ("platform__isnull", True),
                                ("release__isnull", True),
                            )
                            | models.Q(
                                ("edition__isnull", True),
                                ("entity_kind", "release"),
                                ("game__isnull", True),
                                ("platform__isnull", True),
                                ("release__isnull", False),
                            )
                            | models.Q(
                                ("edition__isnull", True),
                                ("entity_kind", "platform"),
                                ("game__isnull", True),
                                ("platform__isnull", False),
                                ("release__isnull", True),
                            )
                        ),
                        name="external_reference_kind_matches_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("provider", "wikidata")),
                        name="external_reference_supported_provider",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("provider_key__regex", "^Q[1-9][0-9]*$")),
                        name="external_reference_canonical_provider_key",
                    ),
                ),
            },
        ),
    ]
