# Generated by Django 6.0.6 on 2026-06-29 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0021_filterpreset_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="filterpreset",
            constraint=models.UniqueConstraint(
                fields=("user", "mode", "name"), name="unique_user_mode_name_preset"
            ),
        ),
    ]
