# Generated by Django 4.1.5 on 2023-11-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0021_auto_20231106_1909"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="year",
            new_name="year_released",
        ),
    ]
