# Generated by Django 6.0.7 on 2026-09-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0022_entry_way_unstated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="libraryentry",
            options={"verbose_name": "copy", "verbose_name_plural": "copies"},
        ),
        migrations.AlterField(
            model_name="filterpreset",
            name="mode",
            field=models.CharField(
                choices=[
                    ("games", "Games"),
                    ("sessions", "Sessions"),
                    ("purchases", "Purchases"),
                    ("playthroughs", "Playthroughs"),
                    ("historical_playtime", "Historical playtime"),
                    ("devices", "Devices"),
                    ("platforms", "Platforms"),
                    ("entries", "Library"),
                ],
                default="games",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="listcolumnchoice",
            name="mode",
            field=models.CharField(
                choices=[
                    ("games", "Games"),
                    ("sessions", "Sessions"),
                    ("purchases", "Purchases"),
                    ("playthroughs", "Playthroughs"),
                    ("historical_playtime", "Historical playtime"),
                    ("devices", "Devices"),
                    ("platforms", "Platforms"),
                    ("entries", "Library"),
                ],
                max_length=50,
            ),
        ),
    ]
