# Generated by Django 6.0.7 on 2026-08-21 11:33

import uuid

import django.db.models.deletion
import django.db.models.fields
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import timetracker.temporal
import timetracker.uuidv7

ADD_STREAM_OWNERSHIP_FOREIGN_KEY = """
ALTER TABLE games_libraryevent
    ADD CONSTRAINT library_event_stream_matches_library
    FOREIGN KEY (stream_id, library_id)
    REFERENCES games_libraryeventstreamhead (id, library_id);
""".strip()

DROP_STREAM_OWNERSHIP_FOREIGN_KEY = """
ALTER TABLE games_libraryevent
    DROP CONSTRAINT library_event_stream_matches_library;
""".strip()


def refuse_rollback_with_recorded_history(apps, schema_editor):
    """Reversing this migration drops the tables. Projections are rebuilt from
    the stream, so recorded events are the only copy of that history."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute("SELECT count(*) FROM games_libraryeventstreamhead")
        head_count = cursor.fetchone()[0]
        cursor.execute("SELECT count(*) FROM games_libraryevent")
        event_count = cursor.fetchone()[0]
    if head_count or event_count:
        raise RuntimeError(
            "Refusing to reverse 0023_library_event_schema: "
            f"{head_count} stream head(s) and {event_count} event(s) exist, "
            "and dropping these tables would discard that history permanently."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0022_external_references"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryEventStreamHead",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=timetracker.uuidv7.PostgreSQLUUIDv7(),
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("current_sequence", models.PositiveBigIntegerField(default=0)),
                (
                    "library",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_stream_head",
                        to="games.userlibrary",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LibraryEvent",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=timetracker.uuidv7.PostgreSQLUUIDv7(),
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveBigIntegerField()),
                ("event_type", models.CharField(max_length=255)),
                ("aggregate_type", models.CharField(max_length=100)),
                (
                    "aggregate_id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=django.db.models.fields.NOT_PROVIDED, default=None
                    ),
                ),
                ("payload_schema_version", models.PositiveIntegerField(default=1)),
                (
                    "recorded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "effective_time",
                    timetracker.temporal.TemporalValueField(
                        blank=False,
                        default=None,
                        editable=False,
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "correlation_id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=django.db.models.fields.NOT_PROVIDED, default=None
                    ),
                ),
                (
                    "causation_id",
                    timetracker.uuidv7.UUIDv7Field(
                        blank=True,
                        db_default=django.db.models.fields.NOT_PROVIDED,
                        default=None,
                        null=True,
                    ),
                ),
                ("source_metadata", models.JSONField(blank=True, default=dict)),
                ("idempotency_key", models.CharField(max_length=255)),
                ("payload", models.JSONField()),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="games.userlibrary",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="events",
                        to="games.libraryeventstreamhead",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="libraryeventstreamhead",
            constraint=models.UniqueConstraint(
                fields=("id", "library"),
                name="unique_library_event_stream_head_library_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="libraryevent",
            constraint=models.UniqueConstraint(
                fields=("stream", "sequence"),
                name="unique_library_event_stream_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="libraryevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gte", 1)),
                name="library_event_sequence_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="libraryevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("payload_schema_version__gte", 1)),
                name="library_event_payload_schema_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="libraryevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("event_type", ""), _negated=True),
                name="library_event_type_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="libraryevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("aggregate_type", ""), _negated=True),
                name="library_event_aggregate_type_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="libraryevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                name="library_event_idempotency_key_not_empty",
            ),
        ),
        migrations.RunSQL(
            sql=ADD_STREAM_OWNERSHIP_FOREIGN_KEY,
            reverse_sql=DROP_STREAM_OWNERSHIP_FOREIGN_KEY,
        ),
        # Last, so an attempted reversal hits the guard before anything drops.
        migrations.RunPython(
            migrations.RunPython.noop,
            refuse_rollback_with_recorded_history,
        ),
    ]
