# Generated by Django 4.1.5 on 2023-11-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "games",
            "0016_alter_edition_platform_alter_edition_year_released_and_more_squashed_0022_rename_year_game_year_released",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="date_finished",
            field=models.DateField(blank=True, null=True),
        ),
    ]
