# Generated by Django 6.0.7 on 2026-09-30 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0023_entries_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="kind",
            field=models.CharField(
                choices=[("full", "Full"), ("prerelease", "Prerelease")],
                default="full",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="kind",
            field=models.CharField(
                choices=[
                    ("main", "Main game"),
                    ("dlc", "DLC"),
                    ("expansion", "Expansion"),
                    ("standalone_expansion", "Standalone expansion"),
                ],
                default="main",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="games.game",
            ),
        ),
        migrations.AddConstraint(
            model_name="edition",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["full", "prerelease"])),
                name="edition_kind_word",
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind__in", ["main", "dlc", "expansion", "standalone_expansion"])
                ),
                name="game_kind_word",
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "main"), ("parent__isnull", True)),
                    models.Q(
                        models.Q(("kind", "main"), _negated=True),
                        ("parent__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="game_parent_exactly_for_addons",
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("id")), _negated=True),
                name="game_not_its_own_parent",
            ),
        ),
    ]
