# Generated by Django 6.0.7 on 2026-08-22 11:24

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import timetracker.uuidv7


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0023_library_event_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryIdempotencyRecord",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=timetracker.uuidv7.PostgreSQLUUIDv7(),
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("fingerprint_version", models.PositiveSmallIntegerField()),
                ("first_sequence", models.PositiveBigIntegerField()),
                ("last_sequence", models.PositiveBigIntegerField()),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idempotency_records",
                        to="games.userlibrary",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("library", "idempotency_key"),
                        name="unique_library_idempotency_key",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("first_sequence__gte", 1)),
                        name="library_idempotency_first_sequence_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("last_sequence__gte", models.F("first_sequence"))
                        ),
                        name="library_idempotency_range_ordered",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("idempotency_key", ""), _negated=True),
                        name="library_idempotency_key_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("request_fingerprint", ""), _negated=True),
                        name="library_idempotency_request_fingerprint_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("fingerprint_version__gte", 1)),
                        name="library_idempotency_fingerprint_version_positive",
                    ),
                ],
            },
        ),
    ]
