# Generated by Django 6.0.7 on 2026-09-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0023_entries_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="playergame",
            name="excluded_from_dropped",
            field=models.BooleanField(default=False),
        ),
    ]
