# Generated by Django 6.0.6 on 2026-07-03 17:33
#
# Runs after 0024 so the sentinel→NULL collapse happens first. If legacy data
# already holds platformless name+year twins (possible via loaddata/bulk
# writes, or a sentinel-platform twin of a leaked-NULL row collapsed by 0024),
# this migration fails loudly — resolve the duplicates manually and re-run.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0024_remove_sentinel_platform_and_device"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(
                condition=models.Q(("platform__isnull", True)),
                fields=("name", "year_released"),
                name="unique_platformless_game_name_year",
            ),
        ),
    ]
