# Generated by Django 6.0.7 on 2026-08-24 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0024_libraryidempotencyrecord"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="libraryevent",
            name="library_event_aggregate_type_not_empty",
        ),
        migrations.RemoveField(
            model_name="libraryevent",
            name="aggregate_type",
        ),
    ]
