# Generated by Django 6.0.6 on 2026-07-09 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0025_game_unique_platformless_game_name_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="related_game",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="addon_purchases",
                to="games.game",
                verbose_name="Base game",
            ),
        ),
    ]
