# Generated by Django 4.1.5 on 2023-11-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0025_game_sort_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="type",
            field=models.CharField(
                choices=[
                    ("game", "Game"),
                    ("dlc", "DLC"),
                    ("season_pass", "Season Pass"),
                    ("battle_pass", "Battle Pass"),
                ],
                default="game",
                max_length=255,
            ),
        ),
    ]
