# Generated by Django 6.0.7 on 2026-08-25 17:13

import uuid

import django.db.models.deletion
import django.db.models.fields
from django.db import migrations, models

import timetracker.uuidv7


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0025_drop_library_event_aggregate_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryEventReference",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=timetracker.uuidv7.PostgreSQLUUIDv7(),
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=255)),
                (
                    "referenced_id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=django.db.models.fields.NOT_PROVIDED, default=None
                    ),
                ),
                ("payload_key", models.CharField(max_length=255)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="games.libraryevent",
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_references",
                        to="games.userlibrary",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["kind", "referenced_id"],
                        name="games_libra_kind_d63eba_idx",
                    ),
                    models.Index(
                        fields=["library", "kind"],
                        name="games_libra_library_8b9f77_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind", ""), _negated=True),
                        name="library_event_reference_kind_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("payload_key", ""), _negated=True),
                        name="library_event_reference_payload_key_not_empty",
                    ),
                ],
            },
        ),
    ]
