# Generated by Django 6.0.7 on 2026-08-25 18:04

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0026_libraryeventreference"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="game",
            name="unique_library_platformless_game_name_year",
        ),
        migrations.RemoveConstraint(
            model_name="platform",
            name="unique_shared_platform_normalized_name_group",
        ),
        migrations.RemoveConstraint(
            model_name="platform",
            name="unique_private_platform_normalized_name_group",
        ),
        migrations.AlterUniqueTogether(
            name="game",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="device",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="platform",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True)),
                fields=("library", "name", "platform", "year_released"),
                name="unique_library_game_name_platform_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("platform__isnull", True), ("archived_at__isnull", True)
                ),
                fields=("library", "name", "year_released"),
                name="unique_library_platformless_game_name_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="platform",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("name")
                ),
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("group")
                ),
                condition=models.Q(
                    ("library__isnull", True), ("archived_at__isnull", True)
                ),
                name="unique_shared_platform_normalized_name_group",
            ),
        ),
        migrations.AddConstraint(
            model_name="platform",
            constraint=models.UniqueConstraint(
                models.F("library"),
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("name")
                ),
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("group")
                ),
                condition=models.Q(
                    ("library__isnull", False), ("archived_at__isnull", True)
                ),
                name="unique_private_platform_normalized_name_group",
            ),
        ),
    ]
