# Generated by Django 6.0.6 on 2026-07-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0026_alter_purchase_related_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="timestamp_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Session end"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="timestamp_start",
            field=models.DateTimeField(db_index=True, verbose_name="Session start"),
        ),
    ]
