# Generated by Django 4.1.5 on 2023-11-14 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0026_purchase_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="related_purchase",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="games.purchase",
            ),
        ),
    ]
