# Generated by Django 6.0.7 on 2026-10-01 07:24

import django.db.models.deletion
import django.db.models.fields
from django.db import migrations, models

import timetracker.temporal
import timetracker.uuidv7


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0026_rename_purchase_legacypurchase"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=django.db.models.fields.NOT_PROVIDED,
                        default=django.db.models.fields.NOT_PROVIDED,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("game", "Game"),
                            ("season_pass", "Season pass"),
                            ("battle_pass", "Battle pass"),
                            ("upgrade", "Upgrade"),
                        ],
                        max_length=11,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, default="", max_length=3)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "purchased",
                    timetracker.temporal.TemporalValueField(
                        blank=False,
                        default=None,
                        editable=False,
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "purchased_lower",
                    models.GeneratedField(
                        db_persist=True,
                        expression=timetracker.temporal.TemporalLowerBound("purchased"),
                        null=True,
                        output_field=models.DateField(null=True),
                        serialize=False,
                    ),
                ),
                (
                    "purchased_upper",
                    models.GeneratedField(
                        db_persist=True,
                        expression=timetracker.temporal.TemporalUpperBound("purchased"),
                        null=True,
                        output_field=models.DateField(null=True),
                        serialize=False,
                    ),
                ),
                ("purchase_recorded_at", models.DateTimeField(editable=False)),
                ("purchase_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(editable=False)),
                (
                    "removed_at",
                    models.DateTimeField(default=None, editable=False, null=True),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="purchases",
                        to="games.libraryentry",
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="games.userlibrary",
                    ),
                ),
            ],
            options={
                "verbose_name": "purchase",
                "verbose_name_plural": "purchases",
                "indexes": [
                    models.Index(
                        condition=models.Q(("removed_at__isnull", True)),
                        fields=["library", "entry"],
                        name="live_purchase_per_entry_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("id", "library"),
                        name="unique_games_purchase_library_identity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "kind__in",
                                ["game", "season_pass", "battle_pass", "upgrade"],
                            )
                        ),
                        name="games_purchase_kind_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("amount__isnull", True),
                            ("amount__gte", 0),
                            _connector="OR",
                        ),
                        name="games_purchase_amount_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("amount__isnull", True), ("currency", "")),
                            models.Q(
                                ("amount__isnull", False),
                                ("currency__regex", "^[A-Z]{3}$"),
                            ),
                            _connector="OR",
                        ),
                        name="games_purchase_currency_where_amount",
                    ),
                ],
            },
        ),
    ]
