# Generated by Django 6.0.7 on 2026-08-26 09:15

import django.db.models.deletion
import django.db.models.fields
from django.db import migrations, models

import timetracker.uuidv7


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0027_tombstone_catalog_rows"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerGame",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=django.db.models.fields.NOT_PROVIDED,
                        default=django.db.models.fields.NOT_PROVIDED,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tracked_at", models.DateTimeField(editable=False)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="player_games",
                        to="games.game",
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="games.userlibrary",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("library", "game"), name="unique_library_player_game"
                    )
                ],
            },
        ),
    ]
