# Generated by Django 6.0.7 on 2026-10-01 09:34

from django.db import migrations, models

import timetracker.temporal


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0027_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="refund_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="purchase",
            name="refund_recorded_at",
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="refunded",
            field=timetracker.temporal.TemporalValueField(
                blank=False, default=None, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="refunded_lower",
            field=models.GeneratedField(
                db_persist=True,
                expression=timetracker.temporal.TemporalLowerBound("refunded"),
                null=True,
                output_field=models.DateField(null=True),
                serialize=False,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="refunded_upper",
            field=models.GeneratedField(
                db_persist=True,
                expression=timetracker.temporal.TemporalUpperBound("refunded"),
                null=True,
                output_field=models.DateField(null=True),
                serialize=False,
            ),
        ),
    ]
