# Generated by Django 4.1.5 on 2023-11-14 11:05

from django.db import migrations, models
from games.models import Purchase


def null_game_name(apps, schema_editor):
    Purchase.objects.filter(type=Purchase.GAME).update(name=None)


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0027_purchase_related_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="name",
            field=models.CharField(
                blank=True, default="Unknown Name", max_length=255, null=True
            ),
        ),
        migrations.RunPython(null_game_name),
    ]
