# Generated by Django 6.0.6 on 2026-07-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0027_alter_session_timestamp_end_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.AlterField(
            model_name="purchase",
            name="price_currency",
            field=models.CharField(blank=True, default="", max_length=3),
        ),
    ]
