# Generated by Django 6.0.7 on 2026-08-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0028_playergame"),
    ]

    operations = [
        migrations.AddField(
            model_name="playergame",
            name="status",
            field=models.CharField(
                choices=[
                    ("unplayed", "Unplayed"),
                    ("played", "Played"),
                    ("completed", "Completed"),
                    ("retired", "Retired"),
                    ("shelved", "Shelved"),
                    ("abandoned", "Abandoned"),
                ],
                default="unplayed",
                max_length=9,
            ),
        ),
    ]
