# Generated by Django 6.0.7 on 2026-08-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0029_playergame_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="playergame",
            name="mastered",
            field=models.BooleanField(default=False),
        ),
    ]
