# Generated by Django 6.0.6 on 2026-07-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0029_userpreferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("system", "System"),
                    ("light", "Light"),
                    ("dark", "Dark"),
                ],
                default=None,
                max_length=6,
                null=True,
            ),
        ),
    ]
