# Generated by Django 6.0.7 on 2026-10-01 11:37

import uuid

import django.db.models.deletion
from django.db import migrations, models

import timetracker.uuidv7


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0029_exchangerate_decimal_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseValuation",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=timetracker.uuidv7.PostgreSQLUUIDv7(),
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("purchase_id", models.UUIDField()),
                ("target_currency", models.CharField(max_length=3)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=26)),
                ("source_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("source_currency", models.CharField(max_length=3)),
                ("rate_year", models.PositiveSmallIntegerField()),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=12, default=None, max_digits=24, null=True
                    ),
                ),
                ("version", models.PositiveBigIntegerField()),
                ("calculated_at", models.DateTimeField()),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="games.userlibrary",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("purchase_id", "target_currency"),
                        name="games_purchasevaluation_one_per_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("amount__gte", 0), ("source_amount__gte", 0)
                        ),
                        name="games_purchasevaluation_amounts_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("amount", models.F("source_amount")),
                                ("rate__isnull", True),
                                models.Q(
                                    ("source_currency", models.F("target_currency")),
                                    ("source_amount", 0),
                                    _connector="OR",
                                ),
                            ),
                            models.Q(
                                ("rate__gt", 0),
                                ("rate__isnull", False),
                                models.Q(
                                    ("source_currency", models.F("target_currency")),
                                    _negated=True,
                                ),
                                models.Q(("source_amount", 0), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="games_purchasevaluation_rate_where_needed",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source_currency__regex", "^[A-Z]{3}$"),
                            ("target_currency__regex", "^[A-Z]{3}$"),
                        ),
                        name="games_purchasevaluation_currency_codes",
                    ),
                ],
            },
        ),
    ]
