# Generated by Django 6.0.7 on 2026-08-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0030_playergame_mastered"),
    ]

    operations = [
        migrations.AddField(
            model_name="playergame",
            name="excluded_from_unfinished",
            field=models.BooleanField(default=False),
        ),
    ]
