# Generated by Django 6.0.6 on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0030_userpreferences_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="date_format_locale",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="display_time_zone",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
