# Generated by Django 6.0.7 on 2026-08-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0031_playergame_excluded_from_unfinished"),
    ]

    operations = [
        migrations.AddField(
            model_name="playergame",
            name="removed_at",
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
    ]
