# Generated by Django 6.0.6 on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0031_userpreferences_presentation_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="datetime_format",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
