# Generated by Django 6.0.6 on 2026-07-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_userpreferences_datetime_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='timestamp_end_timezone',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='timestamp_start_timezone',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
