# Generated by Django 4.2.7 on 2023-11-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0032_alter_session_options_session_modified_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="edition",
            unique_together={("name", "platform", "year_released")},
        ),
    ]
