# Generated by Django 6.0.7 on 2026-10-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0033_legacy_purchase_reverse"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlibrarypreferences",
            name="conversion_review_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
