# Generated by Django 6.0.6 on 2026-08-09 14:45

import django.db.models.expressions
import django.db.models.functions.comparison
from django.db import migrations, models

import games.expressions


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0033_session_timestamp_end_timezone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="duration_total",
        ),
        migrations.AddField(
            model_name="session",
            name="duration_total",
            field=models.GeneratedField(
                db_persist=True,
                expression=games.expressions.DatabaseDurationSum(
                    django.db.models.functions.comparison.Coalesce(
                        django.db.models.expressions.CombinedExpression(
                            models.F("timestamp_end"), "-", models.F("timestamp_start")
                        ),
                        0,
                    ),
                    models.F("duration_manual"),
                ),
                output_field=models.DurationField(),
            ),
        ),
    ]
