# Generated by Django 5.1 on 2024-08-11 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0034_purchase_date_dropped_purchase_infinite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="device",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="games.device",
            ),
        ),
    ]
