# Generated by Django 6.0.6 on 2026-08-09 15:24

import django.db.models.expressions
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0034_alter_session_duration_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="price_per_game",
        ),
        migrations.AddField(
            model_name="purchase",
            name="price_per_game",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    django.db.models.functions.comparison.Coalesce(
                        models.F("converted_price"), models.F("price"), 0
                    ),
                    "/",
                    django.db.models.functions.comparison.NullIf(
                        models.F("num_purchases"), 0
                    ),
                ),
                output_field=models.FloatField(),
            ),
        ),
    ]
