# Generated by Django 6.0.7 on 2026-08-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0034_temporal_functions_search_path"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="libraryidempotencyrecord",
            name="library_idempotency_first_sequence_positive",
        ),
        migrations.RemoveConstraint(
            model_name="libraryidempotencyrecord",
            name="library_idempotency_range_ordered",
        ),
        migrations.AlterField(
            model_name="libraryidempotencyrecord",
            name="first_sequence",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="libraryidempotencyrecord",
            name="last_sequence",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name="libraryidempotencyrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("first_sequence__isnull", True),
                        ("last_sequence__isnull", True),
                    ),
                    models.Q(
                        ("first_sequence__gte", 1),
                        ("first_sequence__isnull", False),
                        ("last_sequence__gte", models.F("first_sequence")),
                        ("last_sequence__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="library_idempotency_range_whole",
            ),
        ),
    ]
