# Generated by Django 6.0.7 on 2026-10-02 12:25

from django.db import migrations

RETIRED_TASK = "games.tasks.calculate_price_per_game"


def remove_retired_schedule(apps, schema_editor):
    """The retired task's lingering schedule row."""
    Schedule = apps.get_model("django_q", "Schedule")
    Schedule.objects.filter(func=RETIRED_TASK).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0034_conversion_review_hidden"),
        ("django_q", "0019_alter_task_options_alter_ormq_key_alter_ormq_lock_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LegacyPurchase",
        ),
        migrations.RunPython(remove_retired_schedule, migrations.RunPython.noop),
    ]
