# Generated by Django 6.0.6 on 2026-08-09 16:14

import django.db.models.functions.comparison
from django.db import migrations, models

import games.expressions


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0035_alter_purchase_price_per_game"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playevent",
            name="days_to_finish",
        ),
        migrations.AddField(
            model_name="playevent",
            name="days_to_finish",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    models.Case(
                        models.When(ended=models.F("started"), then=models.Value(1)),
                        default=games.expressions.DatabaseDateDifference(
                            models.F("ended"), models.F("started")
                        ),
                        output_field=models.IntegerField(),
                    ),
                    models.Value(0),
                ),
                output_field=models.IntegerField(),
            ),
        ),
    ]
