# Generated by Django 5.1 on 2024-08-11 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0035_alter_session_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='platform',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='games.platform'),
        ),
    ]
