# Generated by Django 6.0.7 on 2026-10-03 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "games",
            "0019_device_access_end_squashed_0036_defer_library_event_stream_matches_library",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlibrarypreferences",
            name="conversion_review_hidden",
        ),
    ]
