# Generated by Django 6.0.7 on 2026-08-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0036_removable_records"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["timestamp_start", "id"], name="session_start_id_idx"
            ),
        ),
    ]
