# Generated by Django 5.1.1 on 2024-10-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0037_platform_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
