# Generated by Django 6.0.8 on 2026-10-03 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0037_remove_conversion_review_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalplaytime",
            name="release",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="games.release",
            ),
        ),
        migrations.AddField(
            model_name="playersession",
            name="release",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="games.release",
            ),
        ),
    ]
