# Generated by Django 5.1.2 on 2024-11-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0038_alter_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('PC', 'PC'), ('Console', 'Console'), ('Handheld', 'Handheld'), ('Mobile', 'Mobile'), ('Single-board computer', 'Single-board computer'), ('Unknown', 'Unknown')], default='Unknown', max_length=255),
        ),
    ]
