# Generated by Django 6.0.7 on 2026-08-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0038_temporal_qualifiers"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="removed_at",
            field=models.DateTimeField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="removed_at",
            field=models.DateTimeField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="edition",
            index=models.Index(
                condition=models.Q(("removed_at__isnull", True)),
                fields=["game"],
                name="live_edition_per_game_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                condition=models.Q(("removed_at__isnull", True)),
                fields=["edition"],
                name="live_release_per_edition_idx",
            ),
        ),
    ]
