# Generated by Django 6.0.8 on 2026-10-05 10:03

import uuid

import django.db.models.deletion
from django.db import migrations, models

import timetracker.uuidv7


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0038_session_record_release"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkBatch",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=timetracker.uuidv7.PostgreSQLUUIDv7(),
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.UUIDField()),
                ("action", models.CharField(max_length=100)),
                ("undoes", models.UUIDField(null=True)),
                ("choice", models.TextField(blank=True, default="")),
                ("origin", models.TextField()),
                ("rows", models.JSONField()),
                ("position", models.PositiveIntegerField(default=0)),
                ("total", models.PositiveIntegerField(default=0)),
                ("done", models.PositiveIntegerField(default=0)),
                ("unchanged", models.PositiveIntegerField(default=0)),
                ("refused", models.PositiveIntegerField(default=0)),
                ("lost", models.PositiveIntegerField(default=0)),
                ("reasons", models.JSONField(default=list)),
                ("chunk", models.PositiveIntegerField(default=0)),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("finished", "Finished"),
                            ("stopped", "Stopped"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("stop_requested_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(null=True)),
                ("announced_at", models.DateTimeField(null=True)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="games.userlibrary",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["library", "state"],
                        name="games_bulkb_library_c8e84e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("library", "token"), name="unique_bulk_batch_token"
                    )
                ],
            },
        ),
    ]
