# Generated by Django 6.0.8 on 2026-10-05 11:12

import uuid

import django.db.models.deletion
from django.db import migrations, models

import timetracker.uuidv7


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0038_session_record_release"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkBatch",
            fields=[
                (
                    "id",
                    timetracker.uuidv7.UUIDv7Field(
                        db_default=timetracker.uuidv7.PostgreSQLUUIDv7(),
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.UUIDField()),
                ("action", models.CharField(max_length=100)),
                ("undoes", models.UUIDField(null=True)),
                ("choice", models.TextField(blank=True, default="")),
                ("origin", models.TextField()),
                ("rows", models.JSONField()),
                ("position", models.PositiveIntegerField(default=0)),
                ("total", models.PositiveIntegerField(default=0)),
                ("done", models.PositiveIntegerField(default=0)),
                ("unchanged", models.PositiveIntegerField(default=0)),
                ("refused", models.PositiveIntegerField(default=0)),
                ("lost", models.PositiveIntegerField(default=0)),
                ("reasons", models.JSONField(default=list)),
                ("chunk", models.PositiveIntegerField(default=0)),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("finished", "Finished"),
                            ("stopped", "Stopped"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("stop_requested_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(null=True)),
                ("announced_at", models.DateTimeField(null=True)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="games.userlibrary",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["library", "state"],
                        name="games_bulkb_library_c8e84e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("library", "token"), name="unique_bulk_batch_token"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("state__in", ("queued", "running")),
                            ("undoes__isnull", False),
                        ),
                        fields=("library", "undoes"),
                        name="one_live_undo_per_bulk_batch",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "state__in",
                                ("queued", "running", "finished", "stopped", "failed"),
                            )
                        ),
                        name="bulk_batch_state_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("ended_at__isnull", True),
                                ("state__in", ("queued", "running")),
                            ),
                            models.Q(
                                ("ended_at__isnull", False),
                                ("state__in", ("finished", "stopped", "failed")),
                            ),
                            _connector="OR",
                        ),
                        name="bulk_batch_ended_exactly_when_terminal",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("announced_at__isnull", True),
                            ("ended_at__isnull", False),
                            _connector="OR",
                        ),
                        name="bulk_batch_announced_after_its_end",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("position__lte", models.F("total"))),
                        name="bulk_batch_position_within_rows",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("undoes__isnull", True), ("choice", ""), _connector="OR"
                        ),
                        name="bulk_batch_undo_states_no_choice",
                    ),
                ],
            },
        ),
    ]
