# Generated by Django 6.0.8 on 2026-10-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0039_bulk_batch"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="libraryentry",
            name="games_libraryentry_access_known",
        ),
        migrations.AlterField(
            model_name="libraryentry",
            name="access",
            field=models.CharField(
                choices=[
                    ("owned", "Owned"),
                    ("borrowed", "Borrowed"),
                    ("rented", "Rented"),
                    ("subscription", "Subscription"),
                    ("trial", "Trial"),
                    ("demo", "Demo"),
                    ("pirated", "Pirated"),
                    ("unknown", "Unknown"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="libraryentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "access__in",
                        [
                            "owned",
                            "borrowed",
                            "rented",
                            "subscription",
                            "trial",
                            "demo",
                            "pirated",
                            "unknown",
                        ],
                    )
                ),
                name="games_libraryentry_access_known",
            ),
        ),
    ]
