# Generated by Django 6.0.7 on 2026-08-31 14:30

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0039_removable_editions_and_releases"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddConstraint(
            model_name="edition",
            constraint=models.UniqueConstraint(
                models.F("game"),
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("name")
                ),
                condition=models.Q(
                    ("removed_at__isnull", True), models.Q(("name", ""), _negated=True)
                ),
                name="unique_live_edition_name_per_game",
            ),
        ),
    ]
