# Generated by Django 5.1.3 on 2024-11-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0040_migrate_device_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='converted_currency',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='converted_price',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_from', models.CharField(max_length=255)),
                ('currency_to', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('rate', models.FloatField()),
            ],
            options={
                'unique_together': {('currency_from', 'currency_to', 'year')},
            },
        ),
    ]
