# Generated by Django 5.1.3 on 2025-01-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0041_purchase_converted_currency_purchase_converted_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='editions_temp',
            field=models.ManyToManyField(blank=True, related_name='temp_purchases', to='games.edition'),
        ),
    ]
