# Generated by Django 6.0.7 on 2026-09-04 20:29

import django.db.models.deletion
import django.db.models.fields
import timetracker.temporal
import timetracker.uuidv7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0042_external_reference_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playthrough',
            fields=[
                ('id', timetracker.uuidv7.UUIDv7Field(db_default=django.db.models.fields.NOT_PROVIDED, default=django.db.models.fields.NOT_PROVIDED, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('ordinary', 'Ordinary'), ('imported_history', 'Imported history')], default='ordinary', max_length=16)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('started', timetracker.temporal.TemporalValueField(blank=False, default=None, editable=False, max_length=64, null=True)),
                ('started_lower', models.GeneratedField(db_persist=True, expression=timetracker.temporal.TemporalLowerBound('started'), null=True, output_field=models.DateField(null=True), serialize=False)),
                ('started_upper', models.GeneratedField(db_persist=True, expression=timetracker.temporal.TemporalUpperBound('started'), null=True, output_field=models.DateField(null=True), serialize=False)),
                ('completed', timetracker.temporal.TemporalValueField(blank=False, default=None, editable=False, max_length=64, null=True)),
                ('completed_lower', models.GeneratedField(db_persist=True, expression=timetracker.temporal.TemporalLowerBound('completed'), null=True, output_field=models.DateField(null=True), serialize=False)),
                ('completed_upper', models.GeneratedField(db_persist=True, expression=timetracker.temporal.TemporalUpperBound('completed'), null=True, output_field=models.DateField(null=True), serialize=False)),
                ('created_at', models.DateTimeField(editable=False)),
                ('removed_at', models.DateTimeField(default=None, editable=False, null=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.userlibrary')),
                ('player_game', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='playthroughs', to='games.playergame')),
            ],
            options={
                'indexes': [models.Index(fields=['player_game', 'started_lower', 'completed_lower', 'created_at', 'id'], name='playthrough_display_order')],
            },
        ),
    ]
