# Generated by Django 5.1.3 on 2025-01-07 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0043_auto_20250107_2117"),
    ]

    operations = [
        migrations.RemoveField(model_name="purchase", name="edition"),
        migrations.RenameField(
            model_name="purchase",
            old_name="editions_temp",
            new_name="editions",
        ),
    ]
