# Generated by Django 6.0.7 on 2026-09-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0043_playthrough"),
    ]

    operations = [
        migrations.AddField(
            model_name="playthrough",
            name="completion_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="playthrough",
            name="completion_recorded_at",
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="playthrough",
            name="start_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="playthrough",
            name="start_recorded_at",
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
    ]
