# Generated by Django 5.1.3 on 2025-01-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0044_auto_20250107_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='editions',
            field=models.ManyToManyField(blank=True, related_name='purchases', to='games.edition'),
        ),
    ]
