# Generated by Django 5.1.3 on 2025-01-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0045_alter_purchase_editions'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='emulated',
            field=models.BooleanField(default=False),
        ),
    ]
