# Generated by Django 5.1.5 on 2025-01-29 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0046_session_emulated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='games.game'),
        ),
    ]
