# Generated by Django 6.0.7 on 2026-09-11 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0048_playthrough_start_repair"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playevent",
            name="game",
        ),
        migrations.DeleteModel(
            name="GameStatusChange",
        ),
        migrations.DeleteModel(
            name="PlayEvent",
        ),
    ]
