# Generated by Django 5.1.5 on 2025-01-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0051_purchase_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='editions',
        ),
    ]
