# Generated by Django 5.1.5 on 2025-01-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0052_remove_purchase_editions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edition',
        ),
    ]
