name: Django CI/CD

on:
  push:
    paths-ignore: [ 'README.md' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: |
          python -m pip install poetry
          poetry install
          poetry env info
          poetry run python manage.py migrate
          # PROD=1 poetry run pytest
  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            registry.kucharczyk.xyz/timetracker:latest
            registry.kucharczyk.xyz/timetracker:${{ env.VERSION_NUMBER }}          
    env:
      VERSION_NUMBER: 1.5.1
